### ISSUE TITLE
BCV chapter selection area is broken

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#1000]
**Describe the bug**
see https://github.com/paranext/paranext-core/pull/997#issuecomment-2225722338

**To Reproduce**
look in preview app

**Expected behavior**
should look like earlier (not that narrowly squashed)

**Comment by Sebastian-ubs** [comment]
introduced with 0dbea94234be03f41abe16e9e10f1bfc0edbc5a4 (not sure why I thought it was broken before)
was working in 1ec321a1074647529b4253038c4d19b88ab8e60d

**Comment by Sebastian-ubs** [comment]
ok, looks like in the preview app it truly is alreay broken in 1ec321a1074647529b4253038c4d19b88ab8e60d but somehow the change was only brought to the Platform app with #997 👀

**Comment by Sebastian-ubs** [comment]
Actually issues was introduced by [fix dropdown styles](https://github.com/paranext/paranext-core/commit/de550a1d0c53da9a57c45c265e0061982223a363) (#987) by the [addition](https://github.com/paranext/paranext-core/commit/de550a1d0c53da9a57c45c265e0061982223a363#diff-593ade974b2291d4db98c6a56d290de4dd0ad56861711f880c2d78b641d8ccebR121) of `.pr-twp` to the `dropdown-menu`

| without `.pr-twp`  | with |
| ------------- | ------------- |
| ![grafik](https://github.com/user-attachments/assets/ae14f7a7-0330-4ded-a38a-fec9a520c84b)  | ![grafik](https://github.com/user-attachments/assets/771539bd-3062-4585-859b-1043ef2384db)  |

**Comment by tjcouch-sil** [comment]
Doing as part of #940

**Comment by tjcouch-sil** [comment]
![image](https://github.com/user-attachments/assets/833125e6-4a06-4268-a1ac-2a8d76c731c6)

Fixed by https://github.com/paranext/paranext-core/pull/1096

**Comment by roopa0222** [comment]
Verified the fix, the BCV dropdown is displayed with spaces.

![Screenshot 2024-09-03 111006](https://github.com/user-attachments/assets/5a727f87-6361-4723-813e-4b1e8d44fe12)
