### ISSUE TITLE
Add first-pass compare versions dialog

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1001]
**User Story**
As a translator, I want to be able to collaborate with others on my Scripture projects so that we can work together effectively.

**Description**
Develop a rough-cut first draft of Compare Versions functionality in Platform.Bible.

- [ ] Create simple compare versions dialog
  - [ ] Find npm text comparison component
  - [ ] Compare usfm literally - no need to integrate editor

Compare Versions
![image of Compare Versions](https://github.com/paranext/paranext-core/assets/104016682/b7818f3a-4376-4d05-a1d0-c1622c1aaef9)

Compare Versions with version selector dropdown
![image of Compare Versions with version selector dropdown](https://github.com/paranext/paranext-core/assets/104016682/5867b0a5-f87c-41e0-a7e9-212a1fc075c7)

Project menu item
![Image](https://github.com/user-attachments/assets/d3a2f193-f1e7-4c8c-9bf3-26a4c967eb11)

Revision dropdown
![Image](https://github.com/user-attachments/assets/084bc731-27d6-4dcf-9f70-c0fc5b88945d)

**Comment by irahopkinson** [comment]
Can we discuss this? I'd really like to avoid forcing users to become developers to do version control.

**Comment by Sebastian-ubs** [comment]
Please involve somebody from ux in this discussion. Will be interesting to hear opinions and ideas.

**Comment by tjcouch-sil** [comment]
Time-box this at a medium. We should re-evaluate this if it takes too long.

**Comment by Sebastian-ubs** [comment]
https://github.com/paranext/paratext-bible-internal-extensions/pull/75 has screenshots thanks @jolierabideau

**Comment by roopa0222** [comment]
Verified that with the below steps 

1.  `Open Scripture Editor` with zzz6 project
2. Set the BCV to `Gen 1:1`
3. Click `Project > Compare versions for this project` on zzz6 webview
4. Confirm Compare versions dialog opens with 2 drop downs
5. Verified that `Select Revision one` is displayed with the list of revisions with Timestamp,User Info and Book
6. Verify that `Select Revision two` is displayed with the list of revisions with Timestamp. UserInfo and Book
7.  The diff displays the highlighted text with 'Red' and `-`  for deletion and 'Green' / `+` for adding text.
8. The dropdown selections are persisted even as the dialog was moved around.
9. The dropdown selections are persisted even as the application is reopened.

There are few things PT10 is different from PT95
**Note :**
- In PT95 the Left side pane and Right side pane are independent, they can scroll or place cursor with keys independently.They both are in sync once the cursor is placed.
- In PT95 the compare version dialog opens up with default `Current` on left side and `Base version` on the right side.In PT10 user have to select and it is not displayed as default.
- In PT10 both panes scroll together.
- In PT10 We can also not place a cursor in either of the panes
- In PT10 there is no option to compare different projects or resources with the current project like in PT95
 

![Screenshot 2024-11-11 104254](https://github.com/user-attachments/assets/98d511ee-844c-4729-9229-d7bc6544141f)

![Screenshot 2024-11-11 145402](https://github.com/user-attachments/assets/67f5807b-fc45-461b-98e3-7031202b016f)
