### ISSUE TITLE
Create/hook up Check Results List

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1002]
**User Story**
As a user, I want to run some checks on my project so that I know what errors are present.

**Description**
Use whatever progress has been made so far and continue it to implement the run checks dialog (in the same extension the check stuff is in - at time of writing, the platform scripture extension):
- [x] Add a Checks results list web view in which you can see the results of running checks on a project.
- [x] Running the checks should result in displaying the checks in this web view. The run checks dialog and setting all that up is in #533, so you can just figure out some way to run the checks for this if that isn't yet implemented
- [x] Make the title of the run checks web view "Checks (n items): XYZ" where "XYZ" is the short name of the project

**Comment by roopa0222** [comment]
Testing Steps

1. On the main PB hamburger menu click on `Scripture Editor` with zzz6_2021-08016 project
2. On the Scripture Editor click on the `Configure Checks` webview menu item
3. On the `Configure Checks - zzz6_2021-08-16` webview menu,
4. Check the `Repeated Word` check box.
5. On the Configure Checks , webview menu click on 'Show Results list'
6. Verify that `Show Check Result` is displayed as a webview.
7. Verify that `Repeated Checks` are displayed on the `Show Check Results`
8. Confirm that the title contains the number of items. `Check Results (9): zzz6_2021-08-16`

![Screenshot 2024-09-10 144002](https://github.com/user-attachments/assets/945677a8-c864-46a1-a58f-6343fcd18267)
