### ISSUE TITLE
Update logos to new design

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1003]
**User Story**
As a person who dislikes the old logo, I want to see the new logos so that I can be happy.

**Description**
When we get the new logos, replace the old ones everywhere in our code, both platform and paratext 10

If you want to see everything:
https://www.figma.com/design/HmkSS4H3IiX1mOHF7FOiqO/Visual-Identity-(Brand-Logo)?node-id=305-10057

Google drive with exact things we need:
https://drive.google.com/drive/folders/1fFuaJ2Hz7ysEtdSPUX1Gk6rVt5zUdyhE?usp=drive_link

**Comment by tjcouch-sil** [comment]
We need the following:
- Discord server logo
- Platform.Bible App icon (please label distinct icons for different OSes where appropriate)
- Paratext 10 Studio App icon (please label distinct icons for different OSes where appropriate)
- Platform.Bible icon and word together thing
- Paratext 10 Studio icon and word together thing

**Comment by katherinejensen00** [comment]
Github
Discord
Support.Bible (coordinate with Lingxin)
Platform.Bible
Paratext 10
~~Platform.Bible website ~~
~~Paratext 10 website~~

**Comment by merchako** [comment]
| Description                                     | Filename(s)                 |
|-------------------------------------------------|-----------------------------|
| Discord server logo                             | `app icon platform r1@2x.png `|
| Platform.Bible App icon (all)                   | `app icon platform r2.svg`    |
| Paratext 10 Studio App icon (all)               | `app icon paratext r2.svg`    |
| Platform.Bible icon and word together thing     | `Lockup Inline Platform.*`    |
| Paratext 10 Studio icon and word together thing | `Lockup Inline Paratext.* `   |
| Platform.Bible flat icon without word           |`Logomark Platform.*`         |
| Paratext 10 Studio flat icon without word       | `Logomark Paratext.* `        |

**Comment by tjcouch-sil** [comment]
Hey @merchako ! Thanks for posting those :) very helpful. I noticed a few things that seem to be missing from the folder. I may be missing something. Here are what seem to be missing:

- All `app icon ___ ___.png/svg` files. I only see `jpg`s.
- `Lockup Inline Platform` on a transparent background. I only see ones on colored backgrounds. I do see transparent ones for Paratext

Would you mind double checking for me please? Also, sorry we forgot to discuss before, but would you mind providing all of these in png *and* svg please? We need both in some contexts, so it would be helpful to have them ready.

**Comment by merchako** [comment]
try now
—Alex Mercado

**Comment by tombogle** [comment]
There are a lot of files in that Google Drive folder, but I don't see **app icon platform r1@2x.png** (there are ,

**Comment by tombogle** [comment]
@merchako There are a lot of files in that Google Drive folder, but I don't see **app icon platform r1@2x.png**, **app icon platform r2.svg** , **app icon paratext r2.svg**, etc. What I do see is that all the @2x versions seem to have an SVG and and JPEG, and all the corresponding PNG files do not have the @2x. Am I correct in assuming that @2x mean twice the size and @3x means thrice the size? Since SVG files are inherently scalable, it doesn't seem sensible to use 2x or 3x in naming them, unless you've actually done some special tweaking to enhance/add details at the larger size (in which case I guess we'd need all versions and some indication at what resolutions to use which versions).
Also, @tjcouch-sil, unless my eyes deceive me, the icon on Discord looks more curvy than the flat versions I see in that Google Drive folder. I don't think I have credentials to change that icon. I guess on Discord the Paratext server will continue to use the P9 logo for now.

**Comment by tombogle** [comment]
@CraigNisbett , @GlennPruitt , @lyonsil , or @tjcouch-sil I also don't have credentials to change the Paranext organization logo on Github.

**Comment by CraigNisbett** [comment]
Hi Tom,

I’ve added you to the Paranext Admin group, so you should now be able to
update the logos. When you’ve finished, could you let me know so I can
update the admin settings?

Thanks

Craig
*Craig Nisbett*
Project Manager
***@***.***
*SIL International*
[image: Home] <https://www.sil.org>

**Comment by merchako** [comment]
I think Figma might have added @2X to the file names of all the SVG files against my will. You can rename them or treat them as if they were the same.

The `@2X` is supposed to mean double resolution, but there’s no such thing as double resolution for SVG vectors graphics, so it’s meaningless

There is a Discord file that is indeed more curvy around the edges than the other flat files, but the current Discord image is not it. I added a gradient to it to make it look more dimensional. The gradient is meant to fit the shape of the Discord avatar.

—-

I’m wondering if it might be helpful to have an assets folder, where each of the uses of the images is its own file (e.g., GitHub avatar), but that file is a simlink to the real asset (e.g., logo mark on dark). Then we only have to replace one file to change all of uses.

This naming abstraction could also be done in the Figma output settings, but you’d miss out on any file size optimizations.

**Comment by irahopkinson** [comment]
> When using the app icons in the code, do we want to preserve the new file names, or rename them to the generic "icon.png", for example?

You'll need to use `/assets/icon.png` and `/assets/icon.svg` for the App icon as the build system is expecting that to deliver icons for all OSes.

**Comment by tombogle** [comment]
@merchako I wonder if it is intentional that **Lockup Inline Platform** has more space to the left than to the right? When displayed in a frame where the edges of the image come close to the edges of the frame, it gives me the impression that it was trying to be centered but didn't quite succeed.

**Comment by merchako** [comment]
> **Lockup Inline Platform** has more space to the left than to the right?

This possible @tombogle, and it's likely unintentional…to an extent. There's a difference between furthest-pixel centering and optical centering. I didn't go through the effect to nail optical centering.

Currently, it's just centered based on the containing frame of the logomark plus the containing frame of the logotype. There *is* more whitespace on the left. This is a bit sloppy, but if we don't see any specific problems in our artifacts, I'll hold off on changing it. (I'm traveling, and there's a surprising bit of complexity in Figma to get these elements to line up while still being able to swap out colors, variants, and elements.)

**Comment by tombogle** [comment]
For "Paranext (white-label repo), with copies of the Platform logo", I'm wondering if it would be better in some way use a quasi-generic "example" logo instead of a copy of the Platform logo to perhaps better illustrate the intention?

**Comment by tombogle** [comment]
https://github.com/paranext/extension-marketplace-services/pull/336
https://github.com/paranext/paranext/pull/26

**Comment by tjcouch-sil** [comment]
> For "Paranext (white-label repo), with copies of the Platform logo", I'm wondering if it would be better in some way use a quasi-generic "example" logo instead of a copy of the Platform logo to perhaps better illustrate the intention?

I suggested doing this as well, but Glenn said he wanted the output of that repo to be P.B. Otherwise someone might accidentally create something strange with that repo.

**Comment by tombogle** [comment]
Does anyone (@jolierabideau - ???) know what the warning on Mac looks like when installing the unsigned **Paratext 10 Studio** build? The readme currently says it will say "Paratext 10 Studio" but links to doc-meta\mac-arm-damaged-warning.png, which says "Platform.Bible". Wondering if the actual warning in this case will say "Platform.Bible" or "Paratext 10 Studio". If the latter, then it would be nice to get an accurate screenshot of that and replace the file in paratext-10-studio/doc-meta

**Comment by jolierabideau** [comment]
@tombogle It will say "Paratext 10 Studio", I can work on getting the accurate screenshot soon
