### ISSUE TITLE
Typing a backslash breaks the editor

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1007]
**Describe the bug**
Adding a backslash either makes a word disappear or breaks the editor completely.

**To Reproduce**

1. Click right before a word anywhere in the editor text
2. Enter a backslash \
3. See the word disappear because that word became an unknown marker (warning shows in the console)
4. Click right before a space anywhere in the editor text
5. Enter a backslash \
6. Catastrophic error. The editor completely breaks and is unable to load anymore until you manually edit the USFM

![image](https://github.com/user-attachments/assets/9ca1770e-3d85-416f-a50d-4ebfac66612d)

Looks like the backslash needs to be escaped somehow. I guess when/how to escape it depends on whether lone backslashes are valid USJ/X and how to escape backslashes in USFM.

**Expected behavior**
Backslash adds a backslash and doesn't break anything.

**Comment by roopa0222** [comment]
Opened Scripture Editor from the main P.B. menu. 

On Psalms 1:1 enter `\` . It does not affect the editor and no error messages are displayed on the console.
The Scripture Editor has not crashed.
