### ISSUE TITLE
BCV menu is behind floating windows

### ISSUE THREAD

**Issue by irahopkinson** [paranext/paranext-core#1055]
**Describe the bug**
If a floating window is below the BCV control then the BCV menu opens is behind the floating window:

![image](https://github.com/user-attachments/assets/42945801-1eea-48e7-a28b-8dabaaff65b1)

**To Reproduce**

1. run **Platform**
2. open a project
3. click on the **project icon** to open the menu
4. select _Inventory: Characters_
5. move the **Character Inventory** floating window under the **BCV** control
6. click in the **BCV** control
7. the BCV menu is under the floating window

**Expected behavior**
The BCV menu is above the floating window.

**Comment by tjcouch-sil** [comment]
Doing as part of #940

**Comment by tjcouch-sil** [comment]
![image](https://github.com/user-attachments/assets/833125e6-4a06-4268-a1ac-2a8d76c731c6)

Fixed by https://github.com/paranext/paranext-core/pull/1096

**Comment by roopa0222** [comment]
I verified the fix.

Steps.
1. On the scripture editor webview menu, click on webview menu item 'Inventory : Character'  
2. Floating Character Inventory is displayed.
3. Click on the BCV on the main menu
4. Verify that BCV dropdown is displayed over the floating 'Character Inventory'

![Screenshot 2024-09-03 111757](https://github.com/user-attachments/assets/91dae134-ca79-4498-87dc-2c91b9bc8e2d)
