### ISSUE TITLE
WordList - Not updating with new results when BCV is changed

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1080]
**Describe the bug**
Initially when the Wordlist is opened with Mark 1:1 . It displays the Wordlist results for the Book of Mark. When the BCV is changed to another book Haggai 1:1 it is not reflected in new wordlist results.

**To Reproduce**
1. Open the word list from the main hamburger menu on P.B
2. WordList displays the results of the BCV book (Initially Ex Mark 1:1)
3. Change the BCV to another book - Haggai 1:1
4. Notice that the wordlist is not updated with the new results.

**Expected behavior**
WordList should display the new book results and should fetch content based on the main BCV changes.

**Comment by rolfheij-sil** [comment]
Could not be replicated by Roopa or me on latest main
