### ISSUE TITLE
Wordlist does not fetch results based on the verse

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1082]
**Describe the bug**
WordList results can not be narrowed down based on the 'Verse' on the dropdown in the UI.

**To Reproduce**

1. Open the wordlist from the main PB menu with Mark 1:1 on BCV
2. Wordlist display results with 'Book' in the dropdown
3. Narrow the results based on the 'Verse' from the dropdown. The results are not updated.

**Expected behavior**
WordList should display narrowed down display results based on the 'Verse'

**Comment by rolfheij-sil** [comment]
Could not be replicated by Roopa or me on latest main
