### ISSUE TITLE
Missing file exceptions are thrown for image files

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1133]
**Describe the bug**
I got the latest code 9/11/2024. I notice missing file 404 errors for images.

**To Reproduce**

1. On the main PB , click on `Scripture editor`  with WEB project
2. Notice there are 404 errors thrown for files not found

**Expected behavior**
You should be able to find image files and not have any exceptions.

![Files_Not_Found](https://github.com/user-attachments/assets/25ab62bb-56d7-480d-b98d-392c063d368b)

**Comment by irahopkinson** [comment]
I can confirm that going to the commit on **main** before #1102 was merged does not produce this error.
