### ISSUE TITLE
C#: Create USFM Data Provider (network object)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#114]
Make some equivalent of the `NetworkObjectService.ts` such that C# can handle network objects.

Network objects are essentially a way to share asynchronous functions across the papi in an organized way. This means there must be both a local implementation that actually runs the functions and a remote implementation that sends requests to the appropriate process. Each network object has its own unique id assigned that the local creator of the network object provides when registering the object.

In JavaScript:
- Locally, some code that wants to register a network object runs `NetworkObjectService.set(id, networkObject)`. The `NetworkObjectService` then [registers two requests](https://github.com/paranext/paranext-core/blob/23c40a805aacc75ae35f2199dffb6ee9326cb1b4/src/shared/services/NetworkObjectService.ts#L156):
  - \``object:${id}.get`\` - no parameters. Response is a stringified array with nothing in it (one day, it will be a stringified array containing names of all available functions, but it doesn't do that right now). You must register this request handler to be considered to have a network object. Note: if there is already a network object registered with this id, this request handler registration will fail. You should send a request with this request type before registering to ensure there is not already a request with this type
  - \``object:${id}.function`\` - first parameter (first entry in `contents` array) is string name of the function to run on the network object. Any remaining arguments (remaining entries in `contents` array) are passed into the network object's function as arguments.
- Remotely, some code that wants to use a network object runs `NetworkObjectService.get(id)`. The `NetworkObjectService` then sends a \``object:${id}.get`\` request for the provided id. If that request responds properly, that means there is a network object with that id. As such, it creates a proxy object whose accessor function basically just [builds a function that sends a \``object:${id}.function`\` request](https://github.com/paranext/paranext-core/blob/23c40a805aacc75ae35f2199dffb6ee9326cb1b4/src/shared/services/NetworkObjectService.ts#L254) with the arguments passed to the function
- The `NetworkObjectService` [creates a network event emitter 'object:onDidDisposeNetworkObject'](https://github.com/paranext/paranext-core/blob/23c40a805aacc75ae35f2199dffb6ee9326cb1b4/src/shared/services/NetworkObjectService.ts#L60) whose event is the string id of the network object disposed

The C# client needs to be able to register \``object:${id}.get`\` and \``object:${id}.function`\` like the local JavaScript does. One day, it may need to send remote network object requests, but we decided we will not yet implement that and will wait until we need it like with #57 

---

USFM Data Provider

```typescript
Selector: { scrRef: string }
Get data: ?
Set data: ?
```
---

Depends on #58, #181

**Comment by tjcouch-sil** [comment]
We decided we want to proceed as follows:

Goal of the C# process: provide data
Registering network objects on C#: Reflection
Ingesting other process' network objects: run the requests individually (for now)

**Comment by GlennPruitt** [comment]
https://docs.usfm.bible/usfm-usx-docs/latest/index.html

**Comment by tjcouch-sil** [comment]
Documentation on how data providers work on the websocket level https://docs.google.com/document/d/1caYfnVs15lP9bpWLZG6e3nYgwAF5zZWUAv6o2TuoSY0/edit
