### ISSUE TITLE
Update default text input style to match shadcn

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#1160]
**Describe the bug**
All text input fields are invisible in their default style

![grafik](https://github.com/user-attachments/assets/68decc7a-f21c-44c6-bd84-08118fcd6130)
see https://discord.com/channels/1064938364597436416/1288209312342347806/1288515124629340221

**To Reproduce**
In Paratext 10
1. Click the hamburger to see the main menu
2. Open "settings"
when in Paratext 10
3. Navigate to "Mercurial config" and click inside the center of the white space to the right
or in Platform
3. Navigate to "Platform Settings" and click on `{ bookNum": ...`

![grafik](https://github.com/user-attachments/assets/a5151e86-df4f-42af-ab4d-19597e345a3d)

**Expected behavior**
Not sure why our input looks different than the shadcn one, but:
- All input fields need to look like [input fields on the shadcn website](https://ui.shadcn.com/docs/components/input)
- Also check dark mode and fix the focus ring appearance
- Make sure to only add necessary styles

| shadcn website      | ![Screenshot 2024-09-26 131802](https://github.com/user-attachments/assets/160bf4e4-bf0c-48e1-b157-2dd7071145e5)     |
| ------------- | ------------- |
| __with paratext theme this should look like__  | ![grafik](https://github.com/user-attachments/assets/0edc7cbb-7fde-4476-bebe-52a670c57377) |

**Comment by tjcouch-sil** [comment]
Do you know if this problem exists other than in the settings dialog? Just interested to know the scope of the issue :) if you don't know offhand, that's fine.

**Comment by Sebastian-ubs** [comment]
I assume it is for all text inputs, as in the preview app they also show "invisible". Effort however should be low just fixing the base component style and check if that does not break any consuming components (if that's the case they should be adjusted).

**Comment by roopa0222** [comment]
I verified the PBR Input (Shacn) with the latest code fix. The input reflects the style applied in the fix.

![Screenshot 2024-10-21 121416](https://github.com/user-attachments/assets/18b64789-412a-4456-ac78-0fe985332965)
