### ISSUE TITLE
Text Collection - Window Layout

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1166]
As a Bible Translator, I want to manage the window layout on the text collection so that I can get my work done effectively.

**Description**
Layout
In PT95 the layout of the text collection is in 2 panels. The left side panel has a list of texts and the right side panel has a text display. They are 2 separate. The right side panel can be closed. 
In PB it is 1 tab/window. There is no option to close the right-side expanded text content.

![TCWindowLayoutPT95](https://github.com/user-attachments/assets/40b19485-42be-4cf9-85b1-1b51cfbdb3e8)

**Comment by Sebastian-ubs** [comment]
If you are referring to the upper x: this is part of the docking framework.
If you are referring to the lower x: closing works in platform by clicking the list entry again.

**Comment by roopa0222** [comment]
I was referring to the lower x. You are right this is covered, I overlooked it. I was only focusing on the 'X'. We may need to let users know how the new docking system works.
