### ISSUE TITLE
Console Error is thrown when Configure Checks Web view is opened.

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1170]
**Describe the bug**
When the Configure Checks webview is opened for the first time on a project , the console errors are thrown

**To Reproduce**

1. Open zzz6 project using the `Open scripture editor` form the hamburger menu
2. Open `Configure Checks` from the webview menu on zzz6 project
3. Observe the console errors. 

![ConsoleErrConfig](https://github.com/user-attachments/assets/a1543388-f117-45ea-a17b-604f477a2018)

**Expected behavior**
Should not have any errors in console

**Comment by rolfheij-sil** [comment]
This issue is handled in #1159

**Comment by roopa0222** [comment]
I have verified the fix. No console errors are thrown.
![Screenshot 2024-10-01 094425](https://github.com/user-attachments/assets/371c2030-9484-4921-a877-d12c13af5559)
