### ISSUE TITLE
Run Checks Results are not accurate.

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1171]
The `Check Results` are displayed when `Configure Checks` are exercised for the book of Exodus, and the check results for Genesis are displayed.

**To Reproduce**

1. Open zzz6 project using the Open scripture editor form the hamburger menu.
2. BCV is set to `Exodus 1:1` from previous run.
3. Open Configure Checks from the webview menu on zzz6 project
4. Observe that the `Check Results` are displayed for `Genesis`

![Screenshot 2024-09-26 170636](https://github.com/user-attachments/assets/b9064468-7a0a-44fc-8c40-8578027a2a74)

**Expected behavior**
Check Results should always display results based on the current book

Another related issue:
1. Open zzz6 project using the Open scripture editor form the hamburger menu.
2. BCV is set to `Exodus 1:1` from previous run.
3. Open Configure Checks from the webview menu on zzz6 project
4. Observe that the `Check Results` are displayed for `Genesis`
5.Change the BCV to `Numbers` without unchecking the `Repeated Words` 
6. The Check Results are added to the previous results.

**Expected behavior**
BCV changed should only display Check Results based on the current book.

![Screenshot 2024-09-26 171632](https://github.com/user-attachments/assets/aecaa6ea-5415-4bea-ad6e-b6b8f4b630a0)

Matt advice: look into filtering

To consider: can we remove the 1000 results cap as part of this?

**Comment by tombogle** [comment]
I think we'll want UX to weigh in on this. Now that **Configure Checks** is not an explicit pre-cursor to running the checks and refreshing the results and now that it is possible in the results view to group by book and expand/contract results, I'm not sure that it even makes sense to have the controls in **Configure Checks** to select books or chapters. I could see maybe adding a control to the results view (maybe either on a menu or in a collapsible pane at the top) that would determine whether the results should include all books or just the current book.

**Comment by Sebastian-ubs** [comment]
I do not see a problem on Windows
![grafik](https://github.com/user-attachments/assets/bdde754d-9aaf-4348-bff2-d2363947bf67)

**Comment by Sebastian-ubs** [comment]
Sounds reasonable yes. Thanks Tom. UX team should pick this up (by priority of when dev wants to do changes for it)

**Comment by Sebastian-ubs** [comment]
depends on
- https://github.com/paranext/ux/issues/96 and https://github.com/paranext/ux/issues/120

**Comment by lyonsil** [comment]
Moving this back to the backlog since we'll probably address this as part of #1232 in the next sprint.

**Comment by lyonsil** [comment]
This was fixed as a part of https://github.com/paranext/paranext-core/pull/1319

**Comment by lyonsil** [comment]
Actually I'm wrong about that. There is still a similar bug here I didn't realize. Reopening

**Comment by lyonsil** [comment]
The specific issue is that filtering between subscriptions with different books isn't working as it should.
