### ISSUE TITLE
Provide interaction with web views on papi via project or scroll group

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1185]
**User Story**
As an extension developer, I want to be able to interact with specific web views so that I can make complex interactions between pieces of the UI or different extensions.

**Description**
In order to support #454, we need to add some way to interact with web views for a specific project. Maybe we need to interact with a specific web view type, or maybe we need to interact with all web views focused on a project; not sure.  We probably also need to interact with web views by scroll group.

Maybe we should add some kind of message passing between the web view provider and the web view, then the web view provider can broker the communication. Or open it up so anyone can send messages. Or maybe we add some way to update web view state from the web view provider. Or open it up to anyone.

- [x] Rename stuff (deprecate old stuff but keep for now)
  - [x] `papi.webViews.getWebView` -> `papi.webViews.openWebView`
  - [x] `papi.webViews.getSavedWebViewDefinition` -> `papi.webViews.getOpenWebViewDefinition`
  - [x] `papi.webViews.onDidAddWebView` -> `papi.webViews.onDidOpenWebView`
  - [x] `papi.webViewProviders.register` -> `papi.webViewProviders.registerWebViewProvider`
- [x] Add `papi.webViews.onDidCloseWebView`
- [x] New network object category web view controller: allows others to interact with an api that represents a web view of a certain type. Id of the web view controller is derived from the web view id. Web view providers should register these as part of their `getWebView` if they want one 
  - [x] New method on web view provider service `registerWebViewController` (backend only)
  - [x] New method on web view service `getWebViewController`
  - [x] New shared type `WebViewController`
  - [x] Consider moving web view controller methods to web view service or maybe just `getWebViewController`
  - [x] Maybe make an abstract class `WebViewProvider`
    - [x] Handles the mutex for creating web view controllers
    - [x] Automatically run `dispose` on web view controller or make an optional web view provider method that we call when this happens to make the connection easier...?
- [x] Some form of communication between web view provider and web view - lean on [`postMessage` api](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)?
  - [x] Register request for each web view that gets put on `papi.webViewProviders.postMessageToWebView` or something
  - [x] Add some kind of nonce for some amount of security of communication

#1270 and #1305 split off for another time

**Comment by Sebastian-ubs** [comment]
Instead of implementing in-between-tab-communication, a simpler implementation to support selection for #545  could be to store a global selection and either
- select in all projects
- or select in all windows of the same project (and scroll group)

However if we want to get the exact PT9 parity the inter-tab communication is needed, as PT9 knows which tab has launched the check results list and will only do highlighting in this tab

**Comment by ianhewubs** [comment]
To support #454 my suggestion is that the results list only interacts with the project which relates to the `check` or `find` result that the user has clicked on. Any other webview which relates to the target project ought to follow it according to scroll groups (projects/resources) or verse filters (the UI that controls the content that tools display for the project they serve). Though perhaps those other webviews will only follow the focused project as a result of this work?

**Comment by tjcouch-sil** [comment]
Matt suggests considering a shared state location where we keep a number of things including which projects are associated with which web views.

**Comment by tjcouch-sil** [comment]
I propose the following:
1. Add a `getAllWebViewDefinitions` method to the web view service (consumers can filter web views down as they want. Maybe add an optional `webViewType` parameter)
2. Add an `onDidCloseWebView` (or some name) event
3. Add an `updateWebViewDefinition` or `updateWebViewState` (depending on what seems appropriate; needs more thought) method to the web view service that passes through the web view provider first so there is a way to gatekeep. Maybe provide a way to pass an identifier through so the provider has some idea who is asking to change stuff
4. Upgrade the `useWebViewState` hook to listen for updates to its state (maybe add an `onDidChangeWebViewState` event or something)

For further consideration:
5. Add way to call some kind of methods on a web view? I guess you could just register commands that need a web view id passed in, then do some state manipulation
6. Make a shared interface for `WebViewState` by `webViewType` so everyone can tell what's supposed to be in there

**Comment by Sebastian-ubs** [comment]
Investigation from PT9 for result list connection with project tab:
The PT9 result list knows which tab it was launched from - and so on double clicking a result only highlights results in that tab.
An exported PT9 result list contains a ScrTextName and ScrTextId. So even an imported list can restore this single tab connection (first trying by id, then by name).

**Comment by lyonsil** [comment]
I think there might be two different problems we're conflating here:
1) Identifying webviews by some criteria (who launched me? what editors are open and associated with project ABC? how many webviews are open of type XYZ?)
2) Sending data/comments to webviews

For 1), I would prefer not to create a webview-specific solution if we can avoid it. We have one way now to identify other things with various criteria, and that is the network object service. We already announce when objects are created and destroyed, and the created messages have a place for data unique to the object type to be sent out. This doesn't provide a way to change that state, but if that is needed, we could always create an "object updated" event.

If we don't want to keep using the existing network object approach (which is how we discover and categorize data providers and data provider factories), then I think I'd go back to the idea of a general state service. I think we'll need something like this, anyway, to provide context to menu items on whether they should be enabled or not (e.g., "cut" and "copy" are only enabled when something is selected that can be copied/cut).

For 2), I'm a little nervous about having the way to send data/messages be "I can directly manipulate the state of an object I don't own/control." Maybe the idea here was just for the provider of a webview to be able to update the state. If that's the case, then I suppose we still need to answer the question of how to pass along data/messages. Commands (or functions on a network object if we use network objects as the solution for item 1 above) seem like the straightforward answer to me.

**Comment by tjcouch-sil** [comment]
We are probably covering #616 to some extent with this issue.

**Comment by tjcouch-sil** [comment]
Testing suggestion:

1. Turn on DEV_NOISY (so the hello world extension runs)
2. If you don't already have a hello world project, create one (Main Menu -> Projects -> Create New Hello World Project) and add some names to the project with the "Add Name" button
3. Open up two Hello World Project Web Views to the same project (Main Menu -> Hello World Projects -> Open Hello World Project)
4. Put those two web views next to each other so one is above the other and both are showing
5. Open up a Hello World Project Viewer Web View for the top project web view (Web View Menu -> Open Viewer) and put it to the side of the web view (or put it wherever makes sense for you to keep track that this viewer belongs to the project web view). Repeat for the bottom web view. Make sure you don't get them crossed, and make sure you open one viewer for each project web view
6. Click the name buttons on the viewers to highlight those names on the corresponding project web view. Each viewer should control the highlight on the corresponding project web view and should NOT control both project web views
![Image](https://github.com/user-attachments/assets/c9878bc6-ac96-42d4-983f-62a84a896418)
8. Delete a name that is highlighted in exactly one of the project web views (by pressing the `-` button next to the name). Make sure the button goes away in both viewers
9. Re-add that name you deleted, and make sure its name is not highlighted anymore. Make sure the button re-appears in both viewers
10. Close one of the project web views and make sure the corresponding viewer changes so it doesn't have buttons anymore but just the names in plain text (like the bottom viewer in the picture below)
![Image](https://github.com/user-attachments/assets/e6f4a71b-e393-4925-9797-70e8db794449)
