### ISSUE TITLE
Migrate Marketplace to new kubernetes cluster

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1186]
LT Ops said we need to move our Marketplace services to a new cluster.

**Comment by lyonsil** [comment]
Migration is complete and the services appear to be working, but there were a lot of things I saw that are worth considering for follow up:
#1189 
#1190 
#1191 
#1192 
#1193

**Comment by lyonsil** [comment]
@roopa0222 If you did any validation of the marketplace when the interns were here, you can rerun those tests. If this wasn't on your list of things to do, don't worry about doing any testing of this ticket for now. Based on what I see in the logs and the websites, the migration seems to have been successful.

**Comment by roopa0222** [comment]
@lyonsil  I was not involved in the Marketplace effort. I worked on testing marketplace components in platform-bible-react and the PAPI to install/enable/disable/getallextensions from test extensions.
