### ISSUE TITLE
Document extension side loading

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#1204]
**User Story**
As a extension developer, I want to know how to test an extension I built by loading it from the filesystem.

**Description**
https://discord.com/channels/1064938364597436416/1108113398291497031/1290350148915957771

**Comment by tjcouch-sil** [comment]
Alex added some stuff to [this page](https://github.com/paranext/paranext-extension-template/wiki/Debugging-Your-Extension-in-the-Production-Application#running-your-extension-in-an-app) - does this satisfy this issue?

**Comment by Sebastian-ubs** [comment]
yep, thanks @merchako
