### ISSUE TITLE
Create checks panel component based on UX design

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#1222]
**User Story**
"As a translator I need to be able to see and filter checking results, so that I can click entries to resolve potential projects in my project"

"As a translation consultant / project administrator I need to be able to see and filter all checking results of a project so that I can review the bigger picture of the results, along with the configuration and inventories"

**Description**
A commenting component based on the ux design phase I in https://www.figma.com/design/M2zusN2e1VEqH5kuD9aguD/Checks?node-id=667-8546

This effectively combines the webview created by Rolf for enabling/disabling checks and setting the active range(s) and the component created by Tom that displays check results. This also needs to have a way for users to quickly get to UI to configure checks (which Rolf also put together).

Adding this component to other webviews is covered in other tickets.

**Implementation idea**
Should be an independent component in platform-bible-react, that is passed into the editor

depends on
- https://github.com/paranext/ux/issues/110
- ? https://github.com/BiblioNexus-Foundation/scripture-editors/issues/188
- ? https://github.com/paranext/paranext-core/issues/1220
- https://github.com/paranext/paranext-core/issues/1232

UX Design: https://www.figma.com/design/M2zusN2e1VEqH5kuD9aguD/Checks?node-id=978-5833&node-type=canvas&t=HlxQVQvsIMVn7eS3-0

**Comment by Sebastian-ubs** [comment]
talked about during roadmap meeting that the required dev parts would roughly be
1. book+chapter selection / checks running multiplexer
2. implement the component 
3. add that component
4. put into dedicated webview
5. open bugs that roopa filed, how checks are run

**Comment by katherinejensen00** [comment]
Duplicate is #1283
