### ISSUE TITLE
Create MUI based checkbox component

### ISSUE THREAD

**Issue by rolfheij-sil** [paranext/paranext-core#123]
Create a custom Checkbox component, based on the [Material UI Checkbox component](https://mui.com/material-ui/react-checkbox/)
You can see what props are available [on this page](https://mui.com/material-ui/api/checkbox/).
Select the ones you think should be exposed to our users.

The work for this issue is very similar to #40
Code for that is in [this pull request](https://github.com/paranext/paranext-core/pull/96)

**Comment by tombogle** [comment]
In .net, I'm used to a checkbox having an accompanying text label. Are we looking for a bare checkbox component here, or do we want to build a control that also includes the label portion?

**Comment by rolfheij-sil** [comment]
I'd say just the checkbox for now. The label portion would require things like `<FormControl /> <FormControlLabel /> <FormGroup /> <FormLabel />` and possibly others. Best to leave that work for some other time

**Comment by FoolRunning** [comment]
I think I would disagree with that. A checkbox without a text label isn't very useful. Maybe we should discuss as a group?

**Comment by rolfheij-sil** [comment]
I agree that the label should be added at some point, but just as a first start for Tom to get familiar with the code base et cetera a simple checkbox will do. Adding the label could/should be a follow up to this task. At least that's the way I feel about it. We could discuss as a group if needed

**Comment by tombogle** [comment]
I have created a PR for the change without the label. I think, however, that it would be good (for me?) to attempt to add the label. So far, I didn't learn a whole lot. Mostly just how to copy code and use find-replace.

**Comment by rolfheij-sil** [comment]
Nice, I'll have a look at the PR.

I think the work is not really about adding a label to the checkbox, but more about setting up a framework for forms, using all of these components: `<FormControl /> <FormControlLabel /> <FormGroup /> <FormLabel />`, and possibly more.
If we get that done we will get the ability to add labels to checkboxes for free
