### ISSUE TITLE
Fully remove MUI (tech debt)

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#1231]
**User Story**
As a user, I want a consistent UI design so that the design makes sense without meaningless confusing differences.

**Description**
We are moving from MUI to Shadcn/Tailwind. 

**Implementation idea**
Remove any remaining MUI components and unnecessary packages.

**Comment by Sebastian-ubs** [comment]
Is this a duplicate of #937?

**Comment by katherinejensen00** [comment]
Yes, good catch, Sebastian!

**Comment by katherinejensen00** [comment]
Duplicate of #937
