### ISSUE TITLE
Checks: Add "multiplexer" so that multiple web views can configure check service

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#1232]
#1222 implies multiple UIs will be configuring the check service, so we need a way for them all to communicate without overwriting settings from each other.

**Comment by tjcouch-sil** [comment]
I propose the following:
- Change the check service so its apis revolve around uses of checks/ranges/projects. The check service is the multiplexer that determines what combinations of checks/ranges/projects need to be run. No more enable/disable checks and ranges endpoints...? Do we need them anymore?

And one of the following:
1. Change data provider subscriptions so subscribing actually informs the data provider of subscribes and unsubscribes so it can tell what data is being used (I guess we could also add a way to send an identifier to inform the data provider of who is using the data). Use this to determine what checks/ranges/projects need to be run. This would possibly also be useful in other contexts as well.
2. Add apis to the check service so consumers of checks inform the check service when they want to use its data and when they are done using it or want to change what they're using. Pretty much the same as #1 but kinda a shortcut.

In either case, we will probably need to tune some things up like closing web views so they actually run the unsubscribers. I don't expect they do now.

**Comment by irahopkinson** [comment]
Is it too early to consider using YJS docs for these settings? You can observe that doc for changes. And it would be moving in the right direction so that collab just works.

**Comment by lyonsil** [comment]
I think we can fix #1171 as part of this issue because we're going to have to be reworking the relevant part of the code anyway.

**Comment by jolierabideau** [comment]
May also be able to fix #1244 as part of this issue

**Comment by roopa0222** [comment]
Test Repo steps:
I got the latest code and verified that multiple projects can have checks configured on different books and ranges.

1. Project > Open Scripture Editor > zzz6
2. Set BCV to Exodus 1:1
3. zzz6 > Configure Checks.. 
4. Check `Capitalization` and `Chapter/Verse Numbers` check and get the subscription ID from the console log
5.zzz6 > Show Check Results.. and provide the subscription ID
6. Confirmed that all the results related to zzz6 are displayed
7. Repeat the same with project zzz5.
8. Set the BCV to Mattew 1:1
9. zzz5 > Configure Checks.. 
10. Check `Capitalization` and `Punctuation` check and get the subscription ID from the console log
11.zzz5 > Show Check Results.. and provide the subscription id
12. Confirm that the Results are displayed only for the book of Matthew.

![Image](https://github.com/user-attachments/assets/ea1d06e7-b514-4cb2-9adf-093cdf02faa1)
