### ISSUE TITLE
Add checks panel component to editor webview

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#1233]
#1222 defines a panel that enables checks to run on text in the editor. This issue is for actually adding that panel (component) to the editor webview so users can use it.

Depends on #1185, #1283, and #1232

**Comment by katherinejensen00** [comment]
When we talked about the checks side panel component, we realized that implementing the "island" version would be pretty different from implementing the editor margin so they will be separate implementations and this work will be completed in #1287
