### ISSUE TITLE
Enable Platform.Bible to read downloaded resources

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#1240]
**User Story**
As a user, I want to see resources that I download through download resources so that I can easily access them in the resource viewer.

**Description**
Make downloaded resources available/discoverable to the resource viewer

**Implementation idea**

- [ ] Hook up the Paratext Data dll so that our dotnet process can find the downloaded resources in the `~/.platform.bible/projects/Paratext 9 Projects/_Resources` folder in the normal Platform.Bible data folder (just like Paratext resources)
  - To use DBL resources, the user must have a valid Paratext registration. Before opening these password-protected resources, throw an error explaining this if the user doesn't have a valid Paratext registration.
- [ ]  Make resources available in the resource viewer
- [ ] Make sure you don't commit secrets to the repo!

Paratext's DBL downloading stuff is in `InstallableDBLResource.cs` and `InstallResourcesForm.cs`.

**Comment by katherinejensen00** [comment]
Paratext dll might handle the security for us (hopefully)

**Comment by irahopkinson** [comment]
You can add GH secrets at the org level so all repos in the GH org have access to them.
