### ISSUE TITLE
Configure Checks : In Active ranges when Choose Books option is selected only the last books results are shown

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1244]
**Describe the bug**
On the zzz6 project, `Config Checks` select `Repeated words` when the option `Choose Books` is selected with `Psalms Genesis`. The Results are displayed only for the book of `Genesis`. Instead of both books.

**To Reproduce**

1. Set BCV to `Psalms 1:1`
2. Open `zzz6` project using the `Open scripture editor` from the main menu
3. Open `Configure check` and select `Repeated words`
4. Open `Show Check Results` .. 
5. Notice that there are 5 words in the results list for the `Psalms 1:150` active ranges 
6. Opt `Choose Books` in active ranges and include `Genesis` to the list
7. Notice that the Results are updated with only `Genesis`. Instead of displaying both `Psalms Genesis`

**Expected behavior**
When more than 1 is selected in the Active ranges `Choose Books`.Results if available in all books should be displayed.

Results from Psalms 
![Screenshot 2024-10-28 144444](https://github.com/user-attachments/assets/53a6036b-666f-4662-a00d-cede80b8133a)

Results from Psalms and Genesis
![ResultsFromMorebooks](https://github.com/user-attachments/assets/e7e8184f-1b0c-42f1-af7f-1c53d09c0b42)

**Comment by jolierabideau** [comment]
Could be linked to #1171

**Comment by Sebastian-ubs** [comment]
depends on
- https://github.com/paranext/ux/issues/96 and https://github.com/paranext/ux/issues/120

**Comment by lyonsil** [comment]
This was fixed as a part of https://github.com/paranext/paranext-core/pull/1319

**Comment by lyonsil** [comment]
This particular bug was fixed, but there is a related bug that still exists. #1171 was reopened to cover this.
