### ISSUE TITLE
Add ability to configure `InternetSettings.xml`

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#1254]
**User Story**
As a Bible translator, I want to be able to log in as my Paratext Registry user without opening Paratext 9 so that I can see available resources, use S/R, etc. without having to log in on Paratext 9.

**Description**
In order for S/R and such to work properly using only Paratext 10, we need to add the ability to configure `InternetSettings.xml`.
- [x] Add some way to configure `InternetSettings.xml`
  - Maybe just add a user setting that coordinates to each entry somehow? Actually might make a mess to have it be user settings because all user settings are stored by main process.
  - Make sure it is clear this is only changing internet settings for ParatextData.dll
- [x] When there is an error in S/R because your internet settings are set to proxy (default), add a special error note in the S/R dialog that you may want to look at these settings. Make the error clickable so you can open settings. If #1251 is done, add a link to go directly to the setting
- [x] Update the link to setting up S/R in the code to https://github.com/paranext/paranext/wiki/How-to-make-Send-Receive-work-in-Paratext-10-Studio
- [x] Change the default value for setting `paratextRegistration.shouldShowOnStartup` to `true` in Paratext 10 Studio only

**Implementation idea**
![Image](https://github.com/user-attachments/assets/ae5db0b8-a383-44f9-bfb7-fc50b5d8b3b1)

![Image](https://github.com/user-attachments/assets/8105e64d-1685-455c-a00e-4441610f8239)

Shift+Click Mega menu
![Image](https://github.com/user-attachments/assets/ead84c94-1e27-4a5e-8723-ba0626074a72)

`InternetAccess.RawStatus`
`InternetAccess.SetProxy`
`InternetAccess.SelectedServers`

**Testing idea**
1. Temporarily remove `%localappdata%/Paratext95/InternetSettings.xml` and
`%localappdata%/Paratext95/RegistrationInfo.xml`
2. Open Paratext 10 Studio and make sure the Paratext Registration Information dialog opens automatically (it should not open automatically in Platform.Bible.)
3. Uncheck the setting Main menu -> Settings -> Paratext Registration and Internet Settings -> Show Paratext Registration Web View on Startup (in Platform.Bible, this will be unchecked by default)
4. Close Paratext 10 Studio and open it again. Make sure the Paratext Registration Information dialog does not open automatically
5. Open S/R dialog and make sure it shows an error and a button to configure Paratext registration and internet settings
6. Click the button - it should open the Paratext Registration Information dialog
7. Set up your registry information again and set the Internet Setting Paratext Servers to Development (or whatever your usual one is). Click Save and Restart and wait for it to restart
8. Open S/R dialog and make sure it loads projects appropriately

**Comment by tjcouch-sil** [comment]
Yes, this is simply a stipulation for now. We intend to change this at some point. One setting indeed.

**Comment by Sebastian-ubs** [comment]
Right. Just in case implementing it for the whole app at once would not be much effort, I guess that would pay out, as releasing with a setting that will later be changed adds effort for migration:
- either for us writing a release note + the users to switch it
- or for us writing an automated migration step

**Comment by Sebastian-ubs** [comment]
Decision/info during roadmap meeting: Currently only Paratext dll related internet communication

**Comment by lyonsil** [comment]
We can add this to the bottom of the Paratext Registration UI for now because putting it where it might belong long-term (i.e., the settings UI) would be problematic for now. This should not stay in this dialog forever.

**Comment by tjcouch-sil** [comment]
PRs:
[Added internet settings to Paratext registration info form, fixed disabling internet in sensitive locations - 1 unreplied - Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1320)
[Simplified path to filling out Paratext Registration info, removed pa… by tjcouch-sil · Pull Request #19 · paranext/paratext-10-studio](https://github.com/paranext/paratext-10-studio/pull/19)
[Added button linking to Paratext Registration when getting projects for S/R fails by tjcouch-sil · Pull Request #80 · paranext/paratext-bible-internal-extensions](https://github.com/paranext/paratext-bible-internal-extensions/pull/80)

Documentation changes:
[Can't use GitHub password · paranext/paratext-10-studio@0b82fc9](https://github.com/paranext/paratext-10-studio/commit/0b82fc908b19830873ec64cfaf50b54970ce4ba7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R240)

**Comment by roopa0222** [comment]
Verified the issue with the below repo steps with Paratext 10 Studio 0.1.0-commit.3621a8d.exe
**Testing idea**

1. Temporarily remove %localappdata%/Paratext95/InternetSettings.xml and %localappdata%/Paratext95/RegistrationInfo.xml
2. Open Paratext 10 Studio and make sure the Paratext Registration Information dialog opens automatically (it should not open automatically in Platform.Bible.)
3. Drop down the "Internet Settings" section and change the first dropdown to "Disable all internet use". Save and restart.
4. Uncheck the setting Main menu -> Settings -> Paratext Registration and Internet Settings -> Show Paratext Registration Web View on Startup (in Platform.Bible, this will be unchecked by default)
5. Close Paratext 10 Studio and open it again. Make sure the Paratext Registration Information dialog does not open automatically
6. Open S/R dialog from the main menu (not from a project menu) and make sure it shows an error and a button to configure Paratext registration and internet settings
7. Click the button - it should open the Paratext Registration Information dialog
8. Set up your registry information again and set the Internet Setting back to "Disable in sensitive locations" and Paratext Servers to Development (or whatever your usual one is). Click Save and Restart and wait for it to restart
9. Open S/R dialog and make sure it loads projects appropriately

Verified that all the steps work as expected

![Image](https://github.com/user-attachments/assets/913674ee-dd88-46f4-8db6-530730b7f13f)


![Image](https://github.com/user-attachments/assets/6d8c8e2f-922a-48c5-92a5-dda61cb24ccf)
