### ISSUE TITLE
In MarkdownRenderer component any link in content opens in PB instead of outside

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1266]
**Describe the bug**
As part of testing the MarkdownRenderer component , if the content has a link it is opening in the PB instead of outside

**To Reproduce**

1. On the front end try to use the `MarkdownRenderer` component from https://paranext.github.io/paranext-core/platform-bible-react/index.html 
```
  const markDownString = 'Testing Link ([Support.Bible](https://support.bible/)).';
  <MarkdownRenderer markdown={markDownString} id="TestMarkdownId" />
```

2. Notice that the link is opened in the PB instead of outside. Once opened in PB we can not navigate back to the original UI

**Expected behavior**
The link should open outside PB. There is no option prop available on the component.

![Screenshot 2024-11-05 124038](https://github.com/user-attachments/assets/8d9f7570-c2e2-4600-8792-213c24c654cd)

![Screenshot 2024-11-05 125028](https://github.com/user-attachments/assets/255d7757-7db6-423b-8879-f141a2d1e688)

**Comment by Sebastian-ubs** [comment]
Awesome, so we have the way to easily build a basic [online resource viewer](https://github.com/paranext/roadmap/issues/87) 😄

**Comment by Sebastian-ubs** [comment]
Isn't it actually happening for all links inside platform - independently of Markdown?
![Screenshot 2024-11-07 133503](https://github.com/user-attachments/assets/71a456d8-f5ef-48ad-a4fe-f97124d7afa2)
![Screenshot 2024-11-07 133521](https://github.com/user-attachments/assets/c9526cb3-4c40-47b1-afe7-02c15d80ef34)

**Comment by roopa0222** [comment]
This is recommended way to use a link in PB to open outside the app
<a href="https://support.bible/" target="_blank" rel="noreferrer">
            Link to Support.Bible
          </a>

**Comment by tjcouch-sil** [comment]
I am adding a prop `anchorTarget` to `MarkdownRenderer` that will let you set the target to `_blank` in https://github.com/paranext/paranext-core/pull/1310

Need to consider if it would be good to set the [base target](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) to `_blank`, make the `anchorTarget` prop default to `_blank`, or even expose `options` from the markdown library.

**Comment by Sebastian-ubs** [comment]
I guess a default of `_blank` makes sense (if it is clear how to make then non-blank)

**Comment by roopa0222** [comment]
I got the latest code and updated the component to use the new prop.
```
<MarkdownRenderer markdown={markDownString} id="TestMarkdownId" anchorTarget="_blank" />
```
Verified , click on any link is opened externally and not in PB/PT10

**Comment by roopa0222** [comment]
Working as expected.
