### ISSUE TITLE
Mac Installer

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#1331]
**User Story**
As a user who uses a Mac, I want to install Paratext so that I can use it when translating the Bible.

**Description**
Create a Mac installer for Paratext 10.

**Implementation idea**
See email thread with Chris Hubbard about mac installers for ideas, considerations, and to know who to reach out to for help/inspiration/commiseration
Get signing material. Talk to Glenn and/or Katherine for latest update on that (or one of us will update this before we work on it)
Create a Mac installer for Paratext 10

**Testing ideas**
Install Paratext 10 on a Mac machine

**Comment by Sebastian-ubs** [comment]
is this a duplicate of #1172 ?

**Comment by katherinejensen00** [comment]
It is close enough that I can add any extra details to the other case.

**Comment by katherinejensen00** [comment]
Duplicate of 1172
