### ISSUE TITLE
Create release 0.0.1

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#14]
- [x] Fix [installer icon](https://www.electron.build/icons.html)
- [x] Add portable package to windows
  - In package.json
  - ![Image](https://user-images.githubusercontent.com/104016682/216160917-2efe8088-fc5d-48cf-bba8-cb7a5e753386.png)
- [x] Consider the fixes in [4 must-know tips for building cross platform Electron apps](https://blog.avocode.com/4-must-know-tips-for-building-cross-platform-electron-apps-f3ae9c2bffff).

- [x] Create full release 0.0.1

Depends on #6

**Comment by irahopkinson** [comment]
For item 3 above (_4 must-know tips for building cross platform Electron apps_), the first 2 points are already a part of ERB.
