### ISSUE TITLE
Simplify "server:registerRequest" API

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#144]
Currently, the contents of "server:registerRequest" is an array containing two elements: the "requestType" to register and the clientId. However, the clientId is already supplied in the senderId. We should just make contents a string of the "requestType" because that makes more sense. I did this originally as a quick and easy solution, but we should fix it.

`{"type":"request","requestType":"server:registerRequest","requestId":2,"senderId":6,"contents":["command:addMany",6]}`

**Comment by katherinejensen00** [comment]
TJ said if this takes you more than 10 minutes, talk to TJ or assign it to him.
