### ISSUE TITLE
Investigate cra-craco-electron

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#15]
Investigate https://github.com/sillsdev/cra-craco-electron to determine if we want to restart our app on it.

- [ ] Cost from switching - how long will it take to switch now vs a year from now?
  - [x] Investigate differences from CRA and see if we can adapt ERB
- [ ] Benefits from switching
- [ ] Drawbacks from switching

**Comment by irahopkinson** [comment]
Our repo with ERB already builds for the web. After `npm run build` (or more specifically `npm run build:renderer`), open `/release/app/dist/renderer/index.html` in a browser.

We would need to make some minor adjustments to exclude electron references but if we end up not using electron IPC then we probably don't need to do anything.

**Comment by irahopkinson** [comment]
If we need to develop exclusively on the web we can just add a script in `package.json` like `"start:web": "cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.web.dev.ts",` and then create the `.erb/configs/webpack.config.web.dev.ts` file (we could eject a CRA boilerplate and adapt the webpack config from that).

However, developing React inside electron should cover just about every scenario. Once we have a feature working in electron we can then just run `/release/app/dist/renderer/index.html` with the appropriate backend to check its working the same.
