### ISSUE TITLE
Create Sneeze Board Sample Extension

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#154]
Create sneeze board client. Learning practice objectives:
- [ ] Improve React skills
- [ ] Create WebView in extension
- [ ] Create DataProvider in extension
- [ ] Cache data from server
- [ ] Use WebSocket in extension
- [ ] Create user settings
- [ ] Exercise PAPI and get feedback
- [ ] Improve accuracy of prophecy of Jesus' return*

This would provide a good starting point for the extension team, and it would make a good sample extension people could read to learn how to use the PAPI.

<sub>_*This is a false prophecy._</sub>

**Comment by FoolRunning** [comment]
👍

**Comment by katherinejensen00** [comment]
+ 1

**Comment by katherinejensen00** [comment]
The main goal of this task (create demo extension) is done. Here is a [document ](https://docs.google.com/document/d/18t0yOR_SZJwB-o6cHv03iIR_wDxQQEzGUHTAhc5Ixwk/edit) linking steps of how to get started when making a new extension. I will create a new case to turn the sneezeboard extension into an external extension to see if that would be a helpful exercise or not.

**Comment by tombogle** [comment]
@tjcouch-sil Should we add to this issue the task of adding unit tests, or should i create a separate issue for that?

**Comment by tjcouch-sil** [comment]
> @tjcouch-sil Should we add to this issue the task of adding unit tests, or should i create a separate issue for that?

Let's make a separate issue :) thanks!

**Comment by tombogle** [comment]
See #209
