### ISSUE TITLE
Split PAPI into 3 code modules and make user import from just one of them

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#172]
Divide PAPI (which contains code that does/should run only in the renderer, code that does/should run only in the extension host, and code that can run in any TS/JS context) into 3 modules.  The shared module will likely serve only as a base for the other two modules that are focused on the renderer and extension host.  Then extension developers will either import papi designed the renderer or the extension host.  The individual imported modules should only have properties that are valid for that context.

- [x] Split papi
- [x] Remove papi circular dependency
- [x] Split papt.d.ts
- [ ] Use `dts-bundle-generator` package?

**Comment by lyonsil** [comment]
This is marked "External Extension Ready" because if we do it later, we know this will be a breaking change for all extensions.

**Comment by irahopkinson** [comment]
There is a branch **172c-dts-bundle-generator** that attempted to use the `dts-bundle-generator` package (currently used in `papi-components`) to generate the `papi.d.ts` file. The branch mostly works but there are still a few errors in the `papi.d.ts` file to fix:

![Image](https://github.com/paranext/paranext-core/assets/5582153/5dc54cc9-e8d7-4b04-8820-15a1431d4cec)

Unfortunatley, the fixes for these started heading us in a direction that might make our ability to generate it fragile on how source items are written. Given this work was somewhat outside the scope of this issue anyway I haven't persued it further at this time. This initial work on the branch **172c-dts-bundle-generator** might be useful for #166 and #175.
