### ISSUE TITLE
Convert bundled Sneezeboard extension into a standalone extension

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#174]

**Comment by tombogle** [comment]
Note that the Sneezeboard+WebviewAPI branch is still in the pranext-core repo, though the last commit was to remove everything sneeze-board related. Do we want to leave that branch there for posterity, or should we delete it?

**Comment by katherinejensen00** [comment]
I am okay with deleting it

**Comment by tombogle** [comment]
Done
