### ISSUE TITLE
`window.top` is readonly - prevents us from isolating webviews

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#176]
Looks like we can't actually completely isolate webviews while sharing `React` and `papi`. Either we must disallow same origin policy which would restrict us to communication via message passing only and nothing more, or we must completely distrust the frontend and do what we can to mitigate issues. Some options:

1. We could change our strategy with the offline-only mode to set `content-src` to `'self'` only if we're offline. That way, even if some bad actor did get ahold of `fetch` or connected to some website with an image url or something, we would cut it off in offline mode. We lose security online, but at least we can maintain it offline.

2. Alternatively, we could set the `content-src` to `'self'` always and just make all internet calls have to pass through the internet service. I'm not sure if that buys us anything that approach 1 doesn't.

3. ~~Remove `allow-same-origin` from the iframe sandboxing. Then the webview can only communicate to the extension through message passing, which is what VSCode does. But we lose the ability to share React and the papi. Seems like it could get unwieldy.~~ https://github.com/paranext/paranext-core/issues/176#issuecomment-1619272129

4. Use electron protocol to enforce offline mode and control what endpoints are accessed.

We should also consider drop-in code from other extensions. Like should we do `globalThis.fetch = papi.fetch` so existing code still works? Should we allow `https` and add some kind of protocol like `papi-https` (or maybe we can just overwrite `https`) to allow offline backup image search and such?

**Comment by tjcouch-sil** [comment]
Related: #85, #89

**Comment by irahopkinson** [comment]
FYI on item 1 above, you can't robustly say you are offline, (online - yes, but not offline). Therefore there is always some time during transition where it's actually offline but we haven't detected it yet so `fetch` would still attempt fetching.

**Comment by irahopkinson** [comment]
I was talking about a browser going offline because it loses access to the internet. However, I think this is referring to a user changing a setting to say "don't use the internet at all", right?

**Comment by irahopkinson** [comment]
Some testing on `master` branch today. In `evil.js`, adding the following to the `tryImports()` method:
```typescript
  try {
    // This should NOT work because `window` and `top` are excluded from the sandbox settings.
    window.top.fetch('https://bible-api.com/1%20thessalonians+5:17');
    logger.error('Evil: top.fetch is working.');
  } catch (e) {
    logger.warn(`Evil: Error on top.fetch! ${e}`);
  }
```
results in this error: `Evil: Error on top.fetch! ReferenceError: window is not defined`.

**Comment by irahopkinson** [comment]
Opps, @tjcouch-sil pointed out that `evil.js` is only running in node and not in a webview.

**Comment by tjcouch-sil** [comment]
Glenn and Matt's discussion about security: https://docs.google.com/document/d/1BeqVqgrtQbVp7HYYdi0mGEQG8jU81qpSdFQH3fPnw8k/edit?pli=1

**Comment by tjcouch-sil** [comment]
Some thoughts on the Chrome extension stuff:

To my understanding, [Electron supports a subset of Chrome extensions](https://www.electronjs.org/docs/latest/api/extensions), and they must be manually downloaded and loaded in via the `main.ts` code to my understanding (I don't believe Electron tries to load Chrome extensions from your installed Chrome extensions or anything like that). Electron React Boilerplate starts us off with [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer) and React DevTools Chrome extension by default if in development mode.

**Comment by tjcouch-sil** [comment]
We decided we will throw out number 3 as it is likely only beneficial over the others in preventing malicious webviews from removing sandboxing, which does not have as significant consequences as content security policy. See the [sandbox attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attributes) for more info.

Let's make at least a start of a general security items list to present to Glenn to figure out how to move forward with security concerns. #277

**Comment by tjcouch-sil** [comment]
We concluded that we will make an Electron protocol handler (option 4) that will pass whatever we want when online and do one of two things when offline:
1. Call the extension's offline asset backup function to get an offline version of the requested url
2. Reject the connection attempt

This will not work naturally if we make a web version, but we can go with option 1 in a web scenario. However, we don't know how we would make an offline backup function work in the online setting with arbitrary urls due to security restrictions on protocol handlers and service workers. Hopefully the number of extensions that really need that as an option will be very minimal.

**Comment by tjcouch-sil** [comment]
Created #473 to implement the design

**Comment by tjcouch-sil** [comment]
FYI all the following are not configurable in the renderer as determined by the following code entered into the console:

```typescript
Object.keys(window).filter(key => !Object.getOwnPropertyDescriptor(window, key).configurable)

>  ['window', 'document', 'location', 'top', '__electronLog', 'electronAPI']
```
