### ISSUE TITLE
Figure out client/server pattern

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#190]
To give us a good idea of how the different options would look, we refactored [`extension-asset.service.ts`](https://github.com/paranext/paranext-core/blob/001fee24c4d9fee8f6c03a9ed93e55719a6bb552/src/shared/services/extension-asset.service.ts) in two ways:

- Matt made client/server service pattern https://github.com/paranext/paranext-core/compare/main...cross-process-server-model
- TJ made `@process` pattern https://github.com/paranext/paranext-core/compare/main...fd04d8a0abe6081f0eb27826d8df9ed84cf5b52a

**Comment by tjcouch-sil** [comment]
Here's an eslint rule to disallow certain imports. We could set this up to enforce import alias scoping in the various folders https://eslint.org/docs/latest/rules/no-restricted-imports

**Comment by irahopkinson** [comment]
> Here's an eslint rule to disallow certain imports. We could set this up to enforce import alias scoping in the various folders https://eslint.org/docs/latest/rules/no-restricted-imports

Great, I added this to the **Code Style Evaluation** doc, actually I added the TS version (https://typescript-eslint.io/rules/no-restricted-imports) which has a useful option to `allowTypeImports`.
