### ISSUE TITLE
Events over WebSocket (Node)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#22]
Create Events and Event Handler API for distribution over WebSocket

**Comment by irahopkinson** [comment]
@tjcouch-sil I'm not sure if you had in mind to do this one. Either way I'm not exactly sure what is required here. I'll look at something else until I hear from you.

What I did find is:

-  that if we used [socket.io](https://socket.io/) we would have build in support for custom events (as well as them being reconnecting without us have to write that ourselves).
- also [primus-emitter](https://www.npmjs.com/package/primus-emitter) which is old even though [primus](https://www.npmjs.com/package/primus) itself is still recent.

**Comment by tjcouch-sil** [comment]
@irahopkinson My internet went out all day Friday last week, so I didn't know exactly what to do. I thought about doing some web view stuff, but I realized I was kinda blocked by this work. As such, I went ahead and got started on events on https://github.com/paranext/paranext-core/tree/22-events . I'm sorry I jumped ahead of you on this, especially without notice. Would you like to discuss what we have both done? I haven't implemented registering for events so that event messages only go where they should - we could discuss and see if you'd like to do that work if you'd like to have a bit easier ramp into working on these services! Let me know what you think.

**Comment by tjcouch-sil** [comment]
Ira and I discussed and decided to split out #62 into its own work item. That way, we can go ahead and get this code in when we can, and we don't have to worry about who does that work.
