### ISSUE TITLE
Fix `paranext-core/extensions` vite build failure if there's an empty folder in `extensions` folder

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#233]
If the `extensions/lib` folder has an extra folder in it with no contents (or not many contents, particularly a `manifest.json` file), the Vite build will crash, and it is quite difficult to discover this issue.

This can easily occur if you make a branch where you are making a new extension, then you commit and switch off that branch. Since git doesn't care about directories, that empty extension directory will be left over.

**Comment by katherinejensen00** [comment]
Check to see if this error still occurs in Webpack

**Comment by tjcouch-sil** [comment]
This issue occurs on [this line](https://github.com/paranext/paranext-core/blob/8607101e4d625949e87a2f190a0a65f35b2bbc0c/extensions/webpack/webpack.util.ts#L253) and is fixed in #486
