### ISSUE TITLE
Create Logging Service

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#25]
We need to add a logging service so we stop using `console.whatever` all the time. Apparently we already have some kind of electron-specific logging library. Let's use it!

Some discussion on the topic: https://github.com/paranext/paranext-core/pull/24/files#r1103914506

One important place is in `ServerNetworkConnector.onClientConnect`

**Comment by irahopkinson** [comment]
@tjcouch-sil bultthe app and encountered this error:

![Image](https://user-images.githubusercontent.com/5582153/223888501-e8dfd227-cb70-424a-8ac9-8a9970f02106.png)

**Comment by irahopkinson** [comment]
In `logger.ts`, I tried:

-  `log.initialize({ preload: true });` but that didn't change anything.
- `require('electron-log/renderer');` from the client but that didn't change anything either.

**Comment by irahopkinson** [comment]
@tjcouch-sil From my shallow clone of the `electron-react-boilerplate` repo (which is where this repo is started from) I added a branch with minimal reproduction of our `logger.ts` but the production build didn't have the issue. To me this indicates (as you suggested) that it's something about our webpack config that we have changed.

**Comment by irahopkinson** [comment]
Moved the `win-unpacked` folder up the tree to see the whole of the message:

![Image](https://user-images.githubusercontent.com/5582153/224865512-53eb5ec8-2405-48b4-9b70-9dd2604ed435.png)
