### ISSUE TITLE
Create IconButton component that wraps the MUI IconButton

### ISSUE THREAD

**Issue by tombogle** [paranext/paranext-core#253]
As an extension developer, it would be helpful to have a reusable icon button so that the design of the icon button is consistent with that of icon buttons used in the core of platform.bible.

Wrap MUI IconButton.

**Comment by tjcouch-sil** [comment]
What is the difference between an IconButton and a Button (what we already have) with an image in its children? Like
```typescript
<Button>
  <img ... />
  Hi, I'm a button with an icon
</Button>
```

**Comment by tombogle** [comment]
Material UI's IconButton is similar to the Material UI Button except it has a circular ripple designed for a single icon element.

**Comment by tombogle** [comment]
https://github.com/paranext/paranext-core/pull/474
