### ISSUE TITLE
Start documenting how to make an extension

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#259]
Make some kind of starting point documentation for developing extensions:
1. Document extension api somewhere on the wiki. Lots of JSDocs and comments in the example extensions that we could at least use as a base
3. Link to example code in `paranext-core` and in various extension repos as appropriate
4. Architecture picture https://docs.google.com/presentation/d/1kR9BuUBvsXSnDlv4brfezS0CHDQ6PrrdOUn-lE3rSxk/edit#slide=id.g205fa119c26_0_104 Might be able to create a published link. Can't remember if that's available for Google Slides or not.
5. Video explaining how to make an extension? Probably split to another issue

**Comment by jolierabideau** [comment]
It was undecided where we wanted to host the docs- for now they are in [this](https://drive.google.com/drive/folders/1rowgMXwiWYysy9Hxb_jI-5xPZUQoFbou?usp=share_link) folder in the shared drive

**Comment by jolierabideau** [comment]
They are now published in the [extension template wiki ](https://github.com/paranext/paranext-extension-template/wiki)
