### ISSUE TITLE
Windows don't scroll the whole way to the bottom

### ISSUE THREAD

**Issue by mpelley** [paranext/paranext-core#290]
The bottom part of a window is cut off when the contents are large enough so that it needs to be vertically scrolled.  The attached screenshot is scrolled the whole way to the bottom.  Notice also the down arrow of the scroll bar is missing.
![image](https://github.com/paranext/paranext-core/assets/61086313/e42e42f6-71ea-4517-a345-087d7b202a4d)

**Comment by FoolRunning** [comment]
From looking into this a little bit, it looks like the new header pushed down the dock area without shrinking it vertically.
See ``height: calc(100% - 8px);`` in the definition for the ``.dock-layout`` style.

Note that the correct fix is *not* to change that to ``height: calc(100% - 56px);`` 😉

**Comment by irahopkinson** [comment]
I put in a PR for this since this as a potential prerequisite to #66.
