### ISSUE TITLE
Support running extensions against production Paranext

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#299]
As an extension developer, I want to develop my extensions and run against production Paranext so I don't have to worry about building `paranext-core` and dealing with its problems every time I run my extension.

We need to figure out a couple things to get this working:
- [x] Watch extension files and restart the extension host manually when they change (exclude these files from `nodemon` in development so watching is the same in dev and production?)
- [x] Hook up VSCode to production Paranext so we can debug extension main code

**Comment by irahopkinson** [comment]
To debug Platform app (Windows PowerShell):

1. From the **paranext-core** repo, run `npm run package:debug`.
2. Run `cd ./release/build/win-unpacked`.
3. Run `$env:ELECTRON_IS_DEV=1`.
4. Run `./ParanextCore.exe --inspect-brk=5858 --remote-debugging-port=9223`.
5. In **VS Code**,  add breakpoints in `main.ts` or below.
6. Go to **Run and Debug**.
7. Select _Attach to Platform app_, and click **Start Debugging**.
8. Click **Continue** - it should stop at your breakpoint.

**Comment by tjcouch-sil** [comment]
Split some parts off into #335 and #336

**Comment by irahopkinson** [comment]
Added [Debugging Your Extension in the Production Application](https://github.com/paranext/paranext-extension-template/wiki/Debugging-Your-Extension-in-the-Production-Application) extension Wiki page.

Updated [Troubleshooting Guide: Debug Mode](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#debug-mode) for cross-platform use.

**Comment by irahopkinson** [comment]
Updated [Debugging Your Extension in the Production Application](https://github.com/paranext/paranext-extension-template/wiki/Debugging-Your-Extension-in-the-Production-Application) extension Wiki page to note that `--extensions` switch paths can be absolute or relative. In prodcution or dev the CWD is always relative to the run location.
