### ISSUE TITLE
Load and run extension file (hello world)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#30]
Load up extension file in the extension host and let it run papi stuff

Ideas:
- Need file service
- In debug mode, watch unzipped extension files and reload as appropriate
- Webpack/babel

**Comment by tjcouch-sil** [comment]
Extension requirements:
- Not "type": "module"

**Comment by tjcouch-sil** [comment]
Future possibilities for shimming require:
https://github.com/elastic/require-in-the-middle
https://levelup.gitconnected.com/how-to-add-hooks-to-node-js-require-function-dee7acd12698
https://github.com/danez/pirates

**Comment by irahopkinson** [comment]
Pretty sure `electron` has already shimmed `require` so remember to take that into account.

**Comment by tjcouch-sil** [comment]
Can't figure out how to catch iframe exceptions. Very strange because somehow Electron is showing an exception screen on these exceptions, so _something_ is catching these exceptions. I dunno what layer of ERB or what does that.

Minimal iFrame error catching test that demonstrates the issue:
[iframe-error-test.zip](https://github.com/paranext/paranext-core/files/10816376/iframe-error-test.zip)

Some related stuff:
https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome
https://stackoverflow.com/questions/16194398/inject-a-javascript-function-into-an-iframe

**Comment by tjcouch-sil** [comment]
https://github.com/paranext/paranext-core/tree/30-load-extensions
Waiting for https://github.com/paranext/paranext-core/pull/29 and https://github.com/paranext/paranext-core/pull/43
