### ISSUE TITLE
Add unsubscribers to activate context object

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#304]
We want to make extensions in a way that allows future improvements without massive breaking changes if possible.

We should add some kind of unsubscribers member onto `ExecutionActivationContext` that is an array of (promises of) unsubscribers or an array of (promises of) objects that have dispose or something along these lines (or maybe we should add one of each since we have each of those, or just stick with one that can accept either and reflect on the object to determine which of these two it is). Similar to VSCode's [`ExtensionContext.subscriptions`](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext) (example in their [hello world sample extension](https://github.com/microsoft/vscode-extension-samples/blob/main/helloworld-sample/src/extension.ts#L22)).

This new stuff on `ExecutionActivationContext` replaces the return from the extension `activate` function. Now the extension `activate` function just returns `Promise<void>` (no return but it's an async function).

This is to avoid a breaking change with #54 whenever we get to it.

**Comment by irahopkinson** [comment]
Do you need corresponding follow-up PRs in the template and sneeze-board repos?

**Comment by tjcouch-sil** [comment]
I've just been updating the template and letting others update the others lately 😬 but either way. Probably best to make a post in Discord with update instructions if you break something and don't update in other places.
