### ISSUE TITLE
Support loading zipped extensions instead of just directories

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#316]
As an extension developer, I want to distribute my extension as a zip file that others can use easily.

We should add a way to read extensions from zip files instead of just from directories.

Also, because we decided in #69 that we should likely share types by having people point to the Paranext extensions directory in their `tsconfig.json` `typeRoots`, we should probably figure out some way to programmatically get the types files out of the zips and put them in some folder (maybe a `types` folder in or near the extensions folder in `%appdata%` or something?). Particularly once we get done with #299 

Probably also put a `types` field in the manifest so Paranext knows what your declarations file is

**Comment by irahopkinson** [comment]
Consider using [7zip](https://www.7-zip.org/download.html) console version which is cross platform and works with unicode filenames (since Windows zip doesn't).

**Comment by tjcouch-sil** [comment]
@irahopkinson do you know of any benefits and drawback of using external software like 7zip vs using npm libraries? [This article](https://blog.logrocket.com/best-methods-unzipping-files-node-js/) has many options to choose from and a [comparison table](https://blog.logrocket.com/best-methods-unzipping-files-node-js/#:~:text=Here%E2%80%99s%C2%A0a%20table%20comparing%20the%20unzipping%20packages) :)

**Comment by irahopkinson** [comment]
Good point. Thanks for that link. We should definitely use an npm package if we can. My real point is that we should make sure it handles all non-English characters. A zip file with non-English filenames in it are not always unzipped by Windows properly last time I checked (which was a while ago).

**Comment by tjcouch-sil** [comment]
Agreed. I think the one thing I'd mention there is that it would be good to have both reading and unzipping to file system so we can support pulling out the type declaration files for people to use when developing extensions :)

**Comment by lyonsil** [comment]
@FoolRunning Unfortunately it looks like I'm going to actually unzip the files to a real directory.  We need to have the node.js loader actually load the code, and it's going to be tricky to build and maintain a stable custom module loader to read in arbitrary blobs from memory instead of somewhere on the file system.

**Comment by lyonsil** [comment]
@irahopkinson I'm planning to use [JSZip](https://www.npmjs.com/package/jszip) for handling unzipping.  [It looks like](https://stuk.github.io/jszip/documentation/limitations.html) JSZip does everything in UTF-8.  If you know of a reason that UTF-8 is insufficient on its own please let me know.

**Comment by irahopkinson** [comment]
@lyonsil utf-8 is fine AFAIK. The only additional consideration is for normalization of filenames - we'd want both ends using say NFC.
