### ISSUE TITLE
Create generated documentation of our api

### ISSUE THREAD

**Issue by darren8c** [paranext/paranext-core#32]
As an extension developer, I want to be able to go somewhere not in the code to find all the features of the API so I can easily navigate around and get a detailed view of what I can do.

We need to find a way to generate an external document describing PAPI and possibly hook it up to our CICD process.

Looks like TypeDoc does what we want:
https://github.com/TypeStrong/typedoc
Examples:
- https://typedoc.org/example/
- https://ticlo.github.io/rc-dock/

[There are others](https://www.reddit.com/r/typescript/comments/vy1ew0/recommend_a_ts_documentation_generator/) in case we want to try multiple.

**Comment by tjcouch-sil** [comment]
@darren8c Fixed when we created `papi-dts`?

**Comment by tjcouch-sil** [comment]
Implemented with `papi.d.ts` in #161

**Comment by irahopkinson** [comment]
@tjcouch-sil are you saying that a `.d.ts` file is sufficient documentation for our API?

**Comment by tjcouch-sil** [comment]
Generating docs from the typescript types are in this issue.

Generating an interactive api is in #444
