### ISSUE TITLE
Design localization

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#331]
As a user, I want to be able to use Paranext in my preferred language.

Ian mentioned an idea to me in Discord:
> There's a feature request right there too: In settings, list the UI languages you read in the order you prefer. We'll show UI in the preferred language where possible, and fall back to other languages you've listed. So, plugins that aren't localized in Telegu may appear in Spanish before we fall back to English if you say that your preference is Telegu > Spanish > Huttese

**Comment by lyonsil** [comment]
Integrate a language picker into the settings UI
