### ISSUE TITLE
Move non-UI implementations of plugin interfaces from ParatextBase into ParatextData

### ISSUE THREAD

**Issue by tombogle** [paranext/paranext-core#332]
This is needed to support extensions (e.g., [Transcelerator](https://github.com/sillsdev/transcelerator/)) that rely on .Net libraries that depend on things implemented in Paratext's .Net libraries.
Note: Eventually, it may be that most/all of these things will also be exposed directly through PAPI in some form, but even then in some cases some of the implementation code would still need to be moved.

**Comment by jwickberg** [comment]
From looking at the first commit on this, I'm wondering if you should check with Tom Hindle about what can be used in the ParatextData nuget package projects and still be used by ParatextLite. I know that we were avoiding use of some .Net libraries and I think the change related to moving some Color references would violate this.

**Comment by FoolRunning** [comment]
This is being reviewed by the Paratext team. Waiting on them for approval.
