### ISSUE TITLE
Security: Should we print stack traces?

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#337]
As a user, I want secure software but software that developers can debug.

Stack traces are often helpful for debugging! However, they also reveal architectural information that a hacker could use to get into our system. Since almost all of our code is open source, I am not sure this is an issue, but it's possible it is. I'm not clear on that point. However, I know that some consider it unwise to print stack traces to logs. Should we print stack traces or avoid it?

**Comment by FoolRunning** [comment]
Since our software is open source, I think it would be silly to not print them since it would greatly help in our own debugging.

**Comment by tjcouch-sil** [comment]
TJ and Matt agree with Tim that the benefits outweigh the drawbacks. Most of the code is open, so it doesn't really matter.
