### ISSUE TITLE
Research: How to share extension UI

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#339]
As an extension developer, I want to be able to embed other extensions' UI into my extension UI to make UI more shareable and composable.

We need to research what would be a good way to allow people to share extension UI and come to a design. Some ideas:

1. Embed webviews in other webviews
  - We would need to provide a special component that reaches out and gets webview stuff from a provider and keeps up the id, state, etc on its own. Maybe somehow pass a ref through that people can use for interacting.
  - Extensions wouldn't have to further componentize their stuff; they just have working webviews, and you can display them. Pros and cons
  - Would we make these embedded webviews have their own menu?
  - Doesn't require the dependent code to be bundled into the using webview
2. Extensions can somehow publish and share components with other extensions through papi
  - Actually sharing React components. Maybe can import and use them just like any other component depending on how we implement
  - Doesn't require the dependent code to be bundled into the using webview
3. Extensions publish npm packages, and other extensions can use those packages
  - Actually sharing React components. Definitely import and use just like any other component
  - Dependent code is bundled into the webview itself

If the dependent code is bundled into the webview, there are some advantages and disadvantages:
- Pros:
  - Your UI will always work how you bundle it whether someone else's extension is present/updated/etc
- Cons:
  - Transmitting repetitive react code across the papi each time something shares that code
  - Your code shared from another extension won't update when that extension updates; not controlled by that extension. You will have to release an update to your extension with the latest code from that extension

**Comment by tjcouch-sil** [comment]
Monkey-patching browser import related work: #339, #321, #105

**Comment by lyonsil** [comment]
Answer: publish npm packages
