### ISSUE TITLE
Request to add attribute 'Id' on Papi-components

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#350]
Right now the 'Id' is generated in some instances and it varies every time component is rendered. Having 'Id' on a component helps us to uniquely identify in automation

**Comment by jolierabideau** [comment]
Documentation updated here [PAPI components](https://github.com/paranext/paranext-extension-template/wiki/PAPI#components)

**Comment by roopa0222** [comment]
The newly built P.B custom components do not have 'id' attribute. Please add 'Id' attribute for accessibility in testing.

ChapterRangeSelector
BookChapterControl
DataTable
ScriptureResultsViewer
CharacterInventory
HamburgerMenuButton
MarkdownRenderer
SearchBar
ContextMenu
DisableButton
EnableButton
FilterButton
FilterDropdown
InstallButton
UpdateButton

**Comment by roopa0222** [comment]
My original issue was addressed, and I will create a new one for new P.B components
