### ISSUE TITLE
Need to add 'value' attribute to Slider component

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#351]
I was getting below error while trying to update the value on loading. 'value' attribute will help resolve the issue. 
MUI: A component is changing the default value state of an uncontrolled Slider after being initialized. To suppress this warning opt to use a controlled Slider.

**Comment by jolierabideau** [comment]
@roopa0222 Would you be able to attach some code so that I can replicate this issue?

**Comment by roopa0222** [comment]
In my scenario I had to preload the page with a given value for slider. I have included the pieces of code.

  const [slider, setSlider] = useState(0);

//After getting data from dataprovider I updated the state using useEffect
useEffect(() => {
    //update the state with values from data provider
    if (!isLoading) {
	//for now just assigining value
        const tempSlider = 5;
		setSlider(tempSlider);
    }
  }, [isLoading]);
  
  
   const handleSliderChange = (event: Event, newValue: number | number[], activeThumb: number) => {
   // console.log('In handleSliderChange ');
    setSlider(newValue as number);
    
  };
  
  //This will always shows slider at '0' instead of '5'
    <Slider
              className="papi-slider.paratext"
              max={30}
              step={5}
             valueLabelDisplay="auto"
              onChange={handleSliderChange}
            />
			
			//-- if I try and assign the state to defaultValue as 'slider' it throws error since value is not available
			        <Slider
              className="papi-slider.paratext"
              max={30}
              step={5}
              defaultValue={slider}
              valueLabelDisplay="auto"
              onChange={handleSliderChange}
            />

**Comment by jolierabideau** [comment]
![Screenshot 2023-08-10 at 12 59 03 PM](https://github.com/paranext/paranext-core/assets/135999578/a22a32c5-8a9f-4712-b336-3ef55f575818)

**Comment by jolierabideau** [comment]
Documentation updated here [PAPI components- slider](https://github.com/paranext/paranext-extension-template/wiki/PAPI#slider)
