### ISSUE TITLE
Projects: Get project data provider by project ID

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#358]
As an extension developer, I want to interact with project data providers to edit projects.

Add an interface to the papi (`papi.projects.get` or something?) to specify a project ID and get a PDP from the appropriate PDPF. In Node, gets a PDPE from a PDPF, and layers over it with a PDP.

Note: In phase 2, papi will pass a PSI to the PDPF for it to connect to the PDP it is creating. For now, ignore that requirement

Depends on #356

[Project Design Doc](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit)

**Comment by katherinejensen00** [comment]
Done as part of 356 and 357
