### ISSUE TITLE
Projects: Create stubbed Open Project dialog

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#359]
As a user, I want to be able to open a dialog that lists projects and allows me to open one.
As an extension developer, I want to be able to show the user a dialog with a list of projects and get their selection.

Create an Open Project dialog (built into Platform.Bible, not an extension) that lists projects (spoofed) and allows you to select one to open similar to the Paratext menu.

- Lists projects for user to choose to open them - only display project metadata for now
- This should probably be added to the application menu so people can open a project
- Expose on papi for extensions to call to get a project id from the user (maybe something like `papi.dialogs.getProject` or something?) #388
- The way web views connect to projects is not designed, so this issue just relates to making the dialog itself

Relates to #360

[Project Design Doc](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit)

**Comment by irahopkinson** [comment]
Are you sure that extensions need to invoke this **open project dialog**? I'm thinking that the Platform can open a project and extensions only have access to any existing open projects including what the currently active project is. What is the use case for an extension initiating the **open project dialog**?
