### ISSUE TITLE
Projects: C# - create PDPF to serve Scripture

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#362]
As an extension developer, I want to be able to get Scripture project data to display, edit, etc.

In C#, create the Scripture PDPF that the papi will call to get the PDPs to get Scripture data. The PDPF will register the PDPF network object with the papi. When the papi wants to get a PDP, it will request one from the PDPF and will include the relevant project ID and PSI (PSI not yet implemented, so don't worry about this part yet), and the PDPF will return a PDP to the papi.

More details on the exact messages and network object ID required should be available with #356 

[Project Design Doc](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit)

**Comment by lyonsil** [comment]
Done as part of #361
