### ISSUE TITLE
Projects: Support registering Project Storage Interpreter

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#367]
As a core developer, I need to be able to keep track of PSIs and what storage and project types they implement so I can pass the correct one to the PDPF for a specific project type.

Extensions need to be able to register PSIs on the papi. When the papi gets a new PDP from a PDPF for a project, the papi gives the appropriate PSI some kind of special persistent storage access privileges to the corresponding project folder to load and save from file system for when the PDP asks for data (see `addPersistentStorageToken` suggestion in [the PSI section](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit#heading=h.xro8dzo2o7d0)). Papi give the appropriate PSI info to the PDP created when PDPF creates a PDP.

Note that there are a couple of places where we put a TODO in the code for this issue. You can find them by searching for `https://github.com/paranext/paranext-core/issues/367`

Depends on #366

[Project Design Doc](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit)

**Comment by lyonsil** [comment]
It's worth calling out that "completing" this issue turned into eliminating PSIs altogether. I merged what they were doing into PDPs which already have a way to register/create.
