### ISSUE TITLE
Projects: create `useDataProviderMulti` hook

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#371]
As an extension developer, I want to be able to get data from a variable number of data providers at a time easily in React so I can easily make WebViews.

----

Create a hook `useDataProviderMulti` that retrieves specified data providers. Essentially, we want a hook that is the equivalent of a variable number of `useDataProvider` hooks. This way, you can interact with a variable number of data providers (since you can't have a variable number of hooks in React).

Function signature (ish - probably needs work. Maybe there's a way to associate individual indices within the array):
```typescript
function useDataProviderMulti<EachT extends IDataProvider<any>[]>(dataProviderSources: (string | EachT[number] | undefined)[]): (EachT[number] | undefined)[];
```

[Project Design Doc](https://docs.google.com/document/d/1K-lNUzzThDvDrNrnU2UXXHny30SgjhIxfkC-Xc1fk5o/edit)

**Comment by tjcouch-sil** [comment]
People will probably want to just throw in the project info associated with their webview that was passed in as a prop into the first argument in this hook, so let's do that.

**Comment by katherinejensen00** [comment]
TODO: SPLIT THIS CASE!!!

**Comment by tjcouch-sil** [comment]
#532 split off for making `useProjectDataProviderMulti`
