### ISSUE TITLE
On MenuItem component when used as standalone component, command attribute is not helpful

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#394]
When I tried to use MenuItem as standalone component, the command attribute is mandatory. I used it with command but it does not cause any effect. 

 <MenuItem
          id="testPapiMenuItem1Id"
          className="menu-item"
          isDense={true}
          hasDivider
          name="TestMenu"
          command="paratextExtensionTest.testingComponents"
          onClick={() => console.log('TestMenu clicked')}
        ></MenuItem>

**Comment by roopa0222** [comment]
Also wondering if children attribute has any effect in MenuItem .

**Comment by jolierabideau** [comment]
@roopa0222 Since this component was re-worked to make it beneficial for the toolbar, it is set up to put name into the child spot, so adding children doesn't have any effect because it gets replaced. I can fix this when I fix command/name to make `MenuItem` easier to be used by itself.
