### ISSUE TITLE
Create Stub for Extension Toggle

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#398]
Create the extension toggle shown in the design below, but there is no need to hook it up yet.

Here is a link to the Figma design for the [extension toggle](https://www.figma.com/file/GKofaroTFCjBbfnBHzjbm9/Paranext-Extensions?type=design&node-id=430-774&mode=design&t=DoBC6ggziH2c4bus-0 )

Mike recommended using a Card for each extension instead of just a frame.

**Comment by mikelothers** [comment]
A link to a mockup that shows toggling extensions on/off is [here](https://www.figma.com/proto/GKofaroTFCjBbfnBHzjbm9/Paranext-Extensions?page-id=430%3A774&type=design&node-id=432-4394&viewport=2015%2C713%2C0.57&t=thZfDIsQgbJwwGlw-1&scaling=min-zoom&starting-point-node-id=432%3A4394). (A limitation of the mockup is that it only allows toggling one extension off at a time.)

**Comment by irahopkinson** [comment]
FWIW you can only disable one extension at a time in VS Code and it's 2 clicks (not 1 like here).
