### ISSUE TITLE
Create some basic components (MUI)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#40]
- [x] Get [MUI](https://mui.com/)
- [ ] Create a few basic components that wrap MUI components and use our own props (the MUI component props and such should not be exposed to the papi. It should be an implementation detail
  - [x] Button
  - [x] Input field
  - [x] Switch (on/off)
  - [x] Dropdown select (can't tell if there is one in mui. Maybe get from here if not https://react-select.com/home )
  - [x] Slider
  - [ ] Others you think will be useful

Depends on #39

**Comment by irahopkinson** [comment]
Do we want to think about our components being headless? It's more work initally but makes them more reusable and sharable (such as adding them to the [OCE](https://opencomponents.io/)). This would also keep us independent of MUI ina way that would make it mush easier to change to something else.

Some resources to help think about this:

- [Headless components in React and why I stopped using a UI library for our design system](https://medium.com/@nirbenyair/headless-components-in-react-and-why-i-stopped-using-ui-libraries-a8208197c268)
- An [example of a headless components lib](https://www.downshift-js.com/use-combobox/#materialui) that could be used as a base for an MUI component lib
- [Awesome React Headless Components](https://github.com/jxom/awesome-react-headless-components)
- https://www.downshift-js.com/
- https://www.radix-ui.com/
- https://headlessui.com/
- https://mui.com/base/getting-started/overview/

**Comment by tjcouch-sil** [comment]
@irahopkinson That's a great thought. I Considered Radix for a while. Would be good to discuss further. That was a helpful article to read about the situation! Let's discuss soon :)

**Comment by irahopkinson** [comment]
Decision: we think it's too early to go with headless.
Mui Base is headless but there aren't enough components yet (on Mui v5 at the moment). Mui v6 will be based on Mui Base and when we move to v6 we could re-elvauate the use of headless. Just going with Mui for now also keeps things much simpler as we start up.

**Comment by rolfheij-sil** [comment]
The work for #40 is combined with the work for #39, and both are combined in a single pull request:
https://github.com/paranext/paranext-core/pull/96
