### ISSUE TITLE
Run Basic Checks stub

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#401]
As a user, I want to ensure that the translation is accurate, so that there are no errors, especially easy to catch errors, when we go to print the text.

Create a view for Basic Checks based on a dynamic list but don't hook it up yet. Here is a picture of Run Basic Checks in Paratext to get an idea of what the view should look like.
![image](https://github.com/paranext/paranext-core/assets/25189167/382686d5-efb7-49d8-b7b6-6133eb21cc1f)

**Comment by tombogle** [comment]
![Image](https://github.com/paranext/paranext-core/assets/4229598/16264e62-2633-4480-8533-4747d4cd6651)

This shows the list of checks from Paratext 9.4

**Comment by Sebastian-ubs** [comment]
created UX story: https://github.com/paranext/ux/issues/4
