### ISSUE TITLE
Set up `npm` workspaces

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#410]
As a core developer, I want a simple way to simplify our build process to make it run more smoothly for easier development.

Please make sure to document the changes that will happen and what everyone needs to change in their processes.

Refer to:

- https://earthly.dev/blog/setup-typescript-monorepo/
- https://docs.npmjs.com/cli/v7/using-npm/workspaces

**Comment by Sebastian-ubs** [comment]
@tjcouch-sil is this done?

**Comment by tjcouch-sil** [comment]
I think so! I didn't put much detail in here, but it looks at least on the surface as if we have done this. We implemented npm workspaces a long time ago. Thanks for noting!
