### ISSUE TITLE
Create a packaged release after every merge into main

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#412]
As a product owner, I would like to be able to have a recent build so that I can demo the latest changes to platform.bible.

Glenn asked for us to release the project after each update into main (or at least that's what we think he's asking for).  We can do this manually, but we should setup the github jobs to do it automatically.

**Comment by irahopkinson** [comment]
**Recommendation:** I would leave the existing `.github\workflows\publish.yml` manual release as is for offical releases that get properly archived as GitHub Releases and add another mechanism running off merges to the **main** branch. These would exist only as GitHub Action artifacts for a limited time (and not in GitHub Releases).

**Comment by katherinejensen00** [comment]
No need to preserve artefacts.
