### ISSUE TITLE
Menus and Settings: Write service/module that combines a set of provided JSON documents

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#419]
As a Platform.Bible extension developer, I want to be able to add menus to my webviews and contribute to extensible points in platform-provided menus.

---

Depends on #418.

This ticket is the heart of the menu contribution design for extensions.  This is the component that combines the starting menu JSON document along with all the contributed JSON documents from extensions to make a final, valid JSON document that other modules/services/components can use to draw and work with the menus.

Details about what the starting JSON document, contribution JSON documents, and final JSON documents should look like, see the [menu contribution design document](https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?usp=drive_link).

It is important for this particular task to include enough unit tests to validate many positive and negative contribution examples.  It seems like that the JSON document schema will change over time as new capabilities are added, and we need a solid foundation that we have confidence continues to work properly as we make changes.

UPDATE: [The settings design](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit?usp=sharing) is taking a similar approach of JSON document contributions from extensions that combine into a final document.  So this implementation should have more than just menus in mind.  It should build the service in a way that identical logic can be applied to the settings use case, too.  This could be done through OO inheritance, though if there are other ideas that work better it doesn't have to be done as inheritance.

The service should receive javascript objects and return a javascript object.

The constraints to check for are embedded within the design documents. Please see them to know what problems to fail. This is NOT validating on JSON schema; it is only for validating the higher-level constraints on the data like failing if there are two groups at the same order.

**Comment by tjcouch-sil** [comment]
Some good thoughts from Matt about how a json interpreter and merger could be written:
> If this was something I was writing in C# I'd probably have an abstract base class that establishes a general workflow and API that they all conform to.  Then I would subclass it for each type (e.g., menus, settings, etc.).
> 
> The C# base class would do thing like:
> - Own the map of contributor documents
> - Own rebuilding the final version when something updates
> - Expose abstract functions for specific points in the process (e.g., pre-merge validation of each document, post-merge validation after each document, etc.)
> - If there was any special threading/async stuff, get it in all the right points so implementers don't have to think about it.
> 
> From a validation standpoint, I think these are all distinct:
> - Is the contribution from this source valid by itself?
> - After merging this contribution into the document, is the final version valid?
> - If a contribution fails, what action should be taken?  Throw out the whole document, perform some transform on the contribution, etc.
> 
> Oh, another similarity could be doing the localization replacements at the end.
