### ISSUE TITLE
Menus: Update multi-column menu component to render menu based on JSON document as specified

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#424]
As a Platform.Bible extension developer, I want to be able to add menus to my webviews and contribute to extensible points in platform-provided menus.

----

This particular task is about having menu components that take a "final" menu JSON document for a multi-column menu and display the menus appropriately.  The menu JSON document definition is in the [menu contribution design document](https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?usp=drive_link).

I'm told the existing mutli-column menu component already does something like this.  It is important for the component to align with the schema from the design document, so some updates are likely needed.

Note that the items in a menu should be considered fixed while the menu is open/drawn on the screen.  Once the menu is closed/hidden, its content should be reloaded before rendering again because extensions might have been enabled/disabled or something else might have changed that would modify the list of available menu items.

**Comment by tjcouch-sil** [comment]
You could probably quickly use a JSON-Schema-to-TS-types library to generate TS types for this from the JSON schema in the design quickly just this once :)

**Comment by tombogle** [comment]
Small follow-on PR: https://github.com/paranext/paranext-core/pull/786

**Comment by tombogle** [comment]
Another little PR  to fix an issue in the (for now) hard-coded menu data: https://github.com/paranext/paranext-core/pull/787
