### ISSUE TITLE
Menus: Stitch together back end services and UI components to get menu contributions working end-to-end

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#425]
As a Platform.Bible extension developer, I want to be able to add menus to my webviews and contribute to extensible points in platform-provided menus.

----

Depends on #418, #419, #420, #421, #424, #707, #722 

Once we have code in place that reads in menu contribution JSON documents, transforms those into "final" JSON documents on a per web app and overall application basis, and renders those JSON documents in the UI as "proper" menus, we need to stitch all these things together so they provide an end-to-end benefit to developers and users.

The [menu contribution design document](https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?usp=drive_link) has more details.

Additional note from TJ:
> We might have to do a bit of rework in the extension service as I think it only actually does much of anything with extensions that contain a main file right now. We need to make sure extensions that don't have a main file still get their menus added.

Additional note from Tom (with help from Matt):
create parallel types to MultiColumnMenu and SingleColumnMenu (that should be used in the React components and MultiColumnMenuProvider) that do not expect the ReferencedItem keys, but rather plain strings. This will make it possible to remove some type casts.

**Comment by roopa0222** [comment]
Testing Steps:
In my test extension.
1. I updated the menus.json to include a pointer for the P.B main menu to include under projects.
manus.json
```
{
  "mainMenu": {
    "columns": {},
    "groups": {},
    "items": [
      {
        "label": "%mainMenu_openPAPIMenuTestScreen%",
        "localizeNotes": "Application main menu > Project > Open PAPI Menu TestScreen",
        "group": "platform.projectResources",
        "order": -1000,
        "command": "paratextExtensionTest.openPAPIMenuTestScreen"
      }
    ]
  },
  "defaultWebViewTopMenu": {
    "columns": {},
    "groups": {},
    "items": []
  },
  "defaultWebViewContextMenu": {
    "groups": {},
    "items": []
  },
  "webViewMenus": {}
}

```
2. Updated the localizedStrings.json to have localisation 
```
{
  "metadata": {},
  "localizedStrings": {
    "en": {
      "%mainMenu_openPAPIMenuTestScreen%": "Open PAPI Menu TestScreen"
    }
  }
}
```
3. Updated the type file to include the command that is triggered on menu click on 'Open PAPI Menu TestScreen'
```
 export interface CommandHandlers {
    'paratextExtensionTest.testingComponents': () => Promise<string>;
    'paratextExtensionTest.randomNumGen': (num: number) => number;
    'paratextExtensionTest.openPAPIMenuTestScreen': () => void;
  }

```
5.Updated main.ts to register the command and to open 'PAPI Menu Test' web-view on command.
```
const openPapiMenuWebView = async () => {
  logger.debug(`Entered here in the openPapiMenuWebView command`);
  papi.webViews.getWebView(papiMenuWebViewProvider.webViewType, undefined, { existingId: '?' });
};
const openPapiMenuWebViewPromise = papi.commands.registerCommand(
    'paratextExtensionTest.openPAPIMenuTestScreen',
    openPapiMenuWebView,
  );
```

**Comment by lyonsil** [comment]
Hi @roopa0222 - That looks like a good test of the menu functionality.
