### ISSUE TITLE
Platform.Bible Settings Dialog Stub

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#434]
As a User, I need to be able to customize my work environment so that I can work in the language I want among other things and synchronize the look of my environment with that of my teammates.

- [ ] Create a stub (visual only + interface to be ready for real data) for the Settings Dialog for Platform.Bible (not project settings) based on the one in Visual Studio Code and based on the early mockup from Allison (ask her about it when you are ready to begin work on this so you can get the latest version)
- [ ] It should take in both data and components and display them in a reasonably nice way (feel free to use mock data)
- [ ] Optional: Add a search bar (if there is time/it is easy)

Visual Studio Code Settings:

![Image](https://github.com/paranext/paranext-core/assets/25189167/6fcf9f1a-edb3-4eb8-866d-3675b0997415)

Current Paratext 9 Settings (for reference):

![Image](https://github.com/paranext/paranext-core/assets/25189167/f00e4e1f-e488-4e95-a04d-85684e0e4ada)

**Comment by Sebastian-ubs** [comment]
@katherinejensen00 we already have an early mockup for this. you could ask @allisonparkk

**Comment by tjcouch-sil** [comment]
[Settings data structure](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit#heading=h.fjg01wdfi36k) - shows what kind of data will be coming into the dialog (most importantly, note that there will be settings groups with settings inside them. No need to worry about the details)

[Settings Dialog Architectural Design](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit#heading=h.es9n3jrr4wlb) - hopefully provides some context for what this dialog does.
