### ISSUE TITLE
Basic List

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#435]
As a User, I need to be able to see the results of something like a search or check run so that I can easily find what I am looking for.

Create a basic list like the one in Paratext 9 that displays a view only list of results (can be mock data)

![image](https://github.com/paranext/paranext-core/assets/25189167/f7f67bfe-2d65-4b0d-9a1f-49933e73d31c)

**Comment by mikelothers** [comment]
Corresponding UX issue: https://github.com/orgs/paranext/projects/1/views/13?pane=issue&itemId=39423901
