### ISSUE TITLE
Watch extension directories and restart extensions when extensions are added

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#437]
As a user, I want to be able to add or remove extensions in the extensions folder and see the change reflected in Platform.Bible while it's running so I have a smooth experience playing with extensions.

We should improve the [`watchForExtensionChanges` function](https://github.com/paranext/paranext-core/blob/main/src/extension-host/services/extension.service.ts#L282) to restart extensions when a new folder or extension zip gets added to the extension directories.

Glenn would like to see this if it is possible to do by tech demo.

**Comment by katherinejensen00** [comment]
This is timeboxed to a medium.
