### ISSUE TITLE
Can't access data provider from another extension if your extension starts first

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#439]
As an extension developer, I want to be able to access data providers from extensions I want to use without having weird timing issues that have nothing to do with my code or the other extension's code.

----

When Roopa wrote an extension ("Extension B") that uses a data provider registered by another extension ("Extension A"), she couldn't `get` the data provider in Extension B because it was activating before Extension A. We have lots of code that tries to mitigate timing issues (so this dependency would probably work across processes, but this is on the same process), but something is not working right with an extension getting a data provider before another extension activates and registers that provider. She kept getting the following error:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Timeout reached when waiting for DataProvider-extensionTest.uidata to settle".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

When we wrapped the code getting the data provider in a 1-second `setTimeout`, the problem went away.

Seems there's a problem related to the `AsyncVariable`s in the data provider service. Maybe some variable gets cached in `get` but isn't properly used in `registerEngine` or something. Note that the timeout is on `DataProvider-extnesionTest.uidata`, which seems to be related to the `registerEngine`.

<details><summary>Code Samples</summary>
<p>

<details><summary>Types in `paranext-ext-testing.d.ts` (Extension A)</summary>
<p>

```typescript
declare module 'paranext-ext-testing' {
  type Ref = { bookNum: number; chapterNum: number; verseNum: number };

  type TestDataRow = {
    Id: string;
    FirstName: string;
    LastName: string;
    Zip: string;
  };

  export type UICompData = {
    TextValue: string;
    Slider: number;
    Switch: boolean;
    States: string[];
    Checkbox1: boolean;
    Checkbox2: boolean;
    Reference: Ref;
    TableData: TestDataRow[];
  };

  export type UICompDataTypes = {
    UIData: DataProviderDataType<string, UICompData, UICompData>;
  };

  export type UICompDataMethods = {
    sayHelloWithDataProvider(things: string): Promise<string>;
  };

  export type UICompDataProvider = IDataProvider<UICompDataTypes> & UICompDataMethods;
}
```

</p>
</details> 

<details><summary>Accessing the data provider in Extension B</summary>
<p>

```typescript
setTimeout(async () => {
    try {
      const dataProviderPromise1 =
        papi.dataProvider.get<UICompDataProvider>('extensionTest.uidata');
      const uiDataProvider1 = await dataProviderPromise1;
      logger.info('Extension Test UI Data provider : ' + uiDataProvider1);

      const greeting = await uiDataProvider1?.sayHelloWithDataProvider('Tester');
      logger.info(Method ${greeting});

      const data = await uiDataProvider1?.getUIData('*');
      if (data !== undefined) {
        logger.info(
          Values received from getUIData in Ext-Multiple-B  ${data.TextValue} States: ${data.States} Slider: ${data.Slider} Switch: ${data.Switch},
        );
      } else {
        logger.info('Did not get values in Ext-Multiple-B !!');
      }
    } catch (e) {
      logger.info('Failed to get UIDataProvider', e);
    }
  }, 1000);
```

</p>
</details> 

</p>
</details>

**Comment by lyonsil** [comment]
After some testing of my own, I can say it looks like this is a problem when you have Extension B open in VS Code and are debugging while loading Extension A via `--extensionDirs`.  However, if you are running the platform and have both Extension A and Extension B packaged and loaded using `--extensionDirs`, everything seems to work fine.
