### ISSUE TITLE
Populate "<home_dir>/.platform.bible" with plausible defaults in dev

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#440]
As a Platform.Bible developer, I would like my dev environment to be initially populated with sensible data so that I can test/use PAPI without having to create settings and data files on my own first.

---

Right now we aren't populating the .platform.bible directory with anything.  That means, for example, we don't have a way for users to try out ProjectDataProviders unless they figure out how to migrate an existing project and create a `meta.json` file with the right values on their own.

Make sure to fix the spots like https://github.com/paranext/paranext-core/blob/388-dialog-service/src/main/main.ts#L311 where testing is waiting for a project

**Comment by tjcouch-sil** [comment]
This issue comes from this conversation on Reviewable https://reviewable.io/reviews/paranext/paranext-core/427#-NedOX4p8AAqML4Sf3PJ
