### ISSUE TITLE
PAPI websocket client live interactive documentation page

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#444]
As an extension developer, I want to be able to open a page that shows all the features on the PAPI (commands, events, data providers, etc) and lets me interact with them by clicking buttons, entering data, etc.

----

We could make a websocket client page that shows the different commands/data and such and lets you hit a button to send those messages and get responses back. Like an [interactive swagger api page](https://petstore.swagger.io/).

**Comment by tjcouch-sil** [comment]
Matt found some interesting things along these lines:
 https://spec.open-rpc.org/
https://playground.open-rpc.org/
https://github.com/open-rpc/generator

**Comment by ryderwishart** [comment]
@tjcouch-sil what did you guys wind up doing here? Did you go with the OpenRPC spec?

**Comment by tjcouch-sil** [comment]
@ryderwishart We haven't concluded on a direction and have not worked this issue yet. Still TBD :)

**Comment by lyonsil** [comment]
Now that #1200 is done, this is probably much more achievable.

**Comment by tjcouch-sil** [comment]
Screenshot from the demo:

![Image](https://github.com/user-attachments/assets/db6bfd2e-ae3e-423d-bc1a-af3366c22ba1)

**Comment by Sebastian-ubs** [comment]
Great. Where is the documentation how to launch this?
