### ISSUE TITLE
Create Word List Extension

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#446]
As a user, I want to see a  nice list of words showing how often various words occur in my current context.  

For this first iteration, just show words in the current chapter of a project.  Future iterations will eventually work our way towards the functionality of the P9 Wordlist.

Counts based on current chapter for now.

Add a toggle with a word cloud view:

> [https://www.npmjs.com/package/react-wordcloud](https://www.google.com/url?q=https://www.npmjs.com/package/react-wordcloud&sa=D&source=docs&ust=1695674722062852&usg=AOvVaw2Z_ehJ4XETCeg44USQKl0o)
> [https://react-wordcloud.netlify.app/](https://www.google.com/url?q=https://react-wordcloud.netlify.app/&sa=D&source=docs&ust=1695674722062899&usg=AOvVaw3s3LcDYjH3PiTh9OpyK0fP)
> Resizeable demo [https://codesandbox.io/s/55sb8](https://www.google.com/url?q=https://codesandbox.io/s/55sb8&sa=D&source=docs&ust=1695674722062941&usg=AOvVaw0xTg3sFNHX_vwX184zIHxb)

(Heavily edited by Glenn - this really isn't TJ's comment anymore...)

**Comment by tjcouch-sil** [comment]
@GlennPruitt Should it show the frequency of words in your whole project? Just the currently-selected chapter? Whatever is easiest to implement with what we have (this one is my preference hehe)? Other?

**Comment by GlennPruitt** [comment]
What if it created a list of words instead of a cloud?  Start with displaying the currently selected chapter.  Then later it could be a configurable scope.  Sort the words from most used to least used, then alphabetically.  Instead of the Word Cloud we could call it the Word List...

**Comment by tjcouch-sil** [comment]
Whatever you'd like to do is fine! But a word cloud would honestly probably be just about as easy because of the library I linked in the description of this issue. Your call :) I can adjust the issue as instructed.

**Comment by FoolRunning** [comment]
FWIW, there is a demo Paratext plugin that creates a word cloud from the USFM text: https://github.com/ubsicap/paratext_demo_plugins/tree/master/ChapterWordle

**Comment by rolfheij-sil** [comment]
PR is [here](https://github.com/paranext/paranext-extension-word-list/pull/1)
