### ISSUE TITLE
Checks: Create Run Basic Checks dialog

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#447]
As a user, I want to find and run the checks I care about quickly so that I can efficiently see relevant information about what I need to fix about my text.

Design the structure for the run basic checks dialog (note there is a separate case for designing the anatomy of a check). 
One thing to consider is how to dynamically find and display checks

Assume we will recreate something similar to what was done in PT9 unless UX has a different design in place.

From PT9:

![Image](https://github.com/paranext/paranext-core/assets/128563279/ad62cc72-2dbe-4b63-b14f-b615aac8036b)

**Comment by Sebastian-ubs** [comment]
make basic checks a [dialog](https://www.notion.so/paratext/Dialog-2eee344581fa49e094afb0b1a43a0f04?pvs=4) with non scrolling footer buttons.

**Comment by Sebastian-ubs** [comment]
follow up of
- https://github.com/paranext/paranext-core/issues/401,
related to
- https://github.com/paranext/paranext-core/issues/402

**Comment by jolierabideau** [comment]
@roopa0222 

To be tested from an extension: 

- [ ]  New `Checklist` component in platform-bible-react
- [ ]  `ChapterRangeSelector`, no longer accepts startChapter and endChapter as props

**Comment by roopa0222** [comment]
1. Updated the  ChapterRangeSelector component in my test extension.
2. Used Checklist Component in my test extension. Tested all the component props and functions. Everything working as expected.

> In my UI 
> 
> ```
>   <Checklist
>           id="checkListTestId"
>           className="papi-checkbox"
>           legend="Country"
>           listItems={countryList}
>           selectedListItems={selectCountry}
>           createLabel={OnCreateLabel}
>           handleSelectListItem={OnHandleSelectListItem}
>         />
> ```
> 
> 
> 
> ![Image](https://github.com/paranext/paranext-core/assets/133702629/6e5a5c92-70df-4277-8377-8e0a43259d50)
> 
>
