### ISSUE TITLE
Open Resource Viewer to selected project

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#448]
As a user, I want to be able to select a downloaded project to open with the Resource Viewer so I can see things.

----

As a quick way to get this working for the tech demo, I propose the following course of action:
- [ ] Create a `resourceViewer.open` command in the Resource Viewer extension that does the following:
  1. Opens a Select Project dialog to choose which project to open. When the user selects a project, the project id will be returned to the command code
  2. Call `papi.webViews.getWebView` to get a new Resource Viewer webview. Provide the project id in the options object (extra properties will get carried along to the webview provider function). Return from the command.
  3. When the webview provider receives the request to create the webview, get the project id from the options object (passed from step 2). Set that as part of the webview state.
           - [ ] Set the title to include name of selected project
  4. Adjust the resource viewer webview so it uses the new webview state to get the project ID to show
- [ ] Create a baked-in menu item that calls the new `resourceViewer.open` command. This lets us avoid implementing the menu design by tech demo time.

Depends on #364, #388, #472

**Comment by tombogle** [comment]
This is now basically done, awaiting the implementation of ChapterUSX
