### ISSUE TITLE
Set up code to allow C# to provide checks to Platform.Bible

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#451]
As a user, I need access to Paratext checks so that I can continue to check my translation with the familiar and effective checks from Paratext.

Create a path/channel/pipeline to allow Platform.Bible to access Paratext Checks (and other C# checks).

**Comment by katherinejensen00** [comment]
This could involve C# unit tests

**Comment by lyonsil** [comment]
The list of C# checks being made available are:
- Capitalization
- ChapterVerse
- Character
- Marker
- MatchedPairs
- Numbers
- ParagraphFinalPunctuation
- Punctuation
- Quotation
- QuotationTypes
- QuotedText
- Reference
- RepeatedWord

From a testing perspective, it would be helpful to know if if we produce the same check results as PT9 for the same inputs. We don't need to worry about verifying that the checks are correct in all cases, just that we get the same results between PT9 and P.B.

**Comment by roopa0222** [comment]
I came across a few exceptions when testing the checks. I created issues #1075 , #1074
