### ISSUE TITLE
Create Chapter/Verse Numbers Check Configuration

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#453]
As a user, I need to know that I have included every chapter and verse in my translation so that I am confident we have translated and included everything we intended to.

Add a way to configure this check.

No inventories needed, but does use the following:
~~Versification~~ deferred

Investigate the role of the following in this check and determine if configuring them is relevant in Platform.Bible:
- Segment Order Setting ?? (technically there, but there for P7 migration)
- ExpectedChapterVerseEnumerator (currently hard-coded as a', 'b', 'c', 'd')

Depends on https://github.com/paranext/paranext-core/issues/449

**Comment by FoolRunning** [comment]
Just for clarification, this actually means make an adaptor (or something) that reuses the existing C# Chapter/Verse check, right? I'm hoping we don't want to recreate it.

**Comment by katherinejensen00** [comment]
Yes

**Comment by katherinejensen00** [comment]
@ianhewubs Do you know if Segment Order Setting is still used/helpful?

**Comment by ianhewubs** [comment]
> Do you know if Segment Order Setting is still used/helpful?

If it's just for PT7 migration, I don't know what it could be. That said, it sounds like it could relate to canon definition (some projects are interconfessional and can be printed for protestant, catholic or orthodox tradition readers). If it does relate to canon, it could be essential. In either case, I think a PT9 dev will be in a better place to answer this.

**Comment by katherinejensen00** [comment]
Sounds good, thanks, Ian!

**Comment by tjcouch-sil** [comment]
We deferred the configuring of versification til later, and we do not know of other configuration needed to be done to support this check. Closing.

**Comment by rolfheij-sil** [comment]
The check in PT10S that uses the PT9 code produces the same results as PT9

![image](https://github.com/user-attachments/assets/58d4805d-0b48-4d19-b032-3cee87f076c8)

![image](https://github.com/user-attachments/assets/7c0d6bbb-7830-470c-95e1-c2eed1056b43)

**Comment by roopa0222** [comment]
Got the latest code.

ACTION STEPS
1.    Navigate to PHP 1:30
2.    zzz2 tab menu icon > Tools > Configure Check..
3.    Tick only Chapter/Verse Numbers > "Current Book" > Philippians > OK
4.    CONFIRM the `Show Check Results..` list displays No errors.
---DELETE TEXT
5.    In PHP 1:30, delete all the text in PHP 1:30 after "\v 30"
6.    CONFIRM the `Show Check Results..` list displays only one item:
PHP 1:30 Empty verse

![Chapter-verse-numbers-check](https://github.com/user-attachments/assets/b85ebcfe-3ad6-40db-a1f6-a69976cf89b0)
