### ISSUE TITLE
Checks: Results List Navigation

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#454]
As a user, I would like to click on an error and navigate straight to the location of my error so that I can efficiently fix the problems in my text.

Create ability to click on a result and navigate to its location in the text. Double clicking on an item in the results list should highlight the specific marker, character, punctuation, number or verse that relates to the result.

We need to create a web view controller for the editor to interact with the editor ref to set the selection:

- [x] Convert editor web view provider to `WebViewFactory`
  - [x] Use `WebViewFactory` abstract class. Change `getWebView` to `getWebViewDefinition`
  - [x] Add web view controllers to the editor web view factory that have a `setSelection` method
    - [x] Set up the proper `WebViewControllers` shared interface property
- [x] Set up checks result list properly to send `setSelection` request
  - [x] Save web view id of the web view that opened this results list
  - [x] Get web view controller in results list and send `setSelection` request properly
- [x] Set up sending message from web view controller to editor
  - [x] Use `postMessageToWebView` to send a message to the web view to set the selection
  - [x] Add listener to web view to receive the message and set the selection

Note that these operations will require figuring out translating selection ranges properly

Depends on https://github.com/paranext/paranext-core/issues/881, #1185

**Comment by tombogle** [comment]
Following the meeting with @irahopkinson and @lyonsil, I have stubbed in some possible types for defining USJ-based selections such that checks could produce them and the editor could highlight them. Currently these are in src\components\scripture-ref-keyed-list.component.tsx, but they probably need to migrate to platform-bible-utils instead.
But see the discussion in the [Editor Selection Range Representation](https://docs.google.com/document/d/1V9zHvccdpRevR_7PTbhbf5oWPUG5wpHoW9qybgGqeRg/edit) document for some alternatives when the selection is not in normal text (e.g., when it applies to a verse number node).
