### ISSUE TITLE
Create Markers Check Configuration

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#456]
As a user, I need to check the accuracy of the markers in my translation so that I can have a quality error free publication of my translation.

Add configuration abilities for the Markers Check.

The C# version utilizes the following configuration things that (might; please investigate) need to be implemented:
- Markers Inventory
- Glossary Parser - likely irrelevant
- Stylesheet of the project (do not implement editing the sty file; just make sure the inventory supports listing the custom styles provided)
- Marker Combination setting (advanced setting user can opt in to to see combinations of paragraph markers -- see Show Preceding Marker checkbox on Inventory form in P9)

Depends on https://github.com/paranext/paranext-core/issues/449

**Comment by roopa0222** [comment]
Verified the Markers Inventory functionality with the PT95 

Repo Steps 

1. `Open Scripture Editor > zzz6 > Inventory: Markers..` on PB
2. Confirm that `Markers Inventory: zzz6 ` is opened
3. Set the BCV to `PHM 1:1 `
4. Notice that both PT95 and PT10 produce the same number of results.
5. In PT10 sorting on column `Style Name` is missing
6. In PT10 the Style Name for `x...x* - Cross Reference` whereas in PT95 it is `End Marker`
7. Similarly `f...f* - Footnote` in PT95 is`End Marker`

Note from Rolf: PT10 produces more results compared to the PT95 when the `Show Preceding Marker` option is selected 

PT10

![PT10_MarkersInv](https://github.com/user-attachments/assets/96a41850-d3e3-4a63-9877-410550b5f497)

PT95

![PT95_MarkersInv](https://github.com/user-attachments/assets/317bbfbc-78a2-4305-b8b1-4d459ebd52e7)

**Comment by katherinejensen00** [comment]
Alex: Does not offer a way to see which markers are in the USFM spec but not used or allowed
