### ISSUE TITLE
Create Characters Check

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#457]
As a user, I need to check the accuracy and consistency of the usage of characters in the translation so that I can have a quality error free publication of the translation.

Create Characters Check using P9 Characters Check logic.
Note: This check can be done with or without combinations so make sure to account for that when creating this check. Will those need to be separate checks or one check with a setting? 

Note: This is version 1 and will not support decomposed characters.

The Characters Check uses the Characters Inventory and the Medial Punctuation Setting

Depends on https://github.com/paranext/paranext-core/issues/449

**Comment by lyonsil** [comment]
@rolfheij already did this

**Comment by roopa0222** [comment]
This is verified as part of Character Inventory dialog.

https://github.com/paranext/paranext-core/issues/1072 is created to address some of the issue with Character Inventory/ Checks
