### ISSUE TITLE
Create Repeated Words Check and Inventory

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#463]
As a user, I need to make sure there are no repeated words that shouldn't be repeated in my translation so that I can have a quality error free publication of my translation.

- [x] Implement repeated words inventory
- [ ] Create Repeated Words Check using P9 Repeated Words Check logic.

The C# Repeated Words check uses information from the following:
Repeated Words Inventory
Tools > Checking inventories > Repeated words

Depends on https://github.com/paranext/paranext-core/issues/449

**Comment by roopa0222** [comment]
Test Repo Steps

On the PB got the latest code from main.
1. Open Scripture editor from the PB hamburger menu
2. Select project zzz6 on the Scripture editor dialog
3. Select Exodus 21 on the BCV
4. On the zzz6 webview menu select 'Inventory: Repeated words'
5. Repeated words dialog appears with the list.

The PB did not display any results while PT95 has 2 repeated words.

![PB_Repeated_Ex21](https://github.com/user-attachments/assets/d9384c56-c0ae-43a3-8bb2-875dd2765b53)


![PT95_Repeated_Ex21](https://github.com/user-attachments/assets/8090fa6e-5443-420e-9e67-16cd9550e41d)

**Comment by rolfheij-sil** [comment]
I've updated the logic that extract the repeated words. It detects some false positives now, but that's better than finding nothing.
I've also updated the example in the `platform-bible-react` preview

[PR is here](https://github.com/paranext/paranext-core/pull/1095)

**Comment by roopa0222** [comment]
Test Repo steps to verify the fix. 

1. Open Scripture editor from the PB hamburger menu
2. Select project zzz6 on the Scripture editor dialog
3. Select Exodus 21 on the BCV
4. On the zzz6 webview menu select 'Inventory: Repeated words'
5. Repeated words dialog appears with the list.
6. Change the status on the 'dat' from 'Unknown' to 'Approve'
7. The value 'dat' is added in the Settings.XML at C:\My Paratext 9 Projects\zzz6 folder.

` Settings.xml
  <RepeatableWords>wen dea dat</RepeatableWords>
`

PB Repeated words Inventory is producing same results as PT95

![PB_Corrected_Ex21](https://github.com/user-attachments/assets/95d6be93-ca8d-4dbe-8368-cda6e364ce35)

![PT95_Corrected_Ex21](https://github.com/user-attachments/assets/c4209c0c-47bc-4182-bc24-452f94e21b17)
