### ISSUE TITLE
Fix storybook production build?

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#47]
~~Our production version of storybook (static page that shows the components and their abilities) isn't working. If we ever need to make it work (it may be a convenient way to document and demonstrate to extension developers what components they can use), we need to fix the production webpack configuration in [`.storybook/main.ts`](https://github.com/paranext/paranext-core/blob/39-storybook/.storybook/main.ts#L22).~~

The cost to fix the storybook publication build was too expensive so we decided to create a separate repo that would have all of the components and run storybook. This turned into a research task to understand what options are available for Figma and Storybook integration. Below is the link to the research results:

[Figma and Storybook Integration Research](https://docs.google.com/document/d/1X7UJ0tg5ownScYC-ruaesgDTEgnwdvKpsP-p39v9Tjw/edit#)

To test the production storybook, follow the steps here: https://storybook.js.org/docs/react/sharing/publish-storybook

Depends on #39

**Comment by katherinejensen00** [comment]
This turned from a programming task to a research task. There are some sample projects linked in the research document:
[Figma and Storybook Integration Research](https://docs.google.com/document/d/1X7UJ0tg5ownScYC-ruaesgDTEgnwdvKpsP-p39v9Tjw/edit#)
