### ISSUE TITLE
WebViews: Implement simple WebView state

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#472]
As a user, I want my tabs to stay the same between refreshes and restarts so I can pick up where I left off anytime.

As an extension developer, I want the platform to keep track of a set of data that describes the state of each of my webviews so I can keep the webview the same between sessions and such. I want to be able to set this data when the platform asks for a new webview so I can pull up the webview in whatever state is appropriate for the situation.

As a user, I want to open the Resource Viewer (or other relevant tabs) to a specific project so I can see Scripture as I choose.

----

We should implement a simple intro webview state to get us going with webview state (so we can give the selected project ID to webviews in the tech demo most importantly):
- [ ] web view service keeps track of state (literally just an object) for each webview
- [ ] web view service sends the webview state to the webview provider (as part of the saved web view definition?) when it is getting the contents of the web view
- [ ] web view provider can edit the state as desired and returns the state (as part of the web view definition?)
- [ ] web view service has some more code in the html wrapper that defines get/set functions to interact with this web view state. In the React wrapper, maybe we provide a hook to use these in a `useState`-like interface or pass the state and an updater function as props.
- [ ] When the webview state is set, the web view service needs to persist it somehow (localstorage is probably fine for now)

We should also get some TypeScript types working as well. Don't necessarily need super tight great types. At least `Record<string, unknown>` or `Record<string, any>` would be good at first, though. Maybe we could do a mapped type for the options and state.

[Settings & State Design Doc](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit)

**Comment by katherinejensen00** [comment]
Needs to persist when app closes and reopens
