### ISSUE TITLE
Create TypeScript model for Notes Data API

### ISSUE THREAD

**Issue by GlennPruitt** [paranext/paranext-core#479]
As a funder I want to have a description of all APIs in the BT space. Specifically, I want a model of the API for Project Notes Data that will be exposed by Platform.Bible to extension developers. This model must be written in an easy-to-read format (previously GraphQL).

Only needs to be done for publicly available APIs (aka ones that can be consumed by an extension)

Write documentation for the Project Notes Data API.

Talk to Michael Marshall for more details.

**Comment by tjcouch-sil** [comment]
Adapted from the following in Paratext 9's Plugin Interface Docs:
- [IProjectNote](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProjectNote#assigneduser) and related types

```graphql
# An object representing a project note
type ProjectNote {
  # A selection in the Scripture text representing the "anchor" location of the note.
  anchor: ScriptureTextSelection!
  # Present in a note when it has been assigned to a particular user.
  assignedUser: UserInfo
  # The comments that comprise the note
  comments: [Comment]!
  # Flag indicating whether all the comments of the note have been read by the current user.
  isRead: Boolean!
  # Flag indicating whether this note is resolved.
  isResolved: Boolean!
  # Present in a note when it has been assigned to reply-to a particular user.
  replyToUser: UserInfo
}

# A selection in the Scripture text
type ScriptureTextSelection {
  # The raw USFM text following the SelectedText (typically the remainder of the verse represented by VerseRefEnd).
  afterContext: String!
  # The raw USFM text preceding the SelectedText (typically the entirety of the verse represented by VerseRefStart up to Offset).
  beforeContext: String!
  # The character offset (in the raw USFM data) starting from the point before the \v (i.e., the slash is the 0th character).
  offset: Int!
  # The selected text represented by this object. Can be an empty string (representing an insertion point).
  selectedText: String!
  # The verse where the selection ends.
  verseRefEnd: VerseRef!
  # The verse where the selection starts.
  verseRefStart: VerseRef!
}

type UserInfo {
  
}

type Comment {
  
}

type VerseRef {
}
```

**Comment by tjcouch-sil** [comment]
Relied heavily on [IProject](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProject) and [IProjectNote](https://github.com/ubsicap/paratext_demo_plugins/wiki/IProjectNote) to create the types.

First draft: `ProjectNotesDataProviderExpanded`

**Comment by tjcouch-sil** [comment]
Some thoughts from Matt to discuss sometime with Tim, particularly regarding figuring out what all we can do to the api and still work with PT9:
> - Language really shouldn't have font and isRtoL, I think.  Rather Language should just be the ID/langauge tag, and there should be a dictionary somewhere else that maps those IDs to things including, but perhaps not limited to, fonts and right-to-left (or more generically text direction).
> - I would try to keep the data model totally separate from the presentation layer at least in terms of terminology.  For instance, I don't love that a paragraph has spans.  Paragraphs have sentences.  Or if we're trying to be less granular, paragraphs have snippets of text.  HTML has spans, not paragraphs.
> - When expressed outside of GraphQL, I'm hoping created is a DateTime or something that explicitly includes both a date component and a time component, not just a date in terms of the type name.
> - Having isRead and isResolved seems odd to be at the same scope.  I'm assuming isResolved applies to a scope that includes multiple/all users (e.g., stored for the project overall).  But isRead applies just at the scope of the current user per the definition.  It seems odd to mix those together in the same object like that.  Now if isRead is really about whether assignedUser read it or not, that's different and would apply at a project level.
> - Why does ProjectNote contain a Comment (which has an assigned user value itself) and an assignedUser field?
> - It's kind of surprising that comments or project notes don't have some kind of independent ID associated with them.  The replyToUser field is really strange to me.  If we're trying to have replies, the reply should be to some other ProjectNote or Comment, and then you'll need to reference what you are replying to.  Also, when would replyToUser ever be different than assignedUser?

**Comment by tjcouch-sil** [comment]
Follow-up changes:
`Language` can just be a code in `addNote`. Maybe everywhere. Add `LanguageTag` type and remove `Language`  type
`Date` - specify in comments or field that it is particularly about a time
`isRead` - convenience flag; could be moved somewhere else. Where?
`assignedUser` - comments: most recently assigned user(ish). Like "From"
`replyToUser` - comments: second to most recent assigned user(ish). Like "To"
Comment id is made of thread id and date - should probably add this to ProjectNote and Comment


Note: we can use `Fields` tag on notes to add information in the future as needed
