### ISSUE TITLE
Write wiki documentation for minimal extension template

### ISSUE THREAD

**Issue by rolfheij-sil** [paranext/paranext-core#485]
As an extension developer I want clear documentation that helps me to understand how to work with the minimal extension template so that I can start developing my own extension

Currently we have two extension templates for extension developers to use. The ['hello world' extension template](https://github.com/paranext/paranext-extension-template-hello-world), and the [minimal extension template](https://github.com/paranext/paranext-extension-template). The hello world one has proper documentation that explains users how to get started with it.
The minimal one has proper documentation that explains the anatomy of extensions, but it is still missing practical documentation that helps users to get started with it.

The documentation should contain:

- A description of what is contained within the minimal template repo, similar to the [documentation of the 'hello world' template](https://github.com/paranext/paranext-extension-template-hello-world/wiki/Your-First-Extension-%E2%80%90-An-Easy-Start)
- A step by step description of how to turn the minimal template into a fully functional one, like the 'hello world' template.

The documentation should be added to this [wiki page](https://github.com/paranext/paranext-extension-template/wiki/Your-First-Extension). It should replace the 'To do' section

**Comment by tombogle** [comment]
As part of this, we should also clarify what the "main" key is in the manifest.json (and probably document all the keys in both manifest.json and package.json).

**Comment by tjcouch-sil** [comment]
Here's the current JSDocs for the manifest file https://github.com/paranext/paranext-core/blob/main/src/extension-host/services/extension.service.ts#L40

**Comment by tjcouch-sil** [comment]
Looks great! Thanks for the hard work!

I made some smaller tweaks that you can see in the following diffs:
- https://github.com/paranext/paranext-extension-template/wiki/Extension-Anatomy/_compare/7a187a300156c50eb4d75dfb17eaaeccc9c99e61...30dd2daa50eddf227f76fd3d0066ff559463ce08
- https://github.com/paranext/paranext-extension-template/wiki/Your-First-Extension/_compare/7a187a300156c50eb4d75dfb17eaaeccc9c99e61...67c1f26fd4c3280e438d476b5d4b11416c311d1e
- https://github.com/paranext/paranext-extension-template-hello-world/wiki/Your-First-Extension-%E2%80%90-An-Easy-Start/_compare/44328a5ea7e44c1a1da87adc2a2e126323324b23...33a62deed1e3eba2e67f7172cdd939332f497993
- https://github.com/paranext/paranext-extension-template/wiki/PAPI/_compare/18bded63587e1d2da58fbd0f661393771d9d480f...c0aacb53b50d2104152ceb06b990bb0638889b78

Larger recommendation:
- Extension Anatomy
  - Move Data Provider Engine section down after `activate` and `deactivate`

**Comment by irahopkinson** [comment]
@tjcouch-sil thanks for improving the docs. The first link above you have added links with line numbers to files. That seems fragile to me with no way for anyone modifying the file to know this page needs updating. Perhaps still link to the file but use a description to get to the right line.

**Comment by tjcouch-sil** [comment]
> @tjcouch-sil thanks for improving the docs. The first link above you have added links with line numbers to files. That seems fragile to me with no way for anyone modifying the file to know this page needs updating. Perhaps still link to the file but use a description to get to the right line.

I agree that it's painfully fragile. However, I thought there was enough context to get them close enough for now. If you want to change something, feel free. And there is a link to `WebViewProps` in `papi.d.ts` somewhere, too, which is really bad since `papi.d.ts` is generated. I hope we can replace that once we generate API reference from `papi.d.ts` and use a markdown header link.
