### ISSUE TITLE
Create multi-extension template

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#486]
As an extension developer, I want to create multiple extensions together and run them in Platform.Bible together in order to develop quickly and efficiently as well as to organize my code.

As a core developer, I want to create multiple extensions together and run them in Platform.Bible together in order to have one repository for the Paratext.Bible extensions where all my changes show up together for efficiency and organization.

We may be able to use [merging subtrees](https://stackoverflow.com/a/29695610/8535752) to create a multi-extension template. We could have one repo that is a multi-extension template that has webpack config and such to support running multiple copies of the single extension template inside its `src` folder or something. There would be a bunch of extra config files in each extension folder that aren't typically used, but it would probably help merging to work more smoothly. And you could probably run each extension individually this way, too, which would be a benefit in some cases like if we made some sample extension repo that had a ton of little extensions in it.

**Comment by Sebastian-ubs** [comment]
https://discord.com/channels/1064938364597436416/1145779806684852285

**Comment by lyonsil** [comment]
This sounds more like submodules than subtrees, but I guess we'll see how it looks when someone investigates.

**Comment by tjcouch-sil** [comment]
PRs:
[Added multi-extension template based on paranext-core/extensions by tjcouch-sil · Pull Request #1 · paranext/paranext-multi-extension-template](https://github.com/paranext/paranext-multi-extension-template/pull/1)
[Prep for use in multi-extension-template by tjcouch-sil · Pull Request #55 · paranext/paranext-extension-template](https://github.com/paranext/paranext-extension-template/pull/55)

**Comment by tjcouch-sil** [comment]
PRs implementing the template:
https://github.com/paranext/paranext-core/pull/693
https://github.com/paranext/paratext-bible-extensions/pull/1

**Comment by roopa0222** [comment]
Testing Steps:
Cloned the repo from https://github.com/paranext/paranext-multi-extension-template
1. Created 2 extensions using the steps in the ReadMe.
2. Added 1 stand alone extension created from Paranext-extension-template.
3. Confirmed that all 3 Extensions displayed web-views without any errors.
4. Confirmed that all extensions are started at same time , so the data provider created in 1 extension is used in another without any errors.
5. Confirmed that 'npm run package' is building all individual extensions in release folder.
![Screenshot 2024-04-25 161436](https://github.com/paranext/paranext-core/assets/133702629/b9ab3ac1-3cc8-4910-8a5e-042d57cd8b2d)
![Screenshot 2024-04-25 155548](https://github.com/paranext/paranext-core/assets/133702629/920b5d20-3686-46e8-a185-41a1724ecc3e)
