### ISSUE TITLE
Finalize Text Collection extension

### ISSUE THREAD

**Issue by rolfheij-sil** [paranext/paranext-core#497]
These missing features should be implemented:
- [ ] Allow the splitter that appears when a full chapter is shown to be draggable
- [ ] Add a context menu to the project entries, like it appears in Paratext 9 https://github.com/paranext/paranext-core/issues/236. 
   Click [here](https://github.com/paranext/ux/issues/2) to see a completed design for Text Collections.
- [ ] Show book name instead of book number in title bar

**Comment by katherinejensen00** [comment]
This task was mostly a placeholder in the dev board for the UX task (which is now completed), but now UX has their own board we can easily see so there is no need for this case. https://github.com/paranext/paranext-core/issues/579 will implement those UX designs.
