### ISSUE TITLE
User Settings: Implement settings validators

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#504]
As an extension developer, I want to be able to validate the newly set values for my user settings on the PAPI so I and others can use my settings and trust they are within expected constraints.

----

Add a way for extensions to validate changes to their settings so they and others can only set the settings to be expected values:

- `papi.settings.registerValidator(key, validatorCallback)` - register a validator that the PAPI will call when someone tries to change that setting
  - `type SettingValidator: (newValue, currentValue, key, allChanges) => Promise<boolean>` where `allChanges` is an object representing all changes being made in one call to update settings. The object's keys are the setting keys being updated and values are objects with `newValue` and `currentValue`. Returns true if the new setting value is valid, false otherwise
  - When someone calls `papi.settings.set`, we should internally run the setting validator registered for that setting if one is available.
    - Should we not set if a validator is not available? That way, a setting will be the expected value. Disabling an extension wouldn't let you change it to some crazy value

Depends on #502

[Settings & State Design Doc](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit)

**Comment by roopa0222** [comment]
Test Repo steps
In my test extension I registered a settings validator in the main.ts

const SettingItemsPerPageValidator: SettingValidator<'paranext-ext-testing.itemsPerPage'> = async (
  newValue,
) => {
  logger.debug(`In SettingItemsPerPageValidator ${newValue}`);
  return typeof newValue === 'number' && newValue >= 5 && newValue <= 20;
};

On the webview used the 'useSetting' hook to display the default.
Confirmed that registerValidation is triggered when user set invalid value.
Confirmed that error message is logged on the dev tools console log with message
'network.service.ts:228 Uncaught (in promise) Error: Error setting value for key 'paranext-ext-testing.itemsPerPage': Error: validation failed
    at requestUnsafe (network.service.ts:228:32)'
![Screenshot 2024-04-29 151015](https://github.com/paranext/paranext-core/assets/133702629/fa94f96b-0c56-462b-8ed8-d9e8baf7cfbe)
![Screenshot 2024-04-29 150800](https://github.com/paranext/paranext-core/assets/133702629/cd7c9f2d-d375-44c7-9d09-4047e050078f)

**Comment by roopa0222** [comment]
Added another scenario where validation is not registered on Settings. 
Behaves similar to issue [#511](https://github.com/paranext/paranext-core/issues/511) and [#887](https://github.com/paranext/paranext-core/issues/887) @tjcouch-sil
