### ISSUE TITLE
Project Settings: Implement settings validators

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#511]
As an extension developer, I want to be able to validate the newly set values for my project settings on the PAPI so I and others can use my settings and trust they are within expected constraints.

----

Add a way for extensions to validate changes to their project settings so they and others can only set the settings to be expected values:

- `papi.projectSettings.registerValidator(key, validatorCallback)` - register a validator that the PAPI will call when a PSI calls `papi.projectSettings.isValid` when someone tries to change that project setting
  - `type ProjectSettingValidator: (newValue, currentValue, allChanges, projectType)` where `allChanges` is an object representing all changes being made in one call to update project settings. The object's keys are the setting keys being updated and values are objects with `newValue` and `currentValue`.
  - When someone calls `papi.projectSettings.isValid`, we should internally run the project setting validator registered for that setting if one is available. 
    - If a setting validator is not available, consider that a successful validation
      - Note: We decided that, between making absolutely sure getting a setting wouldn't blow up your code by being the wrong data type and making settings easy to set without tons of requirements, we should favor the second.
    - If the validator run throws an error, re-throw that error. If the validator returns false, throw an error indicating the validation failed. See settings service host's [`set` and `validateSetting`](https://github.com/paranext/paranext-core/blob/5c403e272b002ddd8970f735bc119f335c78c509/src/main/services/settings.service-host.ts#L124) for more context
  - Double check to make sure the notes on the PSI MandatoryDataTypes `Settings` data type mentions `setSetting` must call `papi.projectSettings.isValid(newValue, currentValue, key, allChanges, projectType)` before allowing the setting change

Depends on #509, see #504 which is very similar and code might be shareable

[Settings & State Design Doc](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit)

**Comment by roopa0222** [comment]
Test Repo Steps.
1. Updated the projectSettings.json in contribution folder with
```
[
  {
    "label": "%paranext-ext-testing.mainSettings%",
    "description": "%paranext-ext-testing.mainSettingsDescription%",
    "properties": {
      "paranext-ext-testing.highlightColor": {
        "label": "%paranext-ext-testing.highlightColor%",
        "description": "%paranext-ext-testing.highlightColorDescription%",
        "default": "Aqua",
        "includeProjectTypes": ["ParatextStandard"],
        "excludeProjectTypes": null
      },
      "paranext-ext-testing.itemsPerPage": {
        "label": "%paranext-ext-testing.itemsPerPage%",
        "default": 15,
        "minimum": 5,
        "maximum": 20,
        "shouldAllowProgrammaticChanges": true,
        "includeProjectTypes": ["ParatextStandard"]
      }
    }
  }
]

```
2. Added the exports on the types file paranext-ext-testing.d.ts
```
   export interface ProjectSettingTypes {
    'paranext-ext-testing.highlightColor': string;
    'paranext-ext-testing.itemsPerPage': number;
  }

```
3. In the main.ts used the PAPI to registered validators for Project Settings for `paranext-ext-testing.highlightColor`

```
const projectSettingsColorValidator = papi.projectSettings.registerValidator(
    'paranext-ext-testing.highlightColor',
    ProjectSettingHighlightColorValidator,
  );

const ProjectSettingHighlightColorValidator: ProjectSettingValidator<
  'paranext-ext-testing.highlightColor'
> = async (newValue) => {
  logger.debug(`In ProjectSettingHighlightColorValidator ${newValue}`);
  return typeof newValue === 'string' && newValue !== '';
};

```
4. On the web-view used the PAPI hook useProjectSetting to trigger validation rules
```
 const [
projectColor, setProjectColorInternally] = useProjectSetting(
    'ParatextStandard',
    '32664DC3288A28DF2E2BB75DED887FC8F17A15FB',
    'paranext-ext-testing.highlightColor',
    'Green',
  );
    <input
          id="ProjectSettingColorId"
          value={projectColorTmp}
          onChange={(e) => {
            setProjectColor(e.target.value);
          }}
        />
```
4.Confirm that error message is displayed in the console dev tool
6. Confirmed that value of the Items is updated even when no validation is registered on main.ts. PAPI tries and updates the value. New value is reflected when the page is refreshed. 
![Screenshot 2024-05-01 130636](https://github.com/paranext/paranext-core/assets/133702629/d986401c-4ce2-4e7e-b46e-c983b7cfe60a)
