### ISSUE TITLE
Fix startup race conditions

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#52]
The main process's web server, renderer process client, extension host client, and C# client all start at different times and don't wait on each other well. We need to fix this problem. Probably this task should mainly be about retrying WebSocket connections when they fail until they succeed. Hopefully, the activation event issue #51 may solve problems relating to actual commands not sending properly and such, but maybe this task can solve remaining issues if there are any after that point.

**Comment by irahopkinson** [comment]
The error looks like this:

![image](https://user-images.githubusercontent.com/5582153/224145570-012926cf-1791-4cea-97a5-f8b51d275142.png)

I was able to consistently reproduce the issue by deleting the `dev-appdata` folder.

**Comment by irahopkinson** [comment]
@tjcouch-sil: "added retry initial connection logic for the extension host so it just works whenever the main NetworkService is finished initializing. Maybe we can do the same for the C# client".
