### ISSUE TITLE
Create/hook up Run Checks Dialog

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#533]
**User Story**
As a user, I want to run some checks on my project so that I know what errors are present.

**Description**
Use whatever progress has been made so far and continue it to implement the run checks dialog (in the same extension the check stuff is in - at time of writing, the platform scripture extension):
Create this as a webview in platform scripture (not a tab as it currently is)
- [x] Add a ~~Run~~ Configure Checks web view in which you can select available checks to run on a project.
- [ ] ~~Clicking "ok" or something along the lines (look at UX style guide) should run the checks. Displaying the checks is in #1002, so just confirm somehow that they run successfully if that isn't implemented~~ (This doesn't apply anymore, now that the check runner will always be running the checks in the background)
- [x] Make the title of the run checks web view "Checks: XYZ" where "XYZ" is the short name of the project
- [x] Add a menu item to the editor to run checks for the open project

**Comment by katherinejensen00** [comment]
UX: Feel free to change the content of what is in the Run Checks title (e.g. have the short name - full name). I just put the short name there as a starting place/place holder.

**Comment by tjcouch-sil** [comment]
Comment that was previously in the description before rework:
> We're possibly going to be able to run checks from what was the "results list" tab from PT9. So it seems to make sense to call both the run checks dialog and the results of checks, "Checks".

**Comment by roopa0222** [comment]
Testing Steps Repo:

1. Open the Scripture Editor with WEB project from the main hamburger menu
2. Verfiied that 'Configure Check..' menu item is available on the projects displayed by Scripture Editor
3. Open the Configure Checks .. on the webview menu on WEB project
4. Verify that Configure Checks - WEB webview is displayed
5. Verify that project  name is displayed in the webview title `Configure Checks - WEB`
