### ISSUE TITLE
Error running build command in Github

### ISSUE THREAD

**Issue by jolierabideau** [paranext/paranext-core#567]
As a core developer, I want my changes to build in Github without failing on `Illegal characters in path` error.

```
[build:extension-host] [webpack-cli] Failed to load 'D:\a\paranext-core\paranext-core\.erb\configs\webpack.config.extension-host.prod.ts' config

[build:extension-host] [webpack-cli] Error: Illegal characters in path.
```
[Link to job run](https://github.com/paranext/paranext-core/actions/runs/6562418699/job/17824311329?pr=547)

So far, re-running the job will cause it to pass.

Looks like others are seeing this [issue with ERB](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3424)

**Comment by katherinejensen00** [comment]
Take 15 minutes to see if this can be solved through suggestion in issue link above. If it doesn't work, not our problem so forget about it.

**Comment by tombogle** [comment]
https://github.com/paranext/paranext-core/pull/696
