### ISSUE TITLE
Polish Text Collection

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#579]
**User Story**
As a user, I want easy to navigate Text collections so that I can easily see the same verse in multiple texts at once without getting frustrated with the UI.

**Description**
Change Text Collection to match the desgins and layouts found in the Figma Design Allison created:
Link to Figma Text Collections Dev Mode:
https://www.figma.com/file/C98AH5SWJ0Cmdgmdy1TdNe/Design-Text-Collections-%23429?type=design&node-id=2%3A2013&mode=dev

How to use Dev Mode:
https://help.figma.com/hc/en-us/articles/15023124644247-Guide-to-Dev-Mode

**Comment by tjcouch-sil** [comment]
Looks like [allotment](https://www.npmjs.com/package/allotment) is a pretty nice npm library for light-weight split panes.

**Comment by Sebastian-ubs** [comment]
Make text collection basis a papi component that is independent of the content (a list of items that can be re-ordered, can have additional menu actions and on click open other contentent alongside with the ability to resize)

Like this other extensions can use this interaction model for different components

**Comment by katherinejensen00** [comment]
If making the design changes would naturally involve creating a reusable papi component that Sebastian mentioned, go ahead and do it. Otherwise, make a new case for it and we will do it when we do the next iteration of Text Collection (scheduled in the road map). The focus for this case is really on design rather than new functionality.

**Comment by rolfheij-sil** [comment]
[PR](https://github.com/paranext/paranext-extension-text-collection/pull/24)

**Comment by rolfheij-sil** [comment]
https://github.com/paranext/paranext-extension-text-collection/pull/24
