### ISSUE TITLE
Open Word List to selected project from menu

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#600]
As a user, I want to be able to use a menu item to select a downloaded project to open with the Word list so I can see things.

----

As a quick way to get this working for the tech demo, I propose the following course of action:
- [x] Create a `wordList.open` command in the Word list extension that does the following:
  1. Opens a Select Project dialog to choose which project to open. When the user selects a project, the project id will be returned to the command code
  2. Call `papi.webViews.getWebView` to get a new Word List webview. Provide the project id in the options object (extra properties will get carried along to the webview provider function). Return the return from `getWebView` from the command.
  3. When the webview provider receives the request to create the webview, get the project id from the options object (passed from step 2). Set that as part of the webview state.
           - [ ] Set the title to include name of selected project
  4. Adjust the Word List webview so it uses the new webview state to get the project ID to show
- [x] Create a baked-in menu item that calls the new `wordList.open` command. This lets us avoid implementing the menu design by tech demo time.

**Comment by tjcouch-sil** [comment]
Glenn said let's try to get this in by the tech demo.

**Comment by rolfheij-sil** [comment]
Pull requests:

https://github.com/paranext/paranext-extension-word-list/pull/3
https://github.com/paranext/paranext-core/pull/602
