### ISSUE TITLE
Word list dropdown to choose between showing current book and current chapter

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#601]
**User Story**
As a user, I want to be able to filter my word list on different selections so that I can effectively see the words in my project.

**Description**
Add a combobox to the Word List that lets you choose between current book and current chapter filtering. Bonus points for current verse, but don't focus on it.

**Comment by tjcouch-sil** [comment]
Glenn said let's try to get this in by the tech demo.

**Comment by rolfheij-sil** [comment]
Pull request [here](https://github.com/paranext/paranext-extension-word-list/pull/2)
