### ISSUE TITLE
Stop breaking out data types (USFM, USX, etc.) from PDPs with different API calls

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#609]
**User Story**
As an extension developer, I don't want to need to target different APIs for data if it's USFM vs USX vs USJ vs plain text vs something else.  I just want my Paratext data provider that I tell how the data should be formatted.

**Description**
Right now, we make things a little more confusing for extension developers and ourselves by separating out different PDP data types for chapter USFM, chapter USX, chapter USJ, etc.  We should just have a way to say "get book/chapter/verse" and specify the requested data type.

This came up because one of the controls we were using was getting one type when we really would have preferred a different one.  Because we have to make a different PDP API call for each (book/chapter/verse) and (USFM/USX/USF/etc.) combination, it is tedious and more error prone since more things have to be updated.

Note: This will likely involve breaking out ScriptureData into its own type, but even that might not solve it (talk to TJ for more details)

TJ's comment on this:

> I imagine we will probably need to change the selector to an object that contains this data format thing and the VerseRef... Or an array whose first entry is the verse ref and second is the format? Feels less flexible but also less annoying 😂

**Comment by FoolRunning** [comment]
I don't understand how the API is "confusing" right now. I feel like it's very sensible - if I want USX, I call a ``get...USX`` method. I also don't understand how changing from one data type to another would be any less tedious with this change. You're either changing out the ``get...`` methods for other ``get...`` methods or changing out the data type parameter for another type parameter - basically the same amount of code changes either way.
Also, based on TJ's comment, it sounds like it might make things complicated to call (having to create an object or an array).
Someone please tell me what I'm missing here. 🤔

**Comment by tjcouch-sil** [comment]
This is more about making the appropriate distinction between the data type and the selector. Data types control the kind of data you're getting (like Scripture for example. And updates go out based on data type), whereas selector controls what specific data you want (and should probably control how you want it to look since these different formats are still all the same data).

If we stay split out so the different data formats have different PDP data types associated with them, we will have to make sure that our event that announces updates announces updates to all of these PDP data types when any of them change since they are all technically the same data behind the scenes. If we move the "how the data should look" part into the selector, I imagine we will have fewer potential issues with sending out the wrong data types.

Seems like this is a refinement of our best practice recommendations regarding the distinction between the data type and the selector to match the underlying technology better.

However, we do have the complication of figuring out how to make intellisense work right to return the correct data type depending on what format we specify. I don't know yet how we would do such a thing. Would take some playing around to see if it's even possible. I would consider not doing this if we can't get intellisense to work right honestly.

**Comment by FoolRunning** [comment]
If that's the main reason (and not what was specified in this task), then that makes sense, but I, then, think we should make the PSI <-> PDP relationship how I thought we originally designed it - the PSI will only deal with one data format (e.g. USFM) and the PDP is the thing responsible for transforming the data into other formats. (maybe even a new PDP for each data format?).

The way it is now, the PDP seems to just be a passthrough to the PSI which IMO defeats the purpose of splitting them up.

**Comment by tjcouch-sil** [comment]
Indeed, the first round of issues around project design (all we have implemented so far) didn't even include a PSI. I think Matt threw something in for the PSI to have some resemblance of what it will look like longer-term. I think the later project-related issues will need to fix the apis so they are separated as you mentioned.

**Comment by tjcouch-sil** [comment]
I did some simple testing to determine if this might be currently supported, and it seems it is not. Maybe if we try really hard, we can add some kind of `DataProviderAdvancedDataTypes` that have more generics, and `DataProviderDataTypes` can just translate to a `DataProviderAdvancedDataTypes` under the hood for a seamless transition. Maybe. But those generics will probably make for some really crazy and hard-to-understand type signatures on the methods if we want to return different things if we could even figure out how. Might be best to leave it where we say if you want different types, make a different `DataProviderDataType`.

<details><summary>Expand to see my testing</summary>
<p>

```typescript
declare module 'papi-shared-types' {
  export interface DataProviders {
    stuff: StuffDataProvider;
  }
}

// You cannot provide multiple of the same key here
type StuffDataProviderDataTypes = {
  Stuff: DataProviderDataType<string | number, string | number | undefined, string | number>;
};

// This one didn't work with `registerEngine`. It showed the type of the engine was `never`
/* type StuffDataProvider = {
  getStuff(sel: string): Promise<string | undefined>;
  setStuff(
    sel: string,
    stuff: string,
  ): Promise<DataProviderUpdateInstructions<StuffDataProviderDataTypes>>;
  subscribeStuff(
    sel: string,
    callback: (stuff: string | undefined) => void,
    options?: DataProviderSubscriberOptions,
  ): Promise<UnsubscriberAsync>;
}; */

// This one did work with `registerEngine`. It seems the types for `getStuff` and `setStuff` had to be
// exactly matching StuffDataProviderDataTypes for it to be able to infer the correct type for the engine.
// However, you can also put overloads on the methods that get you to the specific types. But these
// overloads are not detected by `useData`. You can only use them if you get the data provider itself
type StuffDataProvider = {
  getStuff(sel: string): Promise<string | undefined>;
  getStuff(sel: number): Promise<number | undefined>;
  getStuff(sel: string | number): Promise<string | number | undefined>;
  setStuff(
    sel: string,
    stuff: string,
  ): Promise<DataProviderUpdateInstructions<StuffDataProviderDataTypes>>;
  setStuff(
    sel: number,
    stuff: number,
  ): Promise<DataProviderUpdateInstructions<StuffDataProviderDataTypes>>;
  setStuff(
    sel: string | number,
    stuff: string | number,
  ): Promise<DataProviderUpdateInstructions<StuffDataProviderDataTypes>>;
  subscribeStuff(
    sel: string,
    callback: (stuff: string | undefined) => void,
    options?: DataProviderSubscriberOptions,
  ): Promise<UnsubscriberAsync>;
  subscribeStuff(
    sel: number,
    callback: (stuff: number | undefined) => void,
    options?: DataProviderSubscriberOptions,
  ): Promise<UnsubscriberAsync>;
  subscribeStuff(
    sel: string | number,
    callback: (stuff: string | number | undefined) => void,
    options?: DataProviderSubscriberOptions,
  ): Promise<UnsubscriberAsync>;
};

// This is here to detect what TypeScript thinks the type of the engine is
dataProviderService.registerEngine('stuff',)

// `thing` here is `string | number | undefined` even though we put in a string for the selector
const [thing] = useData('stuff').Stuff('thing', 'stuff');

// Here we demonstrate that you can use overloads from the data provider if you have the data provider
// itself, not just using it through `useData`
const dp = await dataProviderService.get('stuff');
// `thisIsAStringType` indeed understands we are using the overload that gives us a string
const thisIsAStringType = dp?.getStuff('stuff');
```

</p>
</details>

**Comment by lyonsil** [comment]
Not needed/desired now that we have interfaces
