### ISSUE TITLE
Word List gets stuck loading if you change verse ref too quickly

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#613]
**Describe the bug**
When you change verse ref quickly, the word list gets stuck loading and doesn't show the table.

**To Reproduce**

1. Open the Word List
2. Click to change the verse ref a few times quickly
3. Notice that it doesn't show the table (sometimes)

**Expected behavior**
The word list should load and show the table every time.

NOTE: This can be a quick fix for the tech demo if it turns out this bug is too hard to solve beforehand. This may be another manifestation of #597. See how Matt quick fixed another issue there. However, this may also be related to the data provider code in the word list main file or something else, so investigate.

**Comment by rolfheij-sil** [comment]
This bug was fixed as part of other work, so there is no related branch or pull request
