### ISSUE TITLE
Create new component: Settings dialog

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#621]
**User Story**
As a user, I want all settings to be presented in a similar way

**Description**
Create a common papi component for
- https://github.com/paranext/paranext-core/issues/503
- https://github.com/paranext/paranext-core/issues/510

This component should use the following components
- [ ] Dialog https://github.com/paranext/paranext-core/issues/470
- [ ] Vertical tab navigator https://github.com/paranext/paranext-core/issues/620
- [ ] Settings list - a new sub component to be created, that represents a single list of settings (e.g. of one category inside of a tab navigator tab).
    - is that the same thing mentioned twice in # 503 **and** # 510 as "_Provide components for settings created_"?
    - Compare https://github.com/paranext/paranext-core/blob/dfd9119c04590f8b559aa9d8200f0ab36035efa0/src/renderer/components/settings-dialog/settings-tab.component.tsx#L368-L389

[Mockups dev link](https://www.figma.com/file/zJWrApZ8AyPGxNHdndbkTz/Settings-Dialog-Stub-%23434?type=design&node-id=141-3972&mode=dev)
Dialog|Vertical tab navigator|Settings list
-|-|-
![Screenshot 2023-11-03 145903](https://github.com/paranext/paranext-core/assets/141921979/45333bc4-c3d1-4118-bda4-89cc0d033da3)|![grafik](https://github.com/paranext/paranext-core/assets/141921979/55afa44f-984e-4f84-841c-c1980942a2a7)|![grafik](https://github.com/paranext/paranext-core/assets/141921979/0f47e289-7aac-4e27-8201-33df61bbddac)

**Comment by tjcouch-sil** [comment]
@Sebastian-ubs can this be closed? I believe this was done with #867

**Comment by Sebastian-ubs** [comment]
what's described in here is basically done. the story for the new design to come is
- https://github.com/paranext/paranext-core/issues/1213
