### ISSUE TITLE
Remove constraints around project folder name

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#623]
**User Story**
As a user, I want my project data to be stored in a format that works for any project short name and id so that I can use any project from any source.

**Description**
Right now, we have a project folder in the file system called `<short_name>_<project_id>` for each project. It is required to have that name. However, since we already have short name and project ID in the metadata, this information embedded into the folder name is unnecessary and is prone to errors. It is also hard to create. Most importantly, however, it puts unhelpful restrictions on the possible characters used for short name and project id because underscore is now a special character and file names on the file system cannot use certain characters.

Instead, let's have the default folder name created be something like `<short_name>_<project_id>` if someone creates or imports a project, then let's just ignore the folder name and use the metadata when using the project in the future.

**Comment by tombogle** [comment]
WIP: https://github.com/paranext/paranext-core/pull/653
