### ISSUE TITLE
Make it easy to run extensions that are separate processes

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#625]
If someone has a bunch of code already in some other language or there is a particular toolkit available only in a specific language (e.g., python), we should make it much easier to have an extension that is in a different process.  TJ suggested treating these other processes in the same way as the .NET host, which is good, but that is baked in.  We would need to figure out how to register these other processes in manifests and how to specify which executable to run depending on the OS, hardware, etc.

Extension needs to request an elevated privilege for this

We should probably give them child_process(ish). Let them run stuff. We should probably track their process and close it when we close our software.

**Comment by tjcouch-sil** [comment]
It is worth considering a few things:
- do we bundle extension executables and run them freely? They would have to make their own websocket protocol
- do we figure out a way to do native modules? they probably couldn't use Python for example
- do we just say use webassembly? Python has native modules that people like using (we :heart: pandas)
Maybe all three of these would be worth doing!

**Comment by lyonsil** [comment]
The "createProcess" elevated privilege should allow us to do this now in a reasonable way. Unless someone asks for something more, we can consider this complete.
