### ISSUE TITLE
Prevent 2 copies of Platform.Bible from running at the same time

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#636]
**Describe the bug**
The platform becomes unpredictable when more than one copy is open at once.  For example, clicking a button in one application can cause things to happen in the other.  I'm assuming this is because we're using fixed ports, and messages are flowing from front ends of one app to the back end of another app.

**To Reproduce**
Open 2 copies of Platform.Bible at the same time and start trying things out.

**Expected behavior**
Either both copies should work totally independently of each other or we should stop the second copy from even starting.

**Comment by FoolRunning** [comment]
Since we don't support moving tabs/panes to another monitor, people will definitely want to start multiple instances. It would be ideal if the backend could somehow support multiple frontends so data updates would be seamless between the two.

**Comment by lyonsil** [comment]
We decided we want to allow this in a backlog grooming discussion on 2024-07-01.

**Comment by Sebastian-ubs** [comment]
linking to https://github.com/paranext/paranext-core/issues/929

**Comment by lyonsil** [comment]
After talking further, we think this workflow will be better served by allowing multiple windows in one instance than multiple instances. A second instance will raise some other design concerns and considerations (e.g., notifications between instances, shared vs separate settings, etc.).
