### ISSUE TITLE
Rework C# code to remove `dynamic`

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#645]
**User Story**
As a user, I want stable and fast code so that things don't crash and stuff.

**Description**
We use `dynamic` in a bunch of places on C# where it is probably not necessary. Refactor the code to remove these uses.

Additionally, Matt and TJ discussed adding a helper class (`DataProviderUpdateInstructions` like the type on the TS side? Or whatever) to strengthen `DataProvider.SendDataUpdateEvent`. It's messy spaghetti right now.

**Comment by lyonsil** [comment]
Matt has opinion on this and will probably just take it. :)
