### ISSUE TITLE
Change `deserialize` to recreate `null` JSON properties recursively as JS/TS objects with `undefined` properties rather than dropping those properties

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#672]
**User Story**
As a Platform.Bible developer, I want to be able to define web view state or other objects with undefined properties and have those properties reappear when serialized/deserialized,  This is so that I can make my web view state objects (or other serialized objects) more to my liking rather than having to provide default/dummy values for all properties.

**Description**
`deserialize` currently replaces all `null` properties with `undefined`.  This is desirable because we want to largely eliminate the use of `null` in our own code.  (See #642).  However, when `JSON.parse` looks at the results of a `resolver` call, it just drops `undefined` properties rather than setting the properties as `undefined` on the returned object.  That means we will need to do something like leaving all the `null` properties as `null` than crawl through the returned object's property tree/graph to do the `null`->`undefined` conversion ourselves.

**Comment by tjcouch-sil** [comment]
[Here's our discussion](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvHILq9DmQFF1k0Fq8) on this topic for background info and implications if needed.

**Comment by tjcouch-sil** [comment]
![Image](https://github.com/paranext/paranext-core/assets/104016682/cea90b0a-e899-49ea-968f-f4dd98fc85fc)
