### ISSUE TITLE
Investigate Reviewable

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#70]
Figure out if we should use Reviewable?
- [x] Is it free and easy to transition to? Thinking about totally open source project
- [x] Can you limit sharing permissions to only paranext?

**Comment by tjcouch-sil** [comment]
![Image](https://user-images.githubusercontent.com/104016682/224835668-fbd228a3-485c-40a3-b89e-6481c342f5cd.png)

**Comment by irahopkinson** [comment]
It's free for open source, see [reviewable.io](https://reviewable.io/):
![image](https://user-images.githubusercontent.com/5582153/225494435-793cc4c5-0abb-4d25-8778-e780405e2c4b.png)

It asks for access to all your personal repos but you must grant it access to each organization. @tjcouch-sil already approved access to our Paranext org:
![image](https://user-images.githubusercontent.com/5582153/225496131-77f3e6ee-b4db-49b9-997a-2d61e89e6ff6.png)

**Comment by irahopkinson** [comment]
I just enabled **Reviewable** for the `paranext`, `paranext-core` and `paranext-extension-template` repos. Its now enabled for the 2 existing PRs #72 and #80. I'll test it by creating a PR for issue #81.

**Comment by irahopkinson** [comment]
I've made **Reviewable** required for PRs in the `paranext`, `paranext-core` and `paranext-extension-template` repos.

**Comment by tjcouch-sil** [comment]
Fortunately it seems not to have asked for change permission on any of my personal repos, private or public. That's what I was hoping for :)


![Image](https://user-images.githubusercontent.com/104016682/225631248-a52f2bee-9ce0-4a1b-a804-bae074cd0212.png)
