### ISSUE TITLE
Menus: Create context menu component (single column) to render menu based on JSON document as specified

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#707]
As a Platform.Bible extension developer, I want to be able to add menus to my webviews and contribute to extensible points in platform-provided menus.

---

This particular task is about having menu components that take a "final" menu JSON document for a single column, context menu and display the menu items appropriately. The menu JSON document definition is in the [menu contribution design document](https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?usp=drive_link).

It is important for the component to align with the schema from the design document.

Note that the items in a menu should be considered fixed while the menu is open/drawn on the screen.  Once the menu is closed/hidden, its content should be reloaded before rendering again because extensions might have been enabled/disabled or something else might have changed that would modify the list of available menu items.

**Comment by tombogle** [comment]
Note: The GridMenu component allows for multiple columns (and has the class "papi-multi-column-menu"). If we use that component, even though there is a single column, it will display a "column name" at the top, which I assume is not what we want. I'm thinking we probably want to factor out the part of MenuColumn that maps items to MenuItems to use for our context menu and then us that component internally to implement MenuColumn.
