### ISSUE TITLE
User Settings: Include settings JSON documents from extensions

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#718]
As an extension developer, I want to be able to get settings' values including defaults like interface language so I can stay in sync whether or not the setting has been set.

----

Extensions need to be able to provide JSON documents that specify their settings. Update the build process for extensions including the core extensions to provide settings JSON according to [the settings contribution point specification](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit#heading=h.fjg01wdfi36k).

This issue is not about validating the documents or serving the documents; it is simply about including them in the extensions.

Testing Idea: test to make sure the json document makes it into the final zip. Note, this will be easier to test when settings end to end are working.

This issue is based on #421 and is very similar.

**Comment by roopa0222** [comment]
Repo steps.
In my test extension at location C:\Repos\paranext-ext-testing
1. I ran npm run build on terminal
2. Confirmed that settings.json is present in dist/contribution folder
3. I ran npm run package on terminal
4. Confirmed that  paranext-extension-template_0.0.1.zip is build in release folder
5. Confirmed that settings.json is present in paranext-extension-template_0.0.1.zip/contribution folder
![Screenshot 2024-04-24 145220](https://github.com/paranext/paranext-core/assets/133702629/ff673f37-4f33-4cf3-b6f1-63202a23d237)
![Screenshot 2024-04-24 145131](https://github.com/paranext/paranext-core/assets/133702629/2f0e3563-9815-4031-8d79-b56520906d74)
