### ISSUE TITLE
Project Settings: Include project settings JSON documents from extensions

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#720]
As an extension developer, I want to be able to get project settings' values including defaults so I can stay in sync whether or not the project setting has been set.

----

Extensions need to be able to provide JSON documents that specify their project settings. Update the build process for extensions including the core extensions to provide project settings JSON according to [the project settings contribution point specification](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit#heading=h.md11ejpp976c).

This issue is not about validating the documents or serving the documents; it is simply about including them in the extensions.

Testing Idea: test to make sure the json document makes it into the final zip. Note, this will be easier to test when project settings end to end are working.

This issue is based on #421 and is very similar.

**Comment by roopa0222** [comment]
In my extenstion 'paranext-ext-testing' I ran npm run build and I can see the projectSettings.json  is in dist folder.
I also ran npm run package on my extension and verified that projectSettings.json is in paranext-extension-template_0.0.1.zip under release folder
![Screenshot 2024-04-05 154521](https://github.com/paranext/paranext-core/assets/133702629/3754c9fe-28fc-471a-a0ac-7479ad8aebf6)
![Screenshot 2024-04-05 155323](https://github.com/paranext/paranext-core/assets/133702629/6cda3a16-75d6-4b82-8aab-90689afae215)
.
