### ISSUE TITLE
Project Settings: Read default values from extension JSON

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#721]
As an extension developer, I want to be able to get project settings' values including defaults so I can stay in sync whether or not the setting has been set.

----

On the project settings service:
- Maintain list of all project settings' defaults provided by extensions in their manifest files and built into core instead of the list just being hard-coded

Depends on #419, #509, #720

**Comment by roopa0222** [comment]
Test Repo Steps.
1. Updated the projectSettings.json in contribution folder with
```
  [
  {
    "label": "%paranext-ext-testing.mainSettings%",
    "description": "%paranext-ext-testing.mainSettingsDescription%",
    "properties": {
      "paranext-ext-testing.highlightColor": {
        "label": "%paranext-ext-testing.highlightColor%",
        "description": "%paranext-ext-testing.highlightColorDescription%",
        "default": "Aqua",
        "includeProjectTypes": ["paranext", "ResourceViewer"],
        "excludeProjectTypes": null
      },
      "paranext-ext-testing.itemsPerPage": {
        "label": "%paranext-ext-testing.itemsPerPage%",
        "default": 15,
        "minimum": 5,
        "maximum": 20,
        "shouldAllowProgrammaticChanges": true,
        "includeProjectTypes": null
      }
    }
  }
]

```
2. Added the exports on the types file paranext-ext-testing.d.ts
```
   export interface ProjectSettingTypes {
    'paranext-ext-testing.highlightColor': string;
    'paranext-ext-testing.itemsPerPage': number;
  }

```
3. In the main.ts uses the papi to display the default Project Settings

```
const projectSettingColorDefault = papi.projectSettings.getDefault(
    'paranext-ext-testing.highlightColor',
    'platform.placeholder',
  );

  const projectSettingItemsDefault = papi.projectSettings.getDefault(
    'paranext-ext-testing.itemsPerPage',
    'platform.placeholder',
  );

  logger.debug(`Project settings default Color : ${await projectSettingColorDefault}`);
  logger.debug(`Project settings default Items : ${await projectSettingItemsDefault}`);

```

Confirmed that values are displayed in the main.log
[2024-04-30 11:51:02.530] [info]  [extension host] 11:51:02.527 > Project settings default Color : Aqua [at Object.<anonymous> C:\Repos\paranext-ext-testing\dist\src\main.js:787:23]
[2024-04-30 11:51:02.527] [debug] Project settings default Color : Aqua [at Object.<anonymous> C:\Repos\paranext-ext-testing\dist\src\main.js:787:23]
[2024-04-30 11:51:02.536] [info]  [extension host] 11:51:02.533 > Project settings default Items : 15 [at Object.<anonymous> C:\Repos\paranext-ext-testing\dist\src\main.js:799:24]
[2024-04-30 11:51:02.533] [debug] Project settings default Items : 15 [at Object.<anonymous> C:\Repos\paranext-ext-testing\dist\src\main.js:799:24]
