### ISSUE TITLE
Project Settings: Implement getting project settings on C# `ParatextProjectDataProvider`

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#723]
As an extension developer, I want to be able to access Paratext-related project settings like books present on the PAPI so I can develop effectively.

----

Implement `getSetting`, `setSetting`, and `resetSetting` on the C# `ParatextProjectDataProvider`. See #509 for details on these functions. They must call `papi.projectSettings.isValid` and `papi.projectSettings.getDefault` appropriately.

Depends on #509, #57

**Comment by roopa0222** [comment]
Test Repo Steps:

1.On the web-view able used PAPI useProjectSettings hook to display Paratext project setting bookspresent.
```
const [projectParatextStandard] = useProjectSetting(
    'ParatextStandard',
    '32664DC3288A28DF2E2BB75DED887FC8F17A15FB',
    'platformScripture.booksPresent',
    '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  );
```
2.Confirmed that UI displayed the value from the setting.xml file from c-sharp/assets
![Screenshot 2024-05-01 142135](https://github.com/paranext/paranext-core/assets/133702629/56958d1f-4d0e-42f4-b666-721ee838af2c)
