### ISSUE TITLE
Internationalization: Improve localization service

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#738]
**User Story**

As a user, I want Platform.Bible to have the equipment in place to be able to display the UI in my language so I can work effectively.

**Description**

Let's improve the localization service from [its placeholder state](https://github.com/paranext/paranext-core/issues/418):
- [x] Implement falling back to English if a localized string doesn't exist for a language
- [x] Rework the service to accept the [new data format](https://docs.google.com/document/d/1dFSTR6bgt7n0HaXOvnV3Cc-z1R2S9Gb5KlNlIS4liQI/edit#heading=h.o5exds20bl2g)
  - [x] Implement `metadata.json` - particularly `fallbackKey`. Note `fallbackKey` should be checked for a locale before going to the fallback language. For example, if someone is asking for a string in 'es' that doesn't exist in that locale, the `fallbackKey` should be checked in 'es' *before* falling back to fallback language main string key *then* fallback language `fallbackKey`. See examples in the spec (linked above) for more clarification
- [x] Rework the service so it throws if it doesn't find a localized string in development (and please add the key name to the error message) and just returns the key in production
- [x] Rework the service to use a data provider instead of just a network object (see menu store service for an example)
  - Suggested implementation: just one data type which is `''` (nothing) - feel free to do something different like two data types or multiple names
    - [x] selector `LocalizeKey` localized string key which returns the localized string.
    - [x] selector `LocalizeKey[]` localized string keys which return the localized strings in an object
    - [x] selector `{ key: LocalizeKey, options?: LocalizedStringOptions }` returns localized string
    - [x] selector `{ keys: LocalizeKey[], options?: LocalizedStringOptions }` returns localized strings in an object
    - [x] `LocalizedStringOptions` should just be an object type
      - [x] optional `locale` - either the locale code to look up with or an array of locale codes to look up and back up to (0th index should be first to look up. If not present, try 2nd index. etc)
- [x] Make a setting for the UI language and fallbacks instead of using a hard-coded const
  - [x] an array of locale strings. The lowest string in the array is the highest preference. 'en' doesn't have to be listed but still works as a last fallback in our interfaces. So if the setting were set to `['fr', 'pt']`, it would try French first, Portuguese second, and English third as if it were `['fr', 'pt', 'en']`.
  - [x] On startup, if the setting isn't set, we should get the current locale from #735's get locale function
- [x] Use BCP 47 as the language code spec
  - [x] Adjust the regex for getting files in the localization folder to accept more stuff like `-` and numbers
  - [x] Use [`Intl.getCanonicalLocales()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales) to normalize file names, locale setting, requested locales, etc.
  - [x] Rename files on disk to BCP 47 equivalents
- [ ] Add a service method to localize VerseRef book name
  - [ ] Localizing book names: copy [how Paratext does it](https://github.com/ubsicap/Paratext/blob/master/ParatextData/SILScriptureExtensions.cs#L72) for now
  - Full reference localization is in #736

[Internationalization Spec](https://docs.google.com/document/d/1dFSTR6bgt7n0HaXOvnV3Cc-z1R2S9Gb5KlNlIS4liQI/edit)

**Comment by merchako** [comment]
If it's the same amount of effort, you might want "falling back to English" to be a recursive "fall back to X which falls back to Y…".

**Comment by merchako** [comment]
FYI, there exist languages which use multiple scripts in significant proportion. For example, Adamawa Fulfulde (fub) uses both Latin and Arabic. I can't think of any that we'd localize into soon.

**Comment by roopa0222** [comment]
Repo Test steps:

1. Added a new Telugu localization file te.json in C:\Repos\paranext-core\assets\localization
```
{
  "%submitButton%": "సమర్పించండి",
  "%Book.Gen%": "ఆదికాండము"
}
```
2. Used PAPI on the front end to see the localization work.
```
const [localizedString] = usePromise(
    useCallback(() => {
      return papi.localization.getLocalizedString({
        localizeKey: '%submitButton%',
        locales: ['te', 'fr', 'en'],
      });
    }, []),
    'defaultValue',
  );

  const [localizedGenesisString] = usePromise(
    useCallback(() => {
      return papi.localization.getLocalizedString({
        localizeKey: '%Book.Gen%',
        locales: ['te', 'fr', 'en'],
      });
    }, []),
    'defaultValue',
  );
```
3.Confirm that Submit and Book of Genesis are displayed in Telugu
![Screenshot 2024-05-06 131943](https://github.com/paranext/paranext-core/assets/133702629/f2950ce9-a8e1-42d9-9a40-a525dc81ea77)
