### ISSUE TITLE
Internationalization: Create `useLocalizedStrings` hook and format function

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#741]
**User Story**

As a user, I want Platform.Bible to have the equipment in place to be able to display the UI in my language so I can work effectively.

**Description**

Depends on #738

- [x] Create a hook that wraps the localization service and gets strings as passed into the hook. While loading the localized strings, just pass back an empty string if the input was just one key or an object with empty strings if the input was multiple keys.
- [x] Create a formatting utility function in `platform-bible-utils` that replaces `{stuff}` - `format(stringToFormat, replacers: { [key: string]: value: string }): string`-ish. Also needs to remove backslash \ on `\{` and `\}` in case there are escaped curly braces.
  - Can probably adapt `git.util.ts`'s `formatGitErrorTemplate` if you want
  - ex:
```typescript
console.log(format('Hi, this is {name}! I like \{curly braces\}!', { name: 'Jim' }));
```
 - output:
```
Hi, this is Jim! I like {curly braces}!
```

You may be able to use `useData` to make this hook easier.

**Testing Ideas**
Test the new string utility function, formatReplacementString, in a webview. You can use the example above or any example of your choice. I would recommend including a word to replace in unescaped curly braces (e.g. {name}) and a word in escaped curly braces that should not be replaced (e.g. \{unreplaceable\}).

Tests can now replace 
usePromise(
    useCallback(() => {
      return papi.localization.getLocalizedString({

with

useLocalizedStrings

Note: if you use useLocalizedStrings, you will need to wrap the keys array in useMemo and the locales array in useMemo.

**Comment by roopa0222** [comment]
Test Repo Steps:

1. Added te.json file in the C:\Repos\paranext-core\assets\localization\te.json

> ```
>  {
>   "%submitButton%": "సమర్పించండి",
>   "%Book.Gen%": "ఆదికాండము"
> }
> ```
> 

2. Updated my test extension to use the useLocalizedStrings hook on the web-view
 

> ```
> const [localizedStrings] = useLocalizedStrings(
>     useMemo(() => ['%submitButton%', '%Book.Gen%', '%wordList%'], []),
>     useMemo(() => ['te', 'fr', 'en'], []),
>   );
> 
>   const localizedString = localizedStrings['%submitButton%'];
>   const localizedGenesisString = localizedStrings['%Book.Gen%'];
>   const localizedFallbackString = localizedStrings['%wordList%'];
> ```
> 

3. Confirmed that the text is displayed in Telugu and English is displayed as fallback

![localizationHookTest](https://github.com/paranext/paranext-core/assets/133702629/b1984a59-b595-4f2e-8ccf-e2853df85630)

**Comment by katherinejensen00** [comment]
These test steps look great. Thanks, Roopa!
