### ISSUE TITLE
Implement BCV Control Design using Shadcn/ui+Radix

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#771]
## User Story
As a developer, I want to choose a UI toolkit to use forever so we can standardize designs with a system so that we can implement UI designs as efficiently as possible.

As a translator or advisor, I want to navigate to different texts and to different books, chapters, and verses within a text. I want to be able to sync navigation across multiple views and tools.

## Description
UI Toolkits Bakeoff Contestant # 1, Shadcn/ui+Radix. Implement the BCV control design in the toolkit, doing all you reasonably can to match the design, particularly in appearance so we can get a good feel of how easy the components are to customize. 

- [UI Toolkit Research](https://docs.google.com/document/d/1AKCBTjSbnZroqJFK0MQd6AaHMNOYAp3WokB19OquLck/edit?usp=sharing) background doc
- [Figma Design](https://www.figma.com/file/4ubCDQA1nqjFTHHtX2BFtb/Tab-Location-(BCV)-Selector-%231?type=design&node-id=1148-7120&mode=design&t=Q7mqe4Je1WphuaP7-4)
- [UX created sandbox](https://codesandbox.io/p/devbox/my-shadcn-playground-working-p46zk8?file=%2Fsrc%2FApp.js)

Code Style Thoughts from Sebastian
  - Create little components (e.g. for the book name list entry)

## Results
Note your thoughts about the usability of the toolkit in [Toolkit Evaluation](https://docs.google.com/document/d/1AKCBTjSbnZroqJFK0MQd6AaHMNOYAp3WokB19OquLck/edit#heading=h.qsukq3lvkybb)

Be ready to demo BCV at the sprint demo planning meeting.

**Comment by Sebastian-ubs** [comment]
reference to the first task
- https://github.com/paranext/paranext-core/issues/776

**Comment by tjcouch-sil** [comment]
[Composition – Radix Primitives](https://www.radix-ui.com/primitives/docs/guides/composition#composition)
[primitives/packages/react/dropdown-menu/src/DropdownMenu.tsx at main · radix-ui/primitives](https://github.com/radix-ui/primitives/blob/main/packages/react/dropdown-menu/src/DropdownMenu.tsx)
[primitives/packages/react/primitive/src/Primitive.tsx at main · radix-ui/primitives](https://github.com/radix-ui/primitives/blob/main/packages/react/primitive/src/Primitive.tsx)
[primitives/packages/react/slot/src/Slot.tsx at main · radix-ui/primitives](https://github.com/radix-ui/primitives/blob/main/packages/react/slot/src/Slot.tsx#L79)
