### ISSUE TITLE
Implement BCV Control Design using Shoelace

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#772]
## User Story
As a developer, I want to choose a UI toolkit to use forever so we can standardize designs with a system so that we can implement UI designs as efficiently as possible.

As a translator or advisor, I want to navigate to different texts and to different books, chapters, and verses within a text. I want to be able to sync navigation across multiple views and tools.

## Description
UI Toolkits Bakeoff Contestant # 2, Shoelace. Implement the BCV control design in the toolkit, doing all you reasonably can to match the design, particularly in appearance so we can get a good feel of how easy the components are to customize. 

- [UI Toolkit Research](https://docs.google.com/document/d/1AKCBTjSbnZroqJFK0MQd6AaHMNOYAp3WokB19OquLck/edit?usp=sharing) background doc
- [Figma Design](https://www.figma.com/file/4ubCDQA1nqjFTHHtX2BFtb/Reference-Selector-Control-%231?type=design&node-id=1126%3A22842&mode=design&t=MIGRoLWRVS9jbcFV-1)
- [UX created sandbox](https://codepen.io/Sebastian-ubs/pen/yLwErNZ?editors=1100)

Code Style Thoughts from Sebastian
  - Create little components (e.g. for the book name list entry)

## Results
Note your thoughts about the usability of the toolkit in [Toolkit Evaluation](https://docs.google.com/document/d/1AKCBTjSbnZroqJFK0MQd6AaHMNOYAp3WokB19OquLck/edit#heading=h.qsukq3lvkybb)

Be ready to demo BCV at the sprint demo planning meeting.

**Comment by Sebastian-ubs** [comment]
reference to the first task
- https://github.com/paranext/paranext-core/issues/777
