### ISSUE TITLE
Shadcn Plumbing

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#776]
## Description
Create a super basic control in P.B using Shadcn/ui + Radix. The control should be one of the controls that makes up the BC control. If it is easy, put this into Storybook, otherwise make a new task to do the Storybook work.

**Comment by tjcouch-sil** [comment]
Note the [instructions for installing shadcn](https://ui.shadcn.com/docs/installation/manual) say you can choose between default and New York. Alex said to go with default for now.

**Comment by tjcouch-sil** [comment]
Tailwind has some nice suggestions for supporting dark mode https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection

**Comment by tjcouch-sil** [comment]
Shadcn set up in platform-bible-react at https://github.com/paranext/paranext-core/tree/shadcn-pbreact
