### ISSUE TITLE
Shoelace Plumbing

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#777]
**Description**
Create a super basic control in P.B using Shoelace. The control should be one of the controls that makes up the BC control. If it is easy, put this into Storybook, otherwise make a new task to do the Storybook work.

**Comment by tjcouch-sil** [comment]
Note in order to keep this working in offline-only mode, we must pull this in with npm and use our webpack bundler as mentioned in these steps https://shoelace.style/getting-started/installation#npm-installation

**Comment by jolierabideau** [comment]
Testing review not needed because we are not moving forward with Shoelace
