### ISSUE TITLE
Finish Implementing BCV Control Design

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#789]
**User Story**
As a (insert role here), I want (insert feature name/summary here) so that (insert reason here for the feature).

**Description**
Finishing Implementing BCV Control Design in the winning UI toolkit.

**Note**
A first and fairly complete implementation was made in the scope of this issue.
A number of additional but less essential features were identified, and a new issue was created for them: https://github.com/paranext/paranext-core/issues/859

**Comment by roopa0222** [comment]
Repo Test Steps:
On the main tool bar at the BCV component on Plaftform.Bible application.  

1.Selected book should be expanded when opening
	When clicked on a selected book, it is expanding and is working as expected.
2.Selected book title and chapter should be bold
	Verified that the book title is in bold and chapter is highlighted
3.Dropdown should scroll to three books above the selected book
	Verified if the a book is selected at Joshua when user has cursor over the component it shows 3 books above in dropdown.
4.Arrow key navigation
	Verified all the arrow keys and 'Enter' key are selecting the books and chapters
5.Manual scrolling
	Verified Manual scrolling is working as expected.
6.Searching with the input
	Was able type text in the input field and change books. Working as expected.
