### ISSUE TITLE
Implement C# project setting validators for Paratext-y project settings

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#794]
**User Story**
As a user or developer, I want Paratext project settings so that I can know things about the project like which books are available, whether the project is editable, etc.

**Description**
We need to be able to provide project settings for Paratext projects. These projects are served from the dotnet data provider process. As such, we need to provide project settings validators for ParatextStandard project settings from C#.

Add validators for the `ProjectSettingTypes` in `extensions\src\usfm-data-provider\index.d.ts` via C#.

**Comment by ianhewubs** [comment]
Here's some UI from PT9 showing the places in Paratext which determine how checks are run:

Project settings:
![image](https://github.com/paranext/paranext-core/assets/57722808/54a5bde2-0e4f-4884-a7b8-34db36a80b49)

Inventories:
![image](https://github.com/paranext/paranext-core/assets/57722808/0c67f8bf-cbbf-4959-9f42-e50442792aaa)

**Comment by tombogle** [comment]
- Add static function RegisterValidator to ProjectSettingsService.cs.
- That function should call PapiClient:RegisterRequestHandler. Pass in extensionProjectSettingValidator:<setting name> for the request type.
- Wait on RegisterRequestHandler to return before returning back to the caller.
- Test

**Comment by tombogle** [comment]
https://github.com/paranext/paranext-core/pull/882
