### ISSUE TITLE
No text appears in Mac version of 0.22

### ISSUE THREAD

**Issue by sewhite** [paranext/paranext-core#801]
I downloaded version 0.22 on my Mac, enabled it to open, and it opens. But no text is visible in the resource viewer, or the wordlist or the text collection
<img width="1035" alt="Screenshot 2024-03-21 at 9 12 12 AM" src="https://github.com/paranext/paranext-core/assets/16904461/0f8e605a-28c9-4add-9d56-c6ff1a62baf9">

Mac OS version 13.6.1
MacBook Pro 13 inch 2017 (Intel processor)

**Comment by lyonsil** [comment]
This is a known issue specific to Macs for now.  It is caused by a difference in how Unicode text is handled on Mac vs. Linux and Windows.  See #264 for tech details.  It is being worked on by someone helping with this project part-time.

**Comment by lyonsil** [comment]
This was fixed when #264 was resolved.
