### ISSUE TITLE
Fix web views not reloading when the extension host restarts (hot reloading)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#813]
**Describe the bug**
When you edit and save an extension or other source file, web views that are not opened immediately on startup (aka all the important ones) are not reloaded from their source. This failure hinders the functionality of hot reloading.

**To Reproduce**

1. Open Resource Viewer to some project
2. Change the source code for the resource viewer web view so some visual change occurs
3. Notice the resource viewer doesn't update.
4. Reload the page (Ctrl+R)
5. Notice the resource viewer is updated

**Expected behavior**
When changing source code, the web view should update appropriately.

**Comment by Sebastian-ubs** [comment]
is #928 happening because of this or is it something else?

**Comment by roopa0222** [comment]
I verified the fix with the latest code.
1.  Open 'Open PAPI Menu Testscreen', webview is opened with the title `PAPI Menu Test`
2. Added a `div` with `Webview Reload test`
3. Verified that the webview is updated with `hot reload`.

![Screenshot 2024-10-21 123746](https://github.com/user-attachments/assets/1deef9d2-97a5-45fd-9b03-addb24b12f47)
