### ISSUE TITLE
Improve SearchBar

### ISSUE THREAD

**Issue by jolierabideau** [paranext/paranext-core#846]
**Describe the bug**
1. If you set `isFullWidth` to false, the `TextField` is shortened but not the `Paper`

![Screenshot 2024-04-09 at 1 30 25 PM](https://github.com/paranext/paranext-core/assets/135999578/83deb2d5-e92f-47ef-8013-824c03a7c43b)

2. If you try to hit 'Enter' to search or use this `SearchBar` in a form, you will get this error:
```Blocked form submission to '' because the form's frame is sandboxed and the 'allow-forms' permission is not set.```
This `SearchBar` was built as a dynamic filter- it was not intended to be "submitted." Removing `component="form"` from the `Paper` element would probably solve this issue.

**To Reproduce**
Steps to reproduce 1) `isFullWidth`:
1. `<SearchBar isFullWidth={false} onSearch={() => logger.info('searching')} />`
2. `SearchBar` is not completely shortened

Steps to reproduce 2) Form submission error
1. `<SearchBar onSearch={() => logger.info('searching')} />`
2. Hit 'Enter' inside the `SearchBar`, will log above error in console.

**Expected behavior**

- [ ] When a user does not provide a value for `isFullWidth` or they provide `isFullWidth={false}`, the `TextField` and `Paper` have matching widths.
- [ ] Remove `component="form"` from the `Paper` element so that the `SearchBar` does not cause the form submit error
- [ ] ?? Rename the `SearchBar` to something like: `SearchFilter`, `DynamicFilter`, `FilterBar` ??

**Comment by roopa0222** [comment]
Verified the issues is resolved with https://github.com/paranext/paranext-core/pull/924
Tested and everything is working as it supposed to. 
Error message is not displayed when 'Enter' is hit .

![SearchBarCompFix](https://github.com/paranext/paranext-core/assets/133702629/fb4484be-05aa-4185-b852-d32a8e8369c8)
