### ISSUE TITLE
Update BCV control for field user testing

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#860]
The UX team needs to be able to run this from Windows. Creating a build for them will be helpful.  The testing will happen on April 27, so it would be important to have this done and verified working by the UX team by around April 25 at the latest.

- [x] zip a project in the exact format needed to drop it right into the `.platform.bible/projects` folder and send it to UX (@Sebastian-ubs is on it)
- [x] Get the resource viewer properly scrolling with the verse ref - fixed by #864
- [x] Make a branch where we take out all the weird junk like the junky web views that open at startup and have **only** the resource viewer available. About tab is pulled up by default, and they can open whatever they want. This branch will have just the top of app BCV selector `ux-test-base`
  - [x] Also remove the deuterocanonical books from the BCV Control
- [x] Make a branch off the branch mentioned above. Add a top bar with BCV selector to the tab somewhere so the resource viewer tab has it. This BCV selector on the tab still controls the global verse ref. No need for individually controlled verse refs. This branch will have both the top BCV and the tab BCV. `ux-test-both`
  - [x] Change the port number on this branch
- [x] Make a branch off the branch mentioned above. Remove the BCV selector at the top of the app. This branch will have just the tab BCV controls `ux-test-tab`
  - [x] Change the port number on this branch

Deliver to UX:
- [x] zip of other project (Sebastian)
  - https://drive.google.com/drive/folders/1Hc36QkFZR3HL-PBvokGiXT5teqQHG4dE
- [x] Build with BCV selector only at top of app
  - https://github.com/paranext/paranext-core/actions/runs/8836452443
- [x] Build with BCV selector at top of app and on each tab
  - https://github.com/paranext/paranext-core/actions/runs/8836453367
- [x] Build with BCV selector only on each tab
  - https://github.com/paranext/paranext-core/actions/runs/8836454302

<details><summary>Pre-Rolf-Jolie-Fix Builds</summary>
<p>

- [x] Build with BCV selector only at top of app
  - https://github.com/paranext/paranext-core/actions/runs/8823680992
- [x] Build with BCV selector at top of app and on each tab
  - https://github.com/paranext/paranext-core/actions/runs/8823682333
- [x] Build with BCV selector only on each tab
  - https://github.com/paranext/paranext-core/actions/runs/8823684237

</p>
</details> 

All the builds should:
- have no junky stuff
- have no DC books showing
- have different ports so they can load all at once (in production)

Note to UX: there is now a "Lorem Ipsum" tab to imitate a text resource. If you do not see it or it gets closed, you'll have to close the application, delete the `%APPDATA%\platform.bible\Local Storage` (on Windows; varies on other OSes) folder, and start the application again. Note the layout will reset, so you will have to set up your layout again.

**Comment by merchako** [comment]
Package 1

- [ ] per-tab BCV navigation
- [ ] independent scroll (optional)
- [ ] scroll groups (optional)

Package 2

- [x] global BCV navigation (done)
- [ ] shadcn/UI (optional)

Package 3 (optional)

- [ ] both per-tab and global BCV navigation
- [ ] scroll groups

**Comment by ianhewubs** [comment]
When you feel confident about what's achievable on this task, please could you let us know you think will be implemented? What gets implemented will determine how we will write our test scripts.

(Also I don't know what "independent scroll" refers to in @merchako 's "package 1". Can anyone clarify?)

**Comment by merchako** [comment]
If there’s no scroll groups, we risk getting unuseful reactions from users. So when there are multiple tabs, should they use the same reference or be separate?

- if separate, maybe users get scared of no scroll sharing
- if together, maybe the flexibility isn’t apparent

@mikelothers says most people will want to have synchronized scrolling. It only makes sense to sync scrolling if we have multiple resources.

**Comment by tjcouch-sil** [comment]
@paranext/paranext-ux the builds are now linked in the issue description! Let me know if you have any problems. At this point, I will likely only be able to respond to major issues that break the tests.
![image](https://github.com/paranext/paranext-core/assets/104016682/216bc767-0e10-4911-8b38-2c222d375db2)

**Comment by ianhewubs** [comment]
@tjcouch-sil Thanks for these, they look great. 

There's just one behaviour which I think might be problematic enough to be worth fixing if you are able: The first time I click in the BCV control, it opens the dropdown with GEN at the top of the list (not with the current book and chapter in view). If I click away and then click back in the control, or if I press the down arrow on the keyboard, the current book and chapter appear located and selected, as expected.
