### ISSUE TITLE
Hook in web view context into web view menu command call

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#866]
As a user, I want to be able to run menu items on web views that do things for those web views or projects so I can do meaningful things in web view menus.

----

- [x] In the webView menu owner(s), add an argument to all menuItem commands that is the webViewId of the current webView. Maybe this is just `toolbar.component.tsx`.
- [x] Add a function to the webView service that returns properties of the webView with a given webViewId. Those properties must include at least the open project(s) in the webView. TJ thought that perhaps adding the IDs to `WebViewDefinitionUpdatableProperties` would make sense, but it's up to whomever picks this up to provide that appropriately. In an ideal world any updates to the ID(s) would trigger an update so React can pass down the changes to components, but if this isn't doable in a reasonable amount of time then a one-time snap of the data when requested is fine.

[Settings & State Design Doc](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit)

**Comment by katherinejensen00** [comment]
Could be cool to write unit tests for this, but might also be hard because of all the mocking, depends on how much time you have.

**Comment by roopa0222** [comment]
Test Repo steps:

In my test extension updated the menus.json with the following
 
```
"webViewMenus": {
    
    "paranextExtTesting.reactTC20": {
      "includeDefaults": false,
      "topMenu": {
        "columns": {
          "paranextExtTesting.results": {
            "label": "%webView_paranextExtTesting_results%",
            "order": 1
          }
        },
        "groups": {
          "paranextExtTesting.resultsTop": {
            "column": "paranextExtTesting.results",
            "order": 1
          }
        },
        "items": [
          {
            "label": "%webView_paranextExtTesting_results_pass_te%",
            "group": "paranextExtTesting.resultsTop",
            "order": 1,
            "command": "paratextExtensionTest.resultsPass"
          },
          {
            "label": "%webView_paranextExtTesting_results_fail_te%",
            "group": "paranextExtTesting.resultsTop",
            "order": 2,
            "command": "paratextExtensionTest.resultsFail"
          }
        ]
      },
      "contextMenu": {
        "groups": {},
        "items": []
      }
    }
```
2. Added function in main.ts for the  "command": "paratextExtensionTest.resultsPass"
3. On the web-view added code to display the values from the 'Pass' menu click function
    On the UI I can display Web-view Id and Project details.

![Screenshot 2024-06-05 175110](https://github.com/paranext/paranext-core/assets/133702629/863978e7-e25a-4ac5-9f17-a6a96731bfe0)
![Screenshot 2024-06-05 175130](https://github.com/paranext/paranext-core/assets/133702629/ddff1643-c72c-42c7-a6d4-c1bd03c58b41)
