### ISSUE TITLE
Checks: Create reusable Inventory dialog

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#880]
As a member of the translation team, I want to be able to open an inventory dialog that shows me counts of different types that can be used in conjunction with related checks.

Assume we will recreate something similar to what was done in PT9 unless UX has a different design in place.

Examples: 

![Image](https://github.com/paranext/paranext-core/assets/128563279/8914770b-bb26-4fbc-9a8f-9ddc42e098d9)

![Image](https://github.com/paranext/paranext-core/assets/128563279/86a25e87-ed08-4285-ac81-379765be6d58)

![Image](https://github.com/paranext/paranext-core/assets/128563279/3f803b5e-076b-4214-880e-d32566650ca4)

**Comment by merchako** [comment]
Be aware that your screenshot is Paratext 9.4. There's a completely new interface in 9.5.

![image](https://github.com/paranext/paranext-core/assets/441789/952aafeb-f1f5-42df-a3f6-86ea1b39644a)

UX doesn't have any new mockups for you today; hopefully we'll have new sketches tomorrow.

**Comment by rolfheij-sil** [comment]
Wow, that looks nothing like the old interface indeed. Also in Paratext 9.4 it's a dialog, and in 9.5 it seems to be a docked tab.
Looking forward to the new mockups! Thanks!
