### ISSUE TITLE
Edits and the cursor placement in Scripture Editor [Web (Editable)] are off on Platform.Bible 

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#893]
**Describe the bug**
In my testing of Scripture Editor I found that the edits seem off. When I hit backspace (3 times consequently) on Psalm 1:3, after deleting 1 ('.') character, it jumps to beginning of the verse and deletes the verse number 2 and 1.

The cursor jumps to the beginning of the verse marker instead of next character. Cursor placement is not accurate.

**To Reproduce**
1. On the Scripture Editor (Editable) hit backspace 3 times on Psalm 1:3 at the end of verse
2. It deletes the first character (.) and the cursor jumps to beginning of the verse marker and deletes verse number 2 and 1.

**Expected behavior**
Expected behavior is to delete the 3 consecutive characters on a word backwards when backspace is hit 3 times. 

![Screenshot 2024-05-13 101923](https://github.com/paranext/paranext-core/assets/133702629/240a9ab0-100e-4f7c-9dd2-f2594f02324d)

**Comment by tjcouch-sil** [comment]
Fixed by #1008

**Comment by tjcouch-sil** [comment]
Follow-up issues:

[Typing a backslash breaks the editor · Issue #1007 · paranext/paranext-core](https://github.com/paranext/paranext-core/issues/1007)
[Error causes input to stop working after putting cursor before chapter number · Issue #133 · BiblioNexus-Foundation/scripture-editors](https://github.com/BiblioNexus-Foundation/scripture-editors/issues/133)
[Not providing view options makes cursor reset after every input · Issue #134 · BiblioNexus-Foundation/scripture-editors](https://github.com/BiblioNexus-Foundation/scripture-editors/issues/134)
[`onChange` fired when loading new text (`editorRef.current.setUsj(...)`) · Issue #135 · BiblioNexus-Foundation/scripture-editors](https://github.com/BiblioNexus-Foundation/scripture-editors/issues/135)
