### ISSUE TITLE
Create Docker Image for Marketplace Publishing Tool

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#913]
**Description**
Docker Image for Marketplace Publishing Tool.

**Comment by lyonsil** [comment]
Maybe this is done?
https://github.com/paranext/extension-marketplace-services/blob/main/marketplace-publishing-tool/Dockerfile

**Comment by katherinejensen00** [comment]
I think you are right. I will go ahead and close the issue.
