### ISSUE TITLE
Only one instance of project/resource will survive on restart

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#928]
**Describe the bug**
When opening a scripture editor (project) or resource multiple times, only 1 of them will have content after restarting Platform.Bible.
Console shows `web-view.component failed to retrieve web view content for` ... `Error: "Timeout reached when waiting for wait-for-net-obj to settle"` 
This happens at least since the [reworked folder structure](https://github.com/paranext/paranext-core/commit/47bb1ee4db5afc111c30cf3a705f3386c15a6716)

<details>
  <summary>Screenshots</summary>

|opened projects| ![Screenshot 2024-06-06 100212](https://github.com/paranext/paranext-core/assets/141921979/c1cd2728-ff12-45b7-819e-27f0a33ae594)      | 
| - | - | 
|after restarting platform| ![Screenshot 2024-06-06 100351](https://github.com/paranext/paranext-core/assets/141921979/5b2c9afd-2294-4da0-97f1-3848098850c5) | 
|console| ![Screenshot 2024-06-06 100435](https://github.com/paranext/paranext-core/assets/141921979/5558e3f9-336b-4e25-8a7f-d37710e44995) | 
</details>

**To Reproduce**
1. Put projects into the new folder structure `<user>\.platform.bible\projects\Paratext 9 Projects`
1. Start Platform
1. Open them twice with "open scripture editor" or "open resource viewer"
1. Restart Platform
  **Unexpectedly the duplicated webviews stay empty**
1. Debug with https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#debug-a-releasepackaged-build

**Expected behavior**
previosly opened projects would show up on restart - also when opened twice in Platform

**Comment by Sebastian-ubs** [comment]
Still happening in 37c0b3d
![grafik](https://github.com/paranext/paranext-core/assets/141921979/66d13224-5b22-44d5-bcbf-fe06504198d2)

**Comment by irahopkinson** [comment]
> Still happening in [37c0b3d](https://github.com/paranext/paranext-core/commit/37c0b3dcbd112d53b7b826fe4c92571dc66c3360)

@Sebastian-ubs Have you tried recompiling? A simple way to do this is make an innocuous change to a file like `src\main\main.ts`, e.g. add and remove a space, then save it. PB will recompile and reload. I find that if I have moved from another branch that the first compile often has the old code in it and the recompile is needed.

**Comment by tjcouch-sil** [comment]
There is a separate issue that sometimes causes web views not to load anymore if they do not load properly even once between refreshes. Did you close and open these webviews and then restart? I can't reproduce this issue anymore, so I will need help reproducing it if you still can.

**Comment by Sebastian-ubs** [comment]
It works fine in development (`npm start`)
![grafik](https://github.com/paranext/paranext-core/assets/141921979/4cae20c6-4e72-4ada-b1f2-c25730ad8b56)

In production (`Platform.Bible 0.2.0-commit.da9d954-latest.exe`) it now only fails with tabs that had been opened from an older Platform version.
![grafik](https://github.com/paranext/paranext-core/assets/141921979/24f9f8ee-5864-48b0-8622-caf168124a90)

This tab correctly opens up in the older 175a6fb but not in current da9d954 
![grafik](https://github.com/paranext/paranext-core/assets/141921979/96c07227-3582-4d27-9afe-c47d6b4758b4)

**Comment by tjcouch-sil** [comment]
Could you please attach a log file from starting up the new vs the old verisons that do and don't work with the old web view? Not all old tabs will work every time we make updates, especially breaking changes, so it might just be some old data that doesn't work with the new system. However, I did look at the code at the revision you mentioned, and it didn't look at first glance like it was much older.

**Comment by Sebastian-ubs** [comment]
With attaching remote debugger I got
> renderer.js:2 Unexpected process type: undefined
7807 @ renderer.js:2
renderer.js:2 09:45:14.480 › Starting renderer
renderer.js:2 09:45:14.989 › Got clientId 3
renderer.js:2 09:45:24.123 › No WebView provider found for WebView type platformScriptureEditor.react
renderer.js:2 09:45:24.123 › web-view.component failed to retrieve web view content for {"id":"d280c9de-6dcb-4879-89a1-7c4e2548fa4c","tabType":"webView","data":{"title":"ESVUS16 (Editable)","webViewType":"platformScriptureEditor.react","id":"d280c9de-6dcb-4879-89a1-7c4e2548fa4c","state":{"isReadOnly":null},"projectId":"F421FE261DA7624F0405A602838BBED467F5FDB2","contentType":"react"}}: Error: getWebView: Cannot find Web View Provider for webview type platformScriptureEditor.react

However on restarting Platform several times I got it to load one of the times, so seems to be some race condition / timing issue.
![grafik](https://github.com/paranext/paranext-core/assets/141921979/b56c0ac0-6b4a-4555-be8b-d610013dc504)

**Comment by Sebastian-ubs** [comment]
uff, after trying again, I can more precisely say, that it is not a special tab, but the most top left tab of my layout always.
> 17:34:14.454 › No WebView provider found for WebView type platformScriptureEditor.react
renderer.js:2 17:34:14.454 › web-view.component failed to retrieve web view content for {"id":"c318baec-c90f-4a0b-8f5d-b966c9111762","tabType":"webView","data":{"title":"NIV84 (Editable)","webViewType":"platformScriptureEditor.react","id":"c318baec-c90f-4a0b-8f5d-b966c9111762","state":{"isReadOnly":null},"projectId":"A6219DB975224F500877392222CF654A32477065","contentType":"react"}}: Error: getWebView: Cannot find Web View Provider for webview type platformScriptureEditor.react
![grafik](https://github.com/paranext/paranext-core/assets/141921979/09f54055-fccf-4e70-998d-0d9e312e8a8b)

**Comment by Sebastian-ubs** [comment]
Can again confirm the timing issue, as after the 5th or so trial I got it to show up one time. Attaching [main.log](https://github.com/user-attachments/files/16070896/main.log)

![grafik](https://github.com/paranext/paranext-core/assets/141921979/f8737c29-4de5-41a9-9dc7-5b86e1a5c5a9)

**Comment by Sebastian-ubs** [comment]
some new / clean logs: [main.log](https://github.com/user-attachments/files/16071156/main.log)
> renderer.js:2 Unexpected process type: undefined
7807 @ renderer.js:2
renderer.js:2 17:51:32.080 › Starting renderer
renderer.js:2 17:51:32.381 › Got clientId 3
renderer.js:2 17:51:41.555 › No WebView provider found for WebView type platformScriptureEditor.react
renderer.js:2 17:51:41.556 › web-view.component failed to retrieve web view content for {"id":"d280c9de-6dcb-4879-89a1-7c4e2548fa4c","tabType":"webView","data":{"title":"ESVUS16 (Editable)","webViewType":"platformScriptureEditor.react","id":"d280c9de-6dcb-4879-89a1-7c4e2548fa4c","state":{"isReadOnly":null},"projectId":"F421FE261DA7624F0405A602838BBED467F5FDB2","contentType":"react"}}: Error: getWebView: Cannot find Web View Provider for webview type platformScriptureEditor.react

**Comment by Sebastian-ubs** [comment]
looks like the first webview of every extension fails to load
> renderer.js:2 Unexpected process type: undefined
7807 @ renderer.js:2
renderer.js:2 18:23:57.196 › Starting renderer
renderer.js:2 18:23:57.734 › Got clientId 3
renderer.js:2 18:24:06.930 › No WebView provider found for WebView type paratextBibleTextCollection.react
renderer.js:2 18:24:06.930 › web-view.component failed to retrieve web view content for {"id":"192bc760-52ae-48ea-bb62-975b0868f23e","tabType":"webView","data":{"title":"Text Collection","tooltip":null,"webViewType":"paratextBibleTextCollection.react","id":"192bc760-52ae-48ea-bb62-975b0868f23e","iconUrl":"papi-extension://paratext-bible-text-collection/assets/Group24.svg","state":{"projectIds":[]},"projectId":"","contentType":"react"}}: Error: getWebView: Cannot find Web View Provider for webview type paratextBibleTextCollection.react
(anonymous) @ renderer.js:2
renderer.js:2 18:24:06.940 › No WebView provider found for WebView type platformScriptureEditor.react
renderer.js:2 18:24:06.940 › web-view.component failed to retrieve web view content for {"id":"56199c2c-943b-44b2-a5f3-1d6d07d22a08","tabType":"webView","data":{"title":"PCM (Editable)","webViewType":"platformScriptureEditor.react","id":"56199c2c-943b-44b2-a5f3-1d6d07d22a08","state":{"isReadOnly":null},"projectId":"B459B0BD26B6FD5A55E2FDE5390E08B84DD1A2AE","contentType":"react"}}: Error: getWebView: Cannot find Web View Provider for webview type platformScriptureEditor.react
(anonymous) @ renderer.js:2
about:srcdoc:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
about:srcdoc:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.

new debug logs: [main.log](https://github.com/user-attachments/files/16071493/main.log)
