### ISSUE TITLE
Reload Extensions menu item from Main Menu in P.B reloading extensions only few times.

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#933]
**Describe the bug**
As part of my automation testing, I am reloading my extension from the Platform.Bible using hamburger Main menu , 'Reload Extensions' menu item.
I noticed that extensions are reloaded properly 2-3 times. After that clicking on 'Reload Extensions'  any number of times does not cause any effect. The UI is not reloaded.

**To Reproduce**
In my test extension I have 2 web -views.
Close 1 web-view and click on 'Reload extensions'. It reloads 2 (web-views) from my test extensions.
After 2 times of 'Reload Extension' extensions are not reloaded.

**Expected behavior**
'Reload Extensions' - Supposed to reload extensions all times? 
[main_reloadExtensions.log](https://github.com/user-attachments/files/15792668/main_reloadExtensions.log)

**Comment by tjcouch-sil** [comment]
Possibly related to #813

**Comment by roopa0222** [comment]
I noticed that in the logs if 'Reload Extension' menu item is clicked 5 times , I can only see 2 successful logging of 1st message in the activate function from main.ts file. 

export async function activate(context: ExecutionActivationContext): Promise<void> {
  **logger.info('Test Extension is activating!');**

**Comment by roopa0222** [comment]
Verified the fix and `Reload Extensions` menu item on the main menu is working as expected.

I was able to reload extensions successfully using the menu item more than 4 times.
