### ISSUE TITLE
Add first pass Send/Receive

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#949]
**User Story**
As a translator, I want to be able to collaborate with others on my Scripture projects so that we can work together effectively.

**Description**
Develop a rough-cut first draft of Send/Receive functionality in Platform.Bible.

- [x] Create simple S/R dialog
  - Internet server only for now (try putting in a selector that only has one option)
- [x] Web view menu item to S/R a project (S/R and displays results)

PT9 Send/Receive Dialog
![image of PT9 Send/Receive Dialog](https://github.com/paranext/paranext-core/assets/104016682/f8a2a50d-7d75-4d05-8dd9-954888b5b1ac)

![Image](https://github.com/user-attachments/assets/1b024af7-dcf7-4b8b-8a59-27e6761bea4d)

S/R Results dialog
![image of S/R Results dialog](https://github.com/paranext/paranext-core/assets/104016682/4c1d2c37-b3d4-41d2-8b10-763c0139c232)

![Image](https://github.com/user-attachments/assets/49e1581d-e79e-4606-adc0-c2674566c365)

![Image](https://github.com/user-attachments/assets/58ab80d6-d15b-4fa8-b6f0-5bc86a43ab98)

![Image](https://github.com/user-attachments/assets/8b79459f-b5a2-40ae-999b-606987a40c83)

![Image](https://github.com/user-attachments/assets/677c46ac-cf74-43f9-a612-b3c317f9181e)

![Image](https://github.com/user-attachments/assets/16dd1645-4d9c-43e5-bb6f-d07989e61df6)

![Image](https://github.com/user-attachments/assets/20d9864f-d7cb-4763-84df-f454595bdba6)

**Comment by tjcouch-sil** [comment]
Methods from `SendReceiveProjectsForm.cs`

- [ ] Determine if internet S/R is available
  - CheckSourceIsAvailable - logic for internet S/R
  - SetInternetDisabledText - indicates why internet S/R is not available
- [ ] List projects available for S/R
  - Get list of online projects and S/R-enabled local projects
    - maybe constructor has info? See CoaxUserToDoASendReceive
  - Determine new/edited status
    - Maybe trace GetProjectsModifiedByAnyone?

**Comment by jcuenod** [comment]
Not sure if this is an appropriate place for what is essentially a feature request, but I often find myself wanting to "receive without sending". Conflict resolution is obviously a complicated problem - in my case, I am always willing to destroy local changes. I am wanting to be sure I don't push local changes. At the very least, I want to note this here because I'd love to see the design support this kind of feature in the future, even if not immediately.

**Comment by tjcouch-sil** [comment]
Looks like we will have to find mercurial on the system or bundle it in like Paratext does (on Windows). There are also a handful of files we need to distribute. Some notes [from a discord conversation](https://discord.com/channels/892072317436448768/902938040362729552/1266395026305585199):
- Paratext uses 4.8.2
- Newer than 4.8.2 will have problems with the `init` function with default config. John W thinks this would only affect if P.B created a USB repo and Paratext tried to use it. But there are init arguments that make it backwards compatible
- Paratext has Python 2.7 scripts that Mercurial must be able to run. Therefore it is stuck on [versions 4.3-6.1ish](https://wiki.mercurial-scm.org/SupportedPythonVersions)
- We may be able to build Mercurial ourselves and distribute it ourselves
- It seems the oldest Mac build of Mercurial on the site is [TortoiseHg 5.3](https://www.mercurial-scm.org/release/tortoisehg/macos/)
- I have no idea how getting Mercurial for linux would work. It's on `apt-get` and some other package repos, but I can't list versions. There are also some rpm files on the site.


[Mercurial downloads](https://www.mercurial-scm.org/downloads)
[DeveloperRepos - Mercurial](https://wiki.mercurial-scm.org/DeveloperRepos)
[hg-stable: 197f092b2cd9 /](https://repo.mercurial-scm.org/hg-stable/file/4.8.2)
[BuildingOnWindows - Mercurial](https://wiki.mercurial-scm.org/BuildingOnWindows)
[BuildingPackages - Mercurial](https://wiki.mercurial-scm.org/BuildingPackages)

**Comment by tjcouch-sil** [comment]
![Image](https://github.com/user-attachments/assets/a001feb9-f85b-4a7b-bff8-ef43278a7036)



![Image](https://github.com/user-attachments/assets/bff2812b-c438-4e53-9b60-44669031a56d)



![Image](https://github.com/user-attachments/assets/ad02aeec-7e61-4764-87c6-0dd6e5c7aa56)

**Comment by tjcouch-sil** [comment]
To use Send/Receive for now:

On Windows:
1. Install Paratext 9
2. Enter your registration information in Paratext 9

On Linux or Mac:
1. Install Mercurial (Ubuntu: run `sudo apt-get install mercurial`)
2. Copy `InternetSettings.xml` and `RegistrationInfo.xml` from a Windows machine `%localappdata%/Paratext95` to `~/.local/share/Paratext95` (or set them up however you want)

**Comment by tjcouch-sil** [comment]
PRs:
[Made extension contributions load in order, added spinner, updated ParatextData to 9.5.0.6, misc bug fixes and improvements - 8 unreplied - Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1066)
[Include untracked changes aka new code files in patches - Reviewable](https://reviewable.io/reviews/paranext/paranext/25)
[Added send/receive service to dotnet process by tjcouch-sil · Pull Request #3 · paranext/paratext-10-studio](https://github.com/paranext/paratext-10-studio/pull/3)
[Added Send/Receive extension including dialog and menu items by tjcouch-sil · Pull Request #67 · paranext/paratext-bible-internal-extensions](https://github.com/paranext/paratext-bible-internal-extensions/pull/67)

Documentation:
[Troubleshooting Guide · paranext/paranext Wiki](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#sendreceive-is-not-working---registration-is-not-set-up)
[Set up Send Receive Functionality · paranext/paranext Wiki](https://github.com/paranext/paranext/wiki/Set-up-Send-Receive-Functionality)

**Comment by roopa0222** [comment]
Verified the Send/Receive functionality on the Paratext 10 studio.

1. Verified that all the projects that I have access to are displayed in the Send/Receive dialog
2. Verified that the changes I made are Send/Receive
3. Verified I can get all the changes made by other Users (TJ)
4. Verified that a merge conflict is displayed when 2 users made changes on the same book and same verse . 
Gen 1 verse showed up as conflict as changes are made in the same verse. 

![SendRecieve_zzz6](https://github.com/user-attachments/assets/fb5741c7-f835-42df-a336-c26881139a03)

![SendReceive_Changes](https://github.com/user-attachments/assets/066a3472-115e-41fd-9ee0-7ee45ad702d7)

![SendReceive_TJ_Updates](https://github.com/user-attachments/assets/1a53a096-9154-43b7-81ca-854bd0b39723)

![SendReceive_PB_MergeConflict](https://github.com/user-attachments/assets/ce14d18f-00ed-454c-b90f-3fbbb89fc9be)
