### ISSUE TITLE
Set up build process for Paratext 10 Studio

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#951]
**User Story**
As a user, I want to be able to download and run Paratext 10 Studio, containing Platform.Bible and some extensions, so that I can start with a good set of features.

As a product manager or developer, I want certainty as to the relationships between all these different repositories and how they combine into our product so I know how to think about the structure of the software and where to put functionality/extensions.

**Description**
We currently have build processes that create Platform.Bible running in `paranext-core`. Now we want to white label it and bundle `paratext-bible-extensions` in with it to create Paratext 10 Studio.

- Create a script and GitHub Action that enable building Paratext 10 Studio:
- [x] Get `paranext-core`
  - [x] Clone `paranext-core`
  - [x] Fulfill build environment requirements for `paranext-core`
- [x] Modify `paranext-core`
  - [x] Change the app name
  - [x] Change the file paths (user folder, temp folder, etc.)
  - [x] Change "Platform.Bible" in localized strings? Or maybe we need to support localized string keys in the localized strings...? `%product_name%`
  - [x] Change the icon
  - [x] Change colors?
- [x] Include
  - [x] Clone [`paratext-bible-extensions`](https://github.com/paranext/paratext-bible-extensions) and [`paratext-bible-internal-extensions`](https://github.com/paranext/paratext-bible-internal-extensions)
  - [x] Build their zip files and include in the electron build (`extraResources` in `electron-builder.json5`?)
- [x] Build `paranext-core`

**Comment by tjcouch-sil** [comment]
Note: version numbers do not need to be synced between Platform.Bible and Paratext 10 Studio

**Comment by tjcouch-sil** [comment]
Potential cost analysis

Note: [Public repos](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) get Linux and Windows machines that have double the CPU and RAM that the machines used for [private repos](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories). We will just double numbers for Windows and Linux as an estimate.

Free plans get 2000 minutes per month and 500MB (per month...? unclear) storage.
- Minute multiplier (each platform costs something different)
  - Linux: 1 ($0.008/min)
  - Windows: 2 ($0.016/min)
  - macOS: 10 ($0.08/min)

[paranext Package workflow](https://github.com/paranext/paranext/actions/runs/9895338182/usage) (Public)
- windows-latest 8m 25s
- macos-latest 6m 18s
- ubuntu-latest 3m 51s
- Artifacts: 589 MB total

Storage:

Actions time:

[paranext Publish workflow](https://github.com/paranext/paranext/actions/runs/9895338182/usage) (Public)
- windows-latest 14m 26s
- macos-latest 8m 31s
- ubuntu-latest 4m 27s
- Release files: ? (Platform.Bible's latest had ~1034MB.)

Storage: 

Actions time:

**Comment by tjcouch-sil** [comment]
Platform.Bible White-labeling Repo: https://github.com/paranext/paranext
Paratext 10 Studio: https://github.com/paranext/paratext-10-studio

Set up to run every Monday morning. Hopefully costs will be under $6/month. Set a $10 monthly spending limit.

Manually ran first build of Paratext 10 Studio:
[Windows](https://github.com/paranext/paratext-10-studio/actions/runs/10066522048)
[Mac](https://github.com/paranext/paratext-10-studio/actions/runs/10066522048/attempts/3)
[Linux](https://github.com/paranext/paratext-10-studio/actions/runs/10066522048/attempts/2)

**Comment by roopa0222** [comment]
Testing Steps: 

Platform.Bible White-labeling Repo: https://github.com/paranext/paranext
Followed instruction on Read me 

```
git clone https://github.com/paranext/paranext.git
cd paranext
npm install
npm run build-ci 
```
After completion, I was able to open Platform.Bible.exe from the 
C:\Repos\paranext\dist\Platform.Bible 0.0.1.exe

![Screenshot 2024-07-25 122554](https://github.com/user-attachments/assets/7634a8ff-3ca9-4c9f-8a22-98baac339f5f)

Paratext 10 Studio: https://github.com/paranext/paratext-10-studio
```
git clone https://github.com/paranext/paratext-10-studio.git
cd paratext-10-studio
npm install
npm run build-ci  
```
After completing the above was able to open the Paratext 10 Studio application at

C:\Repos\paratext-10-studio\dist\Paratext 10 Studio 0.0.1.exe

![Screenshot 2024-07-25 120256](https://github.com/user-attachments/assets/402fee61-03d7-4b43-978f-86f1ce43e0fa)
