### ISSUE TITLE
Enable extensions to manage extensions (special privileges required)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#965]
**User Story**
As an extension developer, I want to be able to ask for special privileges to manage extensions so that I can serve an extension marketplace.

**Description**
Create a way for an extension to request special privileges to manage extensions (install, uninstall, activate, deactivate, etc.). The extension marketplace will use this for managing extensions.
- [x] Add some kind of area in the extension manifest where extensions can list an array of special privileges they need for their extension to work (this can be displayed in the extension marketplace in some way so people know what they're installing)
  - [x] For now, just add the ability for extensions to request to manage extensions
- [x] Add into the `extension.service.ts` some extension-related functions
  - [x] Install and uninstall extensions (I guess just throw them into the `installed-extensions` folder)
    - [ ] Maybe make a network event for these occurrences like `onDidInstallExtension` and `onDidUninstallExtension` or `onDidChangeInstalledExtensions` or something? Doesn't need to be special privileged; should probably be on papi
  - [x] List installed extensions (maybe this can just be a command or something. Doesn't need to be special privileged; should probably be on papi)
- [x] Pass into the extension's `activate` function some extra stuff for managing extensions if it has that special privilege
  - Maybe just leave whatever this extra stuff is `undefined` if the extension doesn't have that special privilege so they can know if they don't have it. But feel free to be creative

**Comment by Sebastian-ubs** [comment]
Wouldn't it be easier to implement the extension management as part of core and only uplink this to the the Paratext marketplace provider in a Paratext extension?

**Comment by tjcouch-sil** [comment]
> Wouldn't it be easier to implement the extension management as part of core and only uplink this to the the Paratext marketplace provider in a Paratext extension?

Extension management is a privilege we want to give to extensions so they can do what they want. If someone wants to build a marketplace with some other API, they can :)

**Comment by Sebastian-ubs** [comment]
> If someone wants to build a marketplace with some other API, they can :)
Right, which they could also do, when extension management would be part of core, but only extensions can add a repo / url / api to query extensions from.

**Comment by lyonsil** [comment]
If someone else takes Platform and makes their own app, they probably want to control the look/feel of the marketplace, not just the backend service details.

**Comment by roopa0222** [comment]
Testing Repos steps:

Updated the test extension with the latest `paranext-extension-template`.
1.updated the manifest.json with below lines 
```
"extensionDependencies": {},
 "elevatedPrivileges": ["manageExtensions"],
```
2. In the main.ts added the to test the methods available on ManageExtensions
```
const installExtension = async (context: ExecutionActivationContext) => {
  logger.debug(`Here in the install extension command ${JSON.stringify(context)}`);
  context.elevatedPrivileges.manageExtensions?.installExtension(
    'https://github.com/paranext/paratext-bible-extensions/releases/download/v0.0.1/paratext-bible-word-list_0.0.1.zip',
    154738,
    {
      sha512:
        'pLpFYPq67DSflQsJj9WcWWO+jdbJ9ylyW4Vs6gksIdbT9eqI2CE3/kNPrLdSNpp57ga6DGlciISSwliSOiLB3A==',
    },
  );

  return `Extension Installed`;
};

const disableExtension = async (context: ExecutionActivationContext) => {
  context.elevatedPrivileges.manageExtensions?.disableExtension({
    extensionName: 'paratext-bible-word-list',
    extensionVersion: '0.0.1',
  });
  return `Extension Disabled`;
};

const enableExtension = async (context: ExecutionActivationContext) => {
  context.elevatedPrivileges.manageExtensions?.enableExtension({
    extensionName: 'paratext-bible-word-list',
    extensionVersion: '0.0.1',
  });
  return `Extension Enabled`;
};

const allInstExtensions = async (context: ExecutionActivationContext) => {
  const allInstExtensionsList =
    await context.elevatedPrivileges.manageExtensions?.getInstalledExtensions();

  return `${JSON.stringify(allInstExtensionsList)}`;
};

```
3. Added commands and updated the UI to have test buttons to invoke individual functions.
4. I can see the extesnions zip is downloaded and saved under the `installed-extensions` folder at `C:\Repos\paranext-core\dev-appdata\installed-extensions` in dev environment.
5. When extension is disable the zip is moved to `disabled-extensions` folder at `C:\Repos\paranext-core\dev-appdata\disabled-extensions` .
6. When a disabled extension is `enabled` the zip is moved back to `installed-extensions` folder

![FoldersUpdated_722224](https://github.com/user-attachments/assets/53aa039e-544a-45ac-a4cd-c6742ca3d1ec)
![InstalledExtensions_7222024](https://github.com/user-attachments/assets/8b5b9f58-834e-4936-931d-614deed1dc1c)

**Comment by lyonsil** [comment]
Looks great. Thanks for verifying!
