### ISSUE TITLE
Add Paratext user login (input registry credentials)

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#971]
**User Story**
As a Bible translator, I want to be able to log in as my Paratext Registry user without opening Paratext 9 so that I can see available resources, use S/R, etc. without having to log in on Paratext 9.

**Description**
Create a way to log into the Paratext Registry in Platform.Bible. When you open PT9 the first time, it asks for a registry code or something along those lines. Basically, we want to be able to do that in Platform.Bible. This user credential needs to go into ParatextData.dll; we probably don't need it elsewhere.

Do this in relation to the identity stuff. Make a nice secure dialog that isn't shared origin and all that. #616

This should go in Platform.Bible

**Comment by lyonsil** [comment]
This is closely related to authentication providers in the [identity spec](https://docs.google.com/document/d/1AIXR1TXjrq8HgwHAOKMMTnf9JiE9j6z6IfmgwmPSxdU/edit#heading=h.hgwlx0t7ncvp).

**Comment by tjcouch-sil** [comment]
Can you access unrestricted resources without a PT registration?

**Comment by tjcouch-sil** [comment]
We have come to the conclusion that users who have valid Paratext registration should be able to access the DBL from Platform.Bible and Paratext 10 Studio. As such, this registration stuff will now be put in Platform.Bible.

**Comment by tjcouch-sil** [comment]
Lots of stuff split off to #1254 to get this finished out and move on with other things for now.

**Comment by merchako** [comment]
@tjcouch-sil I’m wondering what the possible error states are for the dialogue. Do you get error types from the registry or make up your own?

If there are already established error types, could you post get info on them so UX can write error messages?

**Comment by tjcouch-sil** [comment]
> @tjcouch-sil I’m wondering what the possible error states are for the dialogue. Do you get error types from the registry or make up your own?
> 
> If there are already established error types, could you post get info on them so UX can write error messages?

@merchako 

1. There are a couple of places where there are catch-all try/catches that would return something like `Getting Paratext Registration data failed! {e.message}` or `Setting Paratext Registration data failed! {e.Message}`. I don't expect these to happen, but FYI
2. If somehow the user submitted without making any changes (would be a glitch in the UI): `No changes were made to the registration data` (not localized because I was lazy since this should be impossible)
3. User provides an invalid username according to the C# code but somehow passes the UI check of `^.+@.+\\..+$`: `Please enter a valid email address.` (localized)
4. User submits an invalid registration according to the C# code (it uses the name and code to check this, but I don't know particular details): `This registration code is not correct for this user.` (localized)
