### ISSUE TITLE
First web view per web view type is not opening on startup

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#991]
**Describe the bug**
Sebastian is seeing that, sometimes, the first web view per web view type doesn't open. The logs seem to indicate the 10-second timeout  for the first web view runs out before the web view provider is ready. There could be some weird timing things.

**To Reproduce**
Please see latest handful of comments on #928 - this issue is a follow-up to what seems to be a very similar but likely different bug than reported there.

**Expected behavior**
The web views all pull up appropriately

**Comment by tjcouch-sil** [comment]
Latest developments:

I had some thoughts after looking at Sebastian's log files:

Suspects:
- Retrying from server is not lagging with frozen ui so it doesn't wait as long and just doesn't make it happen soon enough
- getWebView now gets the PDP for the name setting instead of just getting metadata. Maybe that takes too long? Some things waiting on each other indefinitely? Not waiting properly (probably not because a second web view requests early and does indeed get the result in time)?

Possible solutions
- Change web-view-provider.service.get to wait on the network object instead of just getting it?
- Increase maxAttempts server-network-connector.service.ts for now until we have good waiting

I sent Sebastian a special build that waits on the web view provider network object for 20 seconds before making the request to it, and he responded with the following:

> I had mixed results:
> - sometimes working fine to also load the first tab
> - sometimes not loading any tab
> 
> When nothing loaded I got
> > renderer.js:2 10:53:51.175 › web-view.component failed to retrieve web view content for {"id":"abdc63ff-4442-4563-bb31-2c25cfed6f28","tabType":"webView","data":{"title":"HEBGRK, HPUXK, PCM, NLT07 (HEB 2:1)","tooltip":"Text Collection\n\nHEBGRK\nHPUXK\nPCM\nNLT07","webViewType":"paratextBibleTextCollection.react","id":"abdc63ff-4442-4563-bb31-2c25cfed6f28","iconUrl":"papi-extension://paratext-bible-text-collection/assets/Group24.svg","state":{"projectIds":["000F2B0426E1457E8E496834AAA30FCE000000F1","88EB71CE6ECEA3EB4E0080D437C64A9D546E3910","B459B0BD26B6FD5A55E2FDE5390E08B84DD1A2AE","FC1FC7A30722D18AD00E5316117994A4698F3C47"]},"projectId":"FC1FC7A30722D18AD00E5316117994A4698F3C47","contentType":"react"}}: Timeout reached when waiting for wait-for-net-obj with details {"id":"paratextBibleTextCollection.react-webViewProvider"} to settle

**Comment by Sebastian-ubs** [comment]
I am unable to reproduce this any longer - with no version. Maybe related to upgrading my nodejs version, not sure 🤷

**Comment by tjcouch-sil** [comment]
That's very strange. Node version shouldn't impact the production application because Electron bundles node into the executable. :weary: hope this doesn't come back to bite us...

**Comment by Sebastian-ubs** [comment]
yes, unfortunately I cannot tell the reason for it not happning any longer - which is not a change in in Platform, because the old version that previously did not work is now working
