### ISSUE TITLE
Make Checking Results List project-aware

### ISSUE THREAD

**Issue by tombogle** [paranext/paranext-core#993]
This probably needs some input from UX.

As a user, I need to be able to choose whether to see the Checking Results List on a per-project basis.
**UX:**

- where/how should the user choose whether to display the list?
- should this list automatically appear docked to the edge of the/a corresponding editor for the project?)

When looking at the list, I also need to know which project it applies to. _Note: currently the list displays the project name, but it just uses stubbed out code to generate the errors for a hard-coded fictitious project called **Dummy project**._

**Comment by tjcouch-sil** [comment]
Closing to defer to a more granular listing of the work in #1222 and #1232
